### ISSUE TITLE
AutoOpen/AutoClose examples won't work

### ISSUE THREAD

**Issue by tomkuijsten** [tfsaggregator/tfsaggregator#104]
I already made a bunch of fixes for the [samples](https://github.com/tfsaggregator/tfsaggregator/wiki/Auto-Open-Auto-Close). But I can't test it for real, because I don't have the Agile process template and the sample does (at least, that's my assumption from the state values).

Update and test it would be my suggestion.

**Comment by jessehouwing** [comment]
I'll have a look at the sample. It was taken from an issue posted by another user and I haven't tested it on my own instance.

**Comment by jessehouwing** [comment]
Can you share the fixes in a pull request?

**Comment by tomkuijsten** [comment]
Ofcourse, you want it in the wiki or somewhere in the sample directory in the source?

**Comment by jessehouwing** [comment]
I suppose the sample directory. I can take that into the Wiki. A couple of gists would also work. Prevents me from having to fix the things you've already found.

**Comment by tomkuijsten** [comment]
Just created a [gist](https://gist.github.com/tomkuijsten/c090269308cc86968206#file-tfsaggregator-samples-xml). 

It contains two rules:
 - AutoOpen: Update Work Item to Committed if a task became "active"
 - AutoClose: Update Work Item to Done if a all child tasks are Done or Removed

**Comment by tomkuijsten** [comment]
Really nice work with this tool btw! Wherever I search for TFS/ALM samples and tools, I find xpirit people :)

**Comment by jessehouwing** [comment]
I updated the sample. This was for the Scrum template, right?

**Comment by tomkuijsten** [comment]
Correct
