### ISSUE TITLE
DebugView not showing any logging

### ISSUE THREAD

**Issue by tomkuijsten** [tfsaggregator/tfsaggregator#105]
Followed the guidelines from [here](https://github.com/tfsaggregator/tfsaggregator/wiki/Troubleshooting#enable-logging)

Some more details:
 - Windows 2012 R2, TFS 2015 Update 1, TFSAggragator 2.0.138-master
 - DebugView is showing logging, but not from the tfsaggregator.
 - My policy is working on TFS, it updates work item state when a task is finished
 - The logging config in the [policy file](https://gist.github.com/tomkuijsten/edc59d2344525b6d74b2) is set to Diagnostic

**Comment by giuliov** [comment]
**Capture Global Win32** is flagged?

**Comment by tomkuijsten** [comment]
As I said, I followed the guidelines :) So that's a yes.

**Comment by giuliov** [comment]
Try remove the DebugView filter.

**Comment by tomkuijsten** [comment]
Tried that already, doesn't work. It's not that big of a problem to me, cause with the excellent test console I can debug just fine. Just wanted to let you know that it doesn't work out of the box if you follow your guidelines.

**Comment by giuliov** [comment]
Yes: developing is much easier with the console, but there is nothing like the living system. I am sure it worked in the past, so I will file this as a bug to review.

**Comment by giuliov** [comment]
Cross-posting from #109.

Just realized that the only the Debug build writes messages to debugger output, that is what DebugView captures.

To use build 138 you need to uninstall the Release MSI, install the Debug one. After troubleshooting is complete and the policy file reach final version, redo the unsintall/install to have the Release version.

I will review the documentation, and issue some source code fix to include in future releases.

**Comment by sstjean** [comment]
It looks like the problem is that the ServerTextLogger.Log() method (Aggregator.ServerPlugin / ServerTextLogger.cs - line 60) uses Debug.Writeline() instead of Trace.Writeline().  

The Debug object is not compiled into the DLL when you build with Release settings.  The Trace object is always compiled into the DLL which means that you can always turn on Tracing and see the output in DebugView.   The original DebugView logging used Trace.Writeline() for just this reason.

**Comment by giuliov** [comment]
Thanks Steve, but line 60 was there on purpose as default trace have nasty formatting; just forgot to document the reasoning behind.

In v2.0.138, a log message goes to:
- Debug output (only in debug builds)
- Application EventLog (_TFS Services_ source) via `TeamFoundationApplicationCore.Log`
- Application EventLog (_TFS Aggregator_ source) when Warning or Critical level
So, regarding the OP Issue, by looking in Application EventLog he should find the trace messages.

With commit aa6edee a log message goes to:
- Debug output
- Application EventLog (_TFS Aggregator_ source) when Warning or Critical level
- Trace listeners

Commit 3bc2c41 send user messages -- i.e. `logger.Log` calls in Rules -- to a specific trace source: `TfsAggregator.User`.

Now, you can send traces to a file by adding to `C:\Program Files\Microsoft Team Foundation Server 14.0\Application Tier\Web Services\web.config` a `system.diagnostics` section similar to the this:

```
<system.diagnostics>
  <sources>
    <source name="TfsAggregator.ServerPlugin" switchValue="All">
      <listeners>
        <remove name="Default" />
        <add name="filelog" />
      </listeners>
    </source>
    <source name="TfsAggregator.User" switchValue="All">
      <listeners>
        <remove name="Default" />
        <add name="filelog" />
      </listeners>
    </source>
  </sources>
  <sharedListeners>
    <add name="filelog"
         type="Microsoft.VisualBasic.Logging.FileLogTraceListener, 
                   Microsoft.VisualBasic, Version=10.0.0.0, 
                   Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
         BaseFileName="TfsAggregator.log"
         DiskSpaceExhaustedBehavior="ThrowException"
         Location="Custom"
         CustomLocation = "C:\Temp"
         MaxFileSize="81920000"
         LogFileCreationSchedule="Daily"/>
  </sharedListeners>
  <trace autoflush="true"/>
</system.diagnostics>
```
