### ISSUE TITLE
New task not triggering rule

### ISSUE THREAD

**Issue by tomkuijsten** [tfsaggregator/tfsaggregator#106]
Am I correct that a new work item doesn't trigger a rule?

**Comment by jessehouwing** [comment]
It should, but it may be that you'll receive the 3rd or 4th revision.
That's due to the sparsification of the backlog kicking in.

**Comment by jessehouwing** [comment]
How are you testing it's new?

**Comment by tomkuijsten** [comment]
Sorry, my bad. I checked for "To do" (as the column is named in the Task board). The state value however seems to be "To Do". I updated my [gist](https://gist.github.com/tomkuijsten/c090269308cc86968206#file-tfsaggregator-samples-xml).
