### ISSUE TITLE
Is there some way to understand if the field was changed?

### ISSUE THREAD

**Issue by Wylde44** [tfsaggregator/tfsaggregator#108]
Hi,
You mentioned about "LastRevision" property to access previous field values.
Can i check it out that some field was changed from this property or maybe there is another way to do it? It would be great to make this part a little bit more documented.

Thanks in advance!

**Comment by giuliov** [comment]
It all depends what you are looking for: change is relative.

Imagine this sequence:
 1. A user opens a work item, whose `Revision` property values `7`
 2. She edits the `Description` field and saves
 3. TFS save the changes to the database and increments `Revision` to `8`
 4. Aggregator is notified of the change

At this point `self.Revision` is `8` and `LastRevision.Index` is `7`. Throught `LastRevision` one can see that `self.LastRevision.Fields["Description"].Value` equals what is saved in the database, while `OriginalValue` is the value before user edit.

If the Rule changes any field, you have this:
 5. Aggregator run a rule that changes a field
 6. Aggregator notices the edit and save the workitem to the database
 7. TFS triggers Aggregator again (maybe on a different machine), this time `Revision` property is `9`

**Comment by Wylde44** [comment]
It helped me so much! Thanks!

**Comment by giuliov** [comment]
Reopen to update docs.

**Comment by Wylde44** [comment]
It will be great if you describe how to use History property as well.

**Comment by jessehouwing** [comment]
docs updated to include `PreviousRevision` and `NextRevision` on workitems.
