### ISSUE TITLE
Unable to get Aggregator to work, please advise

### ISSUE THREAD

**Issue by GSHerber** [tfsaggregator/tfsaggregator#109]
I am unable to get the plugin to work. The console app reports 'success' yet no rollup occurs. Debugview shows nothing from TFSAggregator even when running the console app. I am not a C# developer, that may be part of the problem.

Plugin installed from TFSAggregator-2.0.138-master-release.msi.
TFS is version TFS2013u4.
Attached wit definitions and policy file
[AggregatorIssue.zip](https://github.com/tfsaggregator/tfsaggregator/files/101068/AggregatorIssue.zip)

Best regards,

Gary Herber

**Comment by giuliov** [comment]
I see no issue in the policy file. The lack of messages on DebugView is tracked by issue #105, hopefully I have some hours in the next days to look at it.
Is the console app working, at least?

**Comment by GSHerber** [comment]
The console app reports ‘success’ and no errors or warnings. But I see no evidence that the plugin is triggering for WIT changes.


Best regards,
Gary Herber
Sr. Engineer, Software
General Dynamics Information Technology
2470 Oakdale Blvd.
Coralville, IA 52241
(o) 319-471-4612
(e)Gary.Herber@GDIT.Com<mailto:Gary.Herber@GDIT.Com>

**Comment by giuliov** [comment]
Just realized that the only the Debug build writes messages to debugger output, that is what DebugView captures.
To use build 138 you need to uninstall the Release MSI, install the Debug one. After troubleshooting is complete and the policy file reach final version, redo the unsintall/install to have the Release version.

I will close this issue as duplicating #105, review the documentation, and issue some source code fix to include in future releases.
