### ISSUE TITLE
Setup a CI build

### ISSUE THREAD

**Issue by giuliov** [tfsaggregator/tfsaggregator#11]
Setup a CI build on appveyor

**Comment by rbanks54** [comment]
Are we going to have issues with this, given we need TFS server side dlls? I have a feeling they're not redistributable. We'll have to check first.

**Comment by giuliov** [comment]
I use the trick to download them from a well-know encrypted source. If one wants to re-use the CI or build locally, must get the DLL by him/herself.

**Comment by giuliov** [comment]
We can close this issue, see <https://ci.appveyor.com/project/giuliov/tfsaggregator>
