### ISSUE TITLE
Allow option to "extract" the files to a specific folder instead of auto-installing

### ISSUE THREAD

**Issue by jessehouwing** [tfsaggregator/tfsaggregator#110]
Feedback from a colleague who ran the installer. He'd like:
- [ ] a warning that this will auto-install into the server.
- [ ] an option to extract the plugin for a specific TFS version or to have the different versions extracted under the commandline's installation directory instead of installing them directly.

**Comment by jessehouwing** [comment]
Assigning to @giuliov since this will require more wix magic :)

**Comment by giuliov** [comment]
A quick workaround is to use 7-zip to extract the required files or, better [LessMSI](http://lessmsi.activescott.com/).

I am reviewing the Wix code these nights and found a simpler solution _requiring a breaking change_ , that is to change MSI version numbers.
I was also thinking of an
 - [ ] option to select just client or server install
Your suggestion was more around an admin install, I'll see.

**Comment by giuliov** [comment]
Note to self: admin install won't work as current code has Level=0, but must be reversed as hinted [here](http://stackoverflow.com/questions/5411358/how-to-ensure-a-feature-is-installed-during-a-windows-installer-admininstall).

**Comment by jessehouwing** [comment]
I like that LessMSI option, though we may want to include a warning page in the installer to call that option out and provide guidance for it on the wiki.

**Comment by giuliov** [comment]
I reversed the Level usage and tested the administrative install (`/a`) but things are more complex than expected. It seems that the installed TFS version drives the extracted files. I need to consult other Wix developers to discuss the best approach.

**Comment by giuliov** [comment]
2.2 added option to the installer so you can pick what you need (#170).
