### ISSUE TITLE
TFS has become unavailable after replacing the policy file

### ISSUE THREAD

**Issue by Wylde44** [tfsaggregator/tfsaggregator#111]
Hi,
Yesterday i came across with the problem, I had prepared the new policy file and after replacement TFS became unavailable both from the web and from the visual studio.
The last event was "The application is being shutdown for the following reason: BinDirChangeOrDirectoryRename", and than any manipulations as reinstalling aggregator led to nothing. Only server reboot helped. It was the first time it went like this.
So, is there a place where i made mistake?
Maybe there's some unhandled exception during the get-new-file process.
Or it's just an accident.

TFS 15upd1
TFSAggregator 2.0.114

Thanks in advance.

**Comment by giuliov** [comment]
It is normal finding the BinDirChange event after modifying files in TFS
plugin folder: TFS monitors that directory to reload changed plugins and
writes that message when it happens.

I have no idea why it crashed so badly, as normally exceptions are caught
in Aggregator first and in TFS eventually. Maybe it run out of memory.

Giulio

**Comment by Wylde44** [comment]
Thanks, i will let you know if it happens again or some new circumstances appear.
