### ISSUE TITLE
TFS 2015 Update 2 RC breaks

### ISSUE THREAD

**Issue by jessehouwing** [tfsaggregator/tfsaggregator#113]
```

Detailed Message: Exception encountered processing notification: Method not found: 'System.Uri Microsoft.VisualStudio.Services.Location.Server.ILocationDataProvider.GetSelfReferenceUri(Microsoft.TeamFoundation.Framework.Server.IVssRequestContext, Microsoft.VisualStudio.Services.Location.AccessMapping)'. 
Stack Trace:   at Aggregator.Core.Facade.RequestContextWrapper.GetProjectCollectionUri()
   at Aggregator.Core.Context.RuntimeContext.GetWorkItemRepository() in C:\Users\jhouw\Source\Repos\TfsAggregator\tfsaggregator\Aggregator.Core\Context\RuntimeContext.cs:line 151
   at Aggregator.Core.EventProcessor..ctor(IRuntimeContext runtime) in C:\Users\jhouw\Source\Repos\TfsAggregator\tfsaggregator\Aggregator.Core\EventProcessor.cs:line 40
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in C:\Users\jhouw\Source\Repos\TfsAggregator\tfsaggregator\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 84
```

**Comment by jessehouwing** [comment]
Fix in the works.

**Comment by jessehouwing** [comment]
Initial commit:
https://github.com/tfsaggregator/tfsaggregator/tree/TFS2015u2

@giuliov this needs another Build Configuration and a zipfile with contents.and probably changes to the Wix installer as well.

**Comment by giuliov** [comment]
Sure, but bo earlier than next week, sorry it is a crazy moment now.

**Comment by jessehouwing** [comment]
It's still RC, so I don't think we're in a hurry.

DevDeiv decided to change the returntype of one method from Uri to String... *sigh*

**Comment by jessehouwing** [comment]
With the RC2 it's becoming more important to be able to integrate and test this. @giuliov any chance you'd be able to find a time to update the installer and build to handle Update 2 correctly?

**Comment by giuliov** [comment]
Most of the work has been done on _refactor-setup_ branch which includes the _TFS2015u2_ commits. I haven't had time to test it properly, though.

**Comment by jessehouwing** [comment]
Thanks man! I'll try to find a good moment this week to take it through a
couple of tests.

**Comment by jessehouwing** [comment]
As far as I can tell these are the assemblies we need from the server object model.
[2015-2.zip](https://github.com/tfsaggregator/tfsaggregator/files/171106/2015-2.zip)

**Comment by markhrosen** [comment]
Any idea when a version that supports TFS 2015 Update 2 will be available? We are building out a new environment and are looking to take advantage of the capabilities in tfs aggregator.

**Comment by jessehouwing** [comment]
Right after build is when I'm planning to make that happen.

**Comment by markhrosen** [comment]
I have been looking for a  date from Microsoft for when Update 2 will be released but have not found one. The only thing I did find is that "This release of TFS is a “go-live” release candidate. Microsoft will support customers choosing to install it in a production environment."

DO you know of a release date? Is there a way to get a pre-release of aggregator so we can test?

Thanks!

**Comment by jessehouwing** [comment]
The current dev branch will work with the update 2 rc. It has not yet been
merged to master. Click the build badge to download the latest installer.

We'll work on making a version available shortly after the release of TFS
2015 update 2 RTW.

**Comment by markhrosen** [comment]
First, thanks for your support. I really like this product and it will help increase adoption across the program here.

I clicked on the Build Badge and it took me to Appveyor. I see the log and the test cases but no artifacts. I created an Appveyor account and logged in.

Where should the installer be?

Thanks very much!

**Comment by jessehouwing** [comment]
@giuliov any idea what's wrong here? I don't see any artifacts either...

**Comment by giuliov** [comment]
Sorry my fault. I changed the yaml script to create the setup only for certain branches, namely master, release/* and hotfix/*. The idea is to have a quick CI build for dev branches and full work for releases. Names follow gitflow convention.

----- Messaggio originale -----
Da: "Jesse Houwing" <notifications@github.com>
Inviato: ‎29/‎03/‎2016 19:08
A: "tfsaggregator/tfsaggregator" <tfsaggregator@noreply.github.com>
Cc: "Giulio Vian" <giuliovdev@gmail.com>
Oggetto: Re: [tfsaggregator/tfsaggregator] TFS 2015 Update 2 RC breaks (#113)

@giuliov any idea what's wrong here? I don't see any artifacts either...

**Comment by jessehouwing** [comment]
And that isn't working, because the yml is not yet merged to main. Got it... I suppose the differences between main and develop are too big on the setup side for them work without merging dev to master, right?

**Comment by jessehouwing** [comment]
https://github.com/tfsaggregator/tfsaggregator/releases/tag/v2.1.0-rc1
