### ISSUE TITLE
Can't get Rule to trigger from TFS

### ISSUE THREAD

**Issue by tonkas64** [tfsaggregator/tfsaggregator#114]
I'm using 2.01 RTM on TFS 12.0.40629.0 (Tfs2013.Update5) running on Windows 2012R2
I installed using the MSI (but also manually copied some of the dll's to the TFS plugin bin folder when it didn't work).

I edited the TFSAggregator2.ServerPlugin.policies to fit my team project and collections.
I tested it through the console app (the paths in your wiki and PowerShell Install scripts needed a tweak to ..\samples)  and everything worked.
When I copy the policies file to the TFS plugins directory run the debugger (with capture global win32 enabled) and make the changes to a work item (a Task with a Title, Edit and create) the only messages I get in the debugger appear to be from IIS.
I was expecting to see the Hello World Log message
![image](https://cloud.githubusercontent.com/assets/17335474/13174795/fcc62de4-d6fd-11e5-9575-0e48d4ed4289.png)

**Comment by giuliov** [comment]
Chapeu for the precise report.
Please, take a look at issue #105. Let us know if it helps.

 In the next weeks I will have some time to refresh the docs and consolidate the fixes into a 2.x release.

**Comment by tonkas64** [comment]
Thanks for the pointer and apologies for not seeing that in the issues already, I think that was my misunderstand between, not running at all vs not logging to debug.

Installing the debug version as explained in #105 fixes the issue, I would consider this Issue to be a duplicate.
