### ISSUE TITLE
Does OriginalValue work?

### ISSUE THREAD

**Issue by tomkuijsten** [tfsaggregator/tfsaggregator#117]
I've removed the rateLimiting section from my policy and expected an event for every change. I added a trigger for the Task WIT and compare the ```self.Fields["System.State"].Value``` to ```self.Fields["System.State"].OriginalValue```. I move an item from Done to In Progress, but the event doesn't seem to fire. Am I doing something wrong or is the OriginalValue not working?

**Comment by jessehouwing** [comment]
`OriginalValue` contains the changes *tfsaggregator* makes, not the value of the previous revision. If you need to compare against the previous version you'll need to use `self.LastRevision.Fields["System.State"].Value`.

**Comment by jessehouwing** [comment]
You may want to test against `self.Revision > 1` as well to prevent a nullreference issue.

**Comment by giuliov** [comment]
Probably we should better clarify how the interaction between TFS and the plugin works in the [How it Works]( https://github.com/tfsaggregator/tfsaggregator/wiki/How-it-Works) page.

The `WorkItemChangedEvent` raises _after_ TFS has saved the work. Aggregator picks the id of the changed record and loads the WorkItem object from the database: at that stage the `Value` and `OriginalValue` are identical.

**Comment by tomkuijsten** [comment]
Ah! That explains a lot :). One more question. If I do enable rateLimiting and let's say my task was changed 5 times before my script is executed, what does ```self.LastRevision``` contain? Would that be the last revision since my script was executed, or the actual TFS last revision?

**Comment by jessehouwing** [comment]
It sounds like your understanding of rate limiting may be different than reality. 

Last revision always has the previous TFS revision, but that is likely also the last revision seen by the Aggregator. 

What happens 

```
Ratelimit 5
Revision 1
Revision 2 (last Revison has 1)
Revision 3 (last Revison has 2)
Revision 4 (last Revison has 3)
Revision 5 (last Revison has 4)
Revision 6 Aggregator stops. 
Wait a little 
Revision 7 (last revision has 6)
```

**Comment by tomkuijsten** [comment]
Hmm ok, I think I do understand the rateLimit now. It defines the timespan (or number of changes) it will immediately handle, after one of the two reach it's limit, it will do some kind sleep before before handling new incoming changes, is that correct?

**Comment by jessehouwing** [comment]
That's it.

**Comment by tomkuijsten** [comment]
But still I can't get it to work. I created a [gist](https://gist.github.com/tomkuijsten/cdf9f29db6e1523801a4) with my code (in the policy file). It looks like both originalState and currentState are always equal, am I still doing something wrong here? Sorry to bother you this much, but I really want this to work.

**Comment by giuliov** [comment]
Checked and found that `LastRevision` returns the top Revision in History which is... the current state.

@jessehouwing I am not certain which is the best approach:

1. consider this a bug and fix it so that `LastRevision` returns the Revision before current
2. add a second property, say `PreviousRevision`
3. expose the entire Revision collection and let the Rule author decide (which you didn't liked for some reason)

**Comment by jessehouwing** [comment]
I don't really see the value of LG getting the current revision (as it won't have that behavior once you actually get your hands on another older revision).

Lets treat this as a bug. Though I wonder how we get a consistent behavior so that last revision.lasttevision gives us the revision before and it won't start skipping revisions.

**Comment by tomkuijsten** [comment]
Thanks for the fix. Is a new release upcoming, or am I better off compiling it myself?

**Comment by giuliov** [comment]
I merged to PR to develop branch: you can grab the MSI from the Artifacts in AppVeyor [build 2.1.143-develop](https://ci.appveyor.com/project/giuliov/tfsaggregator/build/2.1.143-develop) and test if it works for you.

**Comment by giuliov** [comment]
Please do not close this issue until we update the wiki.

**Comment by jessehouwing** [comment]
@giuliov pulling in the changes and putting them to the test. Now that I've been trying the Lastrevision property a couple of times, I feel that "Previous" indeed is a better name for them. So I've restored last to the old behavior and added a Next/Previous property.

**Comment by jessehouwing** [comment]
@tomkuijsten does the latest Debug build work for your case?

**Comment by tomkuijsten** [comment]
I don't know yet. In the end I used reflection to get the private Revision list and pulled out the previous one, which worked for me. I don't have a proper test environment, so everything is done in production. It's working fine now. I'll deploy the next stable release of TFSAggregator and replace my reflection code with the property. Thanks for the fix!

**Comment by jessehouwing** [comment]
Documentation updated.
