### ISSUE TITLE
Save last processed revision in a field so we can catch up on missed revisions

### ISSUE THREAD

**Issue by jessehouwing** [tfsaggregator/tfsaggregator#124]
By storing the last processed revision in a field we can detect work items that weren't processed and we can detect changes to workitems that were never processed when we receive an event. That way there's more insurance that rules are processed.

I don't see any other way than either tracking state somewhere. A simple integer field on all work item types would be a relatively simple solution. We could detect the field is there and act on it, making the feature optional. This may be able to prevent issues like #123.

**Comment by tomkuijsten** [comment]
Would be nice to have a property for fetching the last processed revision. Makes comparing of fields easier.

**Comment by jessehouwing** [comment]
You could actually write a rule for that :).

**Comment by tomkuijsten** [comment]
Can I share code between rules?

**Comment by jessehouwing** [comment]
Not yet.

**Comment by giuliov** [comment]
@tomkuijsten make a proposal ;-)

**Comment by giuliov** [comment]
@jessehouwing using a field is one option. Alternatively you use a store to keep track of history, say an additional SQL database on the same SQL instance used by TFS (connection string can be easily looked up in TFS configuration).
Neither is pleasant IMHO .

**Comment by jessehouwing** [comment]
I'd want to make this completely optional and not enabled by default.
