### ISSUE TITLE
False warning

### ISSUE THREAD

**Issue by theliberator** [tfsaggregator/tfsaggregator#125]
Hello,

in our team project the work items 'Product Backlog Item' and 'Task' in our TeamProject both have a custom field. Both custom fields are linked to the same global list.

I've created a policy to copy the value of the custom field from the Product Backlog Item to the child Task item.

`foreach (var child in self.Children)
{
    if (child.TypeName == "Task") { child["CustomField1"] = self["CustomField1"];
}`

When I test the policy with the command line tool, the value is correctly copied to the child Task item, but in the console window following warning is prompted: 

[Warning]     00.787 Invalid value assigned to: 56/CustomField1, it is not in
the allowed list. Value: CustomValue1

Since both fields are linked to the same global list, this seems to be a false-positive.

**Comment by giuliov** [comment]
That is message _FieldValidationFailedValueNotAllowed_. I think you spot a bug in `InvalidValueFieldValueValidator` class: the test

                if (valid)
                {
                    this.Logger.FieldValidationFailedValueNotAllowed(
                        field.WorkItem.Id,
                        field.ReferenceName,
                        value);

                    return false;
                }

should be reversed. @jessehouwing ?

**Comment by jessehouwing** [comment]
Looks like you're on to something.

**Comment by giuliov** [comment]
Forgot to ask: @theliberator which version are you using?

**Comment by theliberator** [comment]
Version is 2.1.173.

**Comment by giuliov** [comment]
@theliberator I added the fix in build https://ci.appveyor.com/project/giuliov/tfsaggregator/build/2.1.174-release/2.1.0-rc1. Can you test it in your environment?

**Comment by theliberator** [comment]
I'm confused, I cannot find a download link on the site https://ci.appveyor.com/project/giuliov/tfsaggregator/build/2.1.174-release/2.1.0-rc1!? I've signed in with my GitHub credentials, still no download link!?

**Comment by jessehouwing** [comment]
You need to pick either debug or release. Under each you'll find an
artifacts tab which holds the download.

**Comment by theliberator** [comment]
Ok, I've tested my policy with the command line tool (2.1.174), the warnings are gone and the policy is correctly applied to the related work items.
However, when I change a work item in the web interface or VS to trigger the policy the policy is not applied by TFS!? Any hints?

**Comment by giuliov** [comment]
@theliberator, have you also updated the server plugin? It the policy is working from command line and the plugin is the bug-fixed version, then you can see in the [wiki](https://github.com/tfsaggregator/tfsaggregator/wiki/Troubleshooting) how to troubleshoot.
