### ISSUE TITLE
Share code between rules

### ISSUE THREAD

**Issue by giuliov** [tfsaggregator/tfsaggregator#126]
As mentioned in #124, it could be useful having a mechanism that permits code sharing between rules.

Each rule generates a method, so there two possible mechanism:

 1. _include_ - the code snippet is included at the top of each method
 2. _call_ - the code is embedded in a method callable from rules

Possible syntax
```
<snippet name="MySnippet"><![CDATA[
    logger.Log("You entered MySnippet snippet.");
]]></snippet>

<function><![CDATA[
  int MyFunc() { return 42; }
]]></function>

<rule name="MyFirstRule" appliesTo="Task" hasFields="Title"><![CDATA[
    ${MySnippet}
    logger.Log("Hello, World from {1} #{0}!", self.Id, self.TypeName);
    logger.Log("MyFunc returns {0}.", MyFunc());
]]></rule>
```

**Comment by tomkuijsten** [comment]
This would be awesome!

**Comment by giuliov** [comment]
Try PR #128, then.

**Comment by giuliov** [comment]
Merged in **develop** branch
