### ISSUE TITLE
Change History

### ISSUE THREAD

**Issue by DaveKLloyd** [tfsaggregator/tfsaggregator#127]
We would like to put a comment in the history of a work item when the aggregator makes it's change. I added this to the rule:
self.Parent["System.History"] = string.Format("TFS Aggregator Rule [AutoActiveTaskParent] : My child Task [ID:{0}] became Active so I was changed to Active",self["System.Id"]);

But it never happens. Can anyone see what I am doing wrong?

**Comment by jessehouwing** [comment]
History is a special kind of field and has it's own property on the work item:

```
self.History = "Hello";
```

See: https://github.com/tfsaggregator/tfsaggregator/wiki/Scripting-Pitfalls

**Comment by DaveKLloyd** [comment]
Thanks for pointing us to the solution

**Comment by jessehouwing** [comment]
We may add a debug helper to log the assignment through the fields collection.
