### ISSUE TITLE
self.PreviousRevision does not work for me

### ISSUE THREAD

**Issue by DaveKLloyd** [tfsaggregator/tfsaggregator#129]
I was looking for an example of PreviousRevision. Then I got reading some of the other issues and I'm not sure I if I am going down the right road or not. 

My customer wants a field on the bug that shows the number of time this bug has been Re-Activated. I wrote them a small app that uses the API to get that information for them. However I thought maybe I could use the Aggregator to continuously increment a read-only field on the Bug with this information. 

The rule would look something like this. 

` <rule name="ReOpenedBugs" appliesTo="Bug">  <![CDATA[
if (((string)self["System.State"] == "Active") && ((string)self.PreviousRevision["System.State"] !=  "Active" ))  
{
        self.Fields["NBFC.ReActivatedCount"].Value = (int)self.Fields["NBFC.ReActivatedCount"].Value + 1;
}
    ]]>
`

I am getting an error that says 
_Aggregator.Core.Interfaces.IWorkItemExposed' does not contain a definition for 'PreviousRevision' and no extension method 'PreviousRevision_

I have tried to use PreviousRevision several different ways with no luck. I have looked for an example in the wiki and in the unit tests. I can't find anything. Can someone point me at an example of how to use PreviousRevision.  LastRevision works fine for me and the wiki implies they would be used the same way. 

What am I missing?

**Comment by giuliov** [comment]
Wiki is hard to sync with releases. That change should be in 2.1-RC branch, not in master.

**Comment by giuliov** [comment]
Note to self: create a release branch on both the main and the wiki repos. When release merges to main, merge the same branches on wiki.

**Comment by DaveKLloyd** [comment]
Well that explains it. :) Thank you  for the quick response.
