### ISSUE TITLE
Gating a rule based on new parent link.

### ISSUE THREAD

**Issue by IronGem** [tfsaggregator/tfsaggregator#130]
I am trying to create a rule that will update a custom field with the contents of that same field from the parent work item.  I want this to happen only when the work item is linked to the parent.  I have been trying to use the Last Revision History as given in the history.policies file in the Samples folder, but the History field is always blank.  Is there a way to accomplish this?

Windows Server 2012 R2; TFS 2015 Update 1, TFSAggregator 2.1.173

Rule:
```
<rule name="PopulateUSWBSRule" appliesTo="User Story;Bug" hasFields="(CustomField)">
      <![CDATA[
        logger.Log("Processing {0} #{1}.", self.TypeName, self.Id);
        var lastRevision = self.LastRevision;
        var history = lastRevision.Fields["History"];
        string lastValue = (string) history.Value;
        bool recentParentLink = lastValue.Contains("Added (Parent)");
                     
        logger.Log("Recent Parent Link:  {0}", recentParentLink);
        
        if (recentParentLink && self.HasParent() && (string)self.Parent.TypeName == "Feature" && self["(CustomField)"] != self.Parent["(CustomField)"])
        {
          var parent = self.Parent;
          self["(CustomField)"] = parent["(CustomField)"];
        }
      ]]>
    </rule>
```

**Comment by giuliov** [comment]
Sorry for later reply.

History is not easy to manipulate, see #65, #117, #118 and [this wiki page](https://github.com/tfsaggregator/tfsaggregator/wiki/Scripting-Pitfalls).

I do not understand why you need to look at history to accomplish the result. I would use something like the following

```
```

**Comment by ProfX66** [comment]
I think he is trying to pull the parent field only on the first link of the work items.

Basically it only pulls the data once, instead of every time the work item is changed.

**Comment by IronGem** [comment]
@ProfX66, Yes that is the thought.  I only want to pull the data when the child is linked to the parent, not every time the child is updated.

**Comment by jessehouwing** [comment]
Checking the previous revision is just as expensive as querying the
parent... If that's the reason you want to check at link time only, then
you may as well ignore it.

We could provide more information on exactly what has changed, we get that
information as part of the INotification but we ignore it presently.

**Comment by jessehouwing** [comment]
Created a new item to track the listing of ChangedFields in #134
