### ISSUE TITLE
TFS 2015 - Update 2

### ISSUE THREAD

**Issue by GlennQuirynen** [tfsaggregator/tfsaggregator#132]
Hi,

on March 30, 2016, microsoft released tfs 2015 update 2.
[https://www.visualstudio.com/en-us/news/tfs2015-update2-vs.aspx]

What are the timelines in which tfsaggregator will support this update?
Is there something we can do ourselfs, to make it work?

Thanks,

**Comment by giuliov** [comment]
You can do us a favor by testing version 2.1 (PR #121) . If you need ready-to-use binaries look in https://ci.appveyor.com/project/giuliov/tfsaggregator.
One caveat, we have an open issue on supporting TFS upgrades: currently you must uninstall and reinstall Aggregator to get the proper version.

**Comment by jessehouwing** [comment]
I pulled the trigger and released the latest build.
