### ISSUE TITLE
FollowingLinks function is not working properly

### ISSUE THREAD

**Issue by djohnson7789** [tfsaggregator/tfsaggregator#133]
I've created some fields on test cases and requirements to roll up hours spent on test case design.  The rule targets a Test Case which should be linked to a Requirement (Tests link) then use that item to sum up all child remaining and actual. for that requirement and update the requirement QA hours fields.

Here is the code for my rule.  Am i doing something wrong?

**var req = self.FollowingLinks("Tests");
	foreach(var rtemp in req){
		logger.Log("req:{0}", rtemp.TypeName);
		var TCS = rtemp.FollowingLinks("Tested By");
		var req1 = rtemp;
		var remaining = TCS.Sum(TestCase => TestCase.GetField<double>
("Microsoft.VSTS.Scheduling.RemainingWork", 0d));
		var actual = TCS.Sum(TestCase => TestCase.GetField<double>
("Microsoft.VSTS.Scheduling.CompletedWork", 0d));
		req1["QAREMAINING"] = remaining;
		req1["QAACTUAL"] = actual;
	}**

I'm not so concerned that there could be a one to many relationship for tested By links.  In most cases, these will be 1 to 1.

Any help is greatly appreciated!

Regards,

-David Johnson

**Comment by djohnson7789** [comment]
Further testing reveals that if I don't use the link type, and instead build the fluent query like this:

var TCS = self.WhereTypeIs("Test Case");

Then the aggregation will complete successfully.  Any idea what I'm doing wrong with the link type argument?

**Comment by giuliov** [comment]
It amazes me what people is able to build on top of Aggregator :-) 
That said the test is always limited so it could be a bug; will confirm after further investigation. For sure I never dreamed of a nested invocation like yours.

That said `FollowingLinks` works only in one direction and matches Link type's reference name, so the correct invocation is `FollowingLinks("Microsoft.VSTS.Common.TestedBy")`.

How it works: the Fluent elements collect the query conditions; as the client code iterates, work items are lazily loaded into memory (see the `WorkItemLazyVisitor.GetEnumerator` workhorse method).

**Comment by jessehouwing** [comment]
Do we want to ship this fix as part of 2.1 or merge it into 2.2?

I'd like to wrap up 2.1.

**Comment by giuliov** [comment]
Which fix? I had no time event to investigate.

**Comment by jessehouwing** [comment]
The fix that may appear after investigation. Just wondered whether you
wanted to finish this before we draw the line.

**Comment by giuliov** [comment]
@djohnson7789 as far as I can tell, `FollowingLinks` works fine; I tested using following code.

```
var requirements = self.FollowingLinks("Microsoft.VSTS.Common.TestedBy-Reverse");
foreach(var req in requirements) {
  var testCases = req.FollowingLinks("Microsoft.VSTS.Common.TestedBy-Forward");
  double remaining = testCases.Sum(tc => tc.GetField("Microsoft.VSTS.Scheduling.RemainingWork", 0.0));
  req["Custom.RemainingWork"] = req.GetField("Microsoft.VSTS.Scheduling.RemainingWork", 0.0) + remaining;
}
```

Note the use of Link type reference name (`Microsoft.VSTS.Common.TestedBy-Reverse` instead of `Tests` and `Microsoft.VSTS.Common.TestedBy-Forward` for `Tested By`). Another trick is using `double` not decimal.

Let us know if this solves or you need additional help. If we do not hear we will close it and wrap up for releasing 2.1

@jessehouwing I pushed in 2fa32bc a unit test for this case.

**Comment by jessehouwing** [comment]
Then it looks like we can merge to master and proceed
