### ISSUE TITLE
Adding support for sending mail

### ISSUE THREAD

**Issue by giuliov** [tfsaggregator/tfsaggregator#135]
Consider adding some helper to simplify composing and sending email. 
Pick ideas from [Email Alert for TFS](https://tfsemailalert.codeplex.com/)
Consider that TFS already tracks users' email address (sample code http://stackoverflow.com/questions/19594071/getting-tfs-identity-users-mailaddress-for-c-sharp-vs2012-and-vs2013) and may have an SMTP server configured.

**Comment by jessehouwing** [comment]
Could even make use of the standard mail task in TFS to deliver the email asynchronously.

Just wonder whether this should be an aggregation rule or a derivatie plugin altogether.

**Comment by giuliov** [comment]
Did not know that the send-mail feature is exposed as API. Any reference?

**Comment by giuliov** [comment]
Got it [TeamFoundationMailService](https://msdn.microsoft.com/en-us/library/microsoft.teamfoundation.framework.server.teamfoundationmailservice.aspx)

**Comment by giuliov** [comment]
I built a working prototype and two things emerged.

`IVssRequestContext`/`TeamFoundationRequestContext` must be visible down to the script engine. I think to avoid coupling by having a 'library' class that receives the context and wraps TFS Server API calls for scripts that may require them. Sample script code:
```
string from = "aggregator@example.com";
string to = "test@example.com";
string subject = "TFS Aggregator";
string body = "It worked!";
Lib.SendMail(from, to, subject, body);
```

I am more concerned regarding the webhooks scenario #138.
It rules out TFS server specific code as the mentioned 'library' class. This means that we must have two implementations, one dependent on TFS Server API and one stand-alone. This latter requires additional configuration data that the former gets for free.

**Comment by jessehouwing** [comment]
I wonder whether we should provide a spam provider as a cloud service at
all... I'm fine with on premise only support for now and a warning/error.
Especially if we allow the specification of to and from.

Doing email alerts on behalf of others correct try is a minefield.
