### ISSUE TITLE
Update Visual Studio Gallery

### ISSUE THREAD

**Issue by jessehouwing** [tfsaggregator/tfsaggregator#136]
@giuliov since you own the VS Gallery item, can you push the 2.1 install to the gallery?

**Comment by jessehouwing** [comment]
PS: tested against the upcoming 2015.2.1 release and no changes seem to be required.

**Comment by giuliov** [comment]
Also update the Wiki with new features and tips from issues.

**Comment by giuliov** [comment]
Completed, note the suggestions in [Branches](https://github.com/tfsaggregator/tfsaggregator/wiki/Developer-Intro#branches) and [Wiki](https://github.com/tfsaggregator/tfsaggregator/wiki/Developer-Intro#wiki).
