### ISSUE TITLE
Roll-up for an entire tree

### ISSUE THREAD

**Issue by IronGem** [tfsaggregator/tfsaggregator#137]
We have a structure in TFS that can be 4-5 levels deep, kind of like this WIT1 -> WIT2 -> WIT3 -> UserStory -> Task (sometimes WIT2 or WIT3 is skipped).  WIT1 has Estimated, Remaining, and Completed hours for an entire project, which we currently have to enter manually.  Is there a way I can write a Roll-up query that would allow me to:
1) trigger off of a Task, 
2) find the WIT1 that is the 'great-grandparent' or 'great-great-grandparent' of that task,
3) search for all Tasks under that WIT1, up to 4 or 5 generations deep
4) add up all Estimated, Remaining, and Completed hours on those Tasks
5) write the totals in the WIT1 fields.

I know I can write a Linq query on the .Children collection, but can I make is scan multiple generations?  Also is there a way to scan multiple generations of ancestors for one with a specific WIT name without a large, nested If statement?

**Comment by giuliov** [comment]
Take a look at the [Fluent Query](https://github.com/tfsaggregator/tfsaggregator/wiki/self-Object#fluent-queries) helpers: they were designed exactly for tree traversal. Do not forget to test your rules using the [console tester app](https://github.com/tfsaggregator/tfsaggregator/wiki/Console-App) for fast prototyping.

**Comment by IronGem** [comment]
Thank you for the quick response.  I have looked at your suggestions and from my understanding of the Fluent Query syntax, this is the code I have come up with:

```
<rule name="EffortRollupRule" appliesTo="Task" hasFields="Microsoft.VSTS.Scheduling.OriginalEstimate;Microsoft.VSTS.Scheduling.RemainingWork;Microsoft.VSTS.Scheduling.CompletedWork">
	<![CDATA[
		IWorkItemExposed WIT1 = null;
		
		WIT1 = self.FollowingLinks("Parent").WhereTypeIs("WIT1").AtMost(5).FirstOrDefault();
		
		if (WIT1 != null)
		{
			var tasks = WIT1.FollowingLinks("Child").WhereTypeIs("Task").AtMost(5);
			
			WIT1["Microsoft.VSTS.Scheduling.OriginalEstimate"] = tasks.Sum(task => task.GetField("Microsoft.VSTS.Scheduling.OriginalEstimate", 0));
			WIT1["Microsoft.VSTS.Scheduling.RemainingWork"] = tasks.Sum(task => task.GetField("Microsoft.VSTS.Scheduling.RemainingWork", 0));
			WIT1["Microsoft.VSTS.Scheduling.CompletedWork"] = tasks.Sum(task => task.GetField("Microsoft.VSTS.Scheduling.CompletedWork", 0));
		}
	]]>
</rule>

```
WIT1 keeps coming up null, though.  Have I formatted the methods incorrectly?

**Comment by giuliov** [comment]
You fallen in a typical error: use `System.LinkTypes.Hierarchy-Reverse` instead of `Parent` and `System.LinkTypes.Hierarchy-Forward` for `Child`.

**Comment by IronGem** [comment]
Thank you so much, that worked!!!  I also had to add <double> to the .GetField method or Sum didnt work properly.  The lines now look like this
```
WIT1["Microsoft.VSTS.Scheduling.OriginalEstimate"] = tasks.Sum(task => task.GetField<double>("Microsoft.VSTS.Scheduling.OriginalEstimate", 0));
```

Thank you for guiding me through the documentation.  I didn't realize quite how the Fluent Query methods worked.

**Comment by jessehouwing** [comment]
We should update FollowingLinks to work on the Simpel name as well.

**Comment by jessehouwing** [comment]
We should be able to re-use the code from the AddWorkItemLink to make the experience consistent between all pieces handling work item link code:

https://github.com/tfsaggregator/tfsaggregator/blob/master/Aggregator.Core/Facade/WorkItemWrapper.cs#L230

**Comment by jessehouwing** [comment]
I'll roll this into the work to support deleting links #131.

**Comment by giuliov** [comment]
It can be done but use of immutable name is more widespread and need some refactoring as I struggled to keep link code independent of TFS.

**Comment by jessehouwing** [comment]
It's the 3rd or 4th issue which lead to the use of simple names. Plus I personally find the simple names much easier to read. We could pre-populate the link types on load and save them in the context (or populate on first access). And use a similar structure for linktypes as the built-in one using System Name and Simple name. In query context we would only use one direction anyway. Right now it's not consistent across our codebase with the addition of simpel name support for AddWorkitemLink.

**Comment by giuliov** [comment]
My idea is to extend this interface and refactor code to always use it.
```
public interface IWorkItemLinkCollection : IEnumerable<IWorkItemLink>
{
    bool Contains(IWorkItemLink link);
    IWorkItemLink Contains(string linkTypeName);
    void Add(IWorkItemLink link);
    void Remove(IWorkItemLink link);
}
```

**Comment by jessehouwing** [comment]
My plan exactly.

**Comment by jessehouwing** [comment]
Keep the old methods in place, but have them write a deprecated warning for now? It should be easy tor redirect their current access points...
