### ISSUE TITLE
Support different linktypes check.

### ISSUE THREAD

**Issue by ASolovyev** [tfsaggregator/tfsaggregator#141]
As i saw in docs, now we can check only Parent and Child workitems from self.

It will be great if standart linktypes will be allowed as parent and child. e.g. related, referenced..

**Comment by jessehouwing** [comment]
What makes you think other links types are unsupported?

**Comment by jessehouwing** [comment]
You can use the `HasRelation` method on workitem.

**Comment by ASolovyev** [comment]
oh...really. sorry for disturbing.

**Comment by giuliov** [comment]
@ASolovyev note that there are some bugs and you should use Link types' Reference name to make things work (see #137 for some discussion).
I am working on fixing, but is coming out to be more work than expected: no ETA.
