### ISSUE TITLE
How to get changeset number?

### ISSUE THREAD

**Issue by Wylde44** [tfsaggregator/tfsaggregator#142]
Hi, guys!
I have one more question to you.
Is it possible to get the chageset number associated with the work item?
Thanks!

**Comment by giuliov** [comment]
No, sorry.
This piece of information is available in the links collection but we miss to expose it.
or you can submit a PR for this feature.

**Comment by Wylde44** [comment]
I'm afraid that my developer skills are quiet low to perform this. Sorry...

**Comment by gmbrooker** [comment]
Once this is introduced as part of a future release, will I then be able to associate Changesets of a child item to its parent?

**Comment by giuliov** [comment]
Yes @gmbrooker , but there is too much work in the pipeline: we need additional contributors.

**Comment by ExSF** [comment]
Will this change also include information about all the development links? (Build, commits, branch, Changeset, pull request, etc...)
