### ISSUE TITLE
Exceeding Concurrent Connection Limit

### ISSUE THREAD

**Issue by derekhuether** [tfsaggregator/tfsaggregator#143]
We had to back-out the install of the TFS Aggregator.  We had the older version running on TFS 2013 and the new one now running on TFS 2015.  The add-on was causing the TFS App Server(s) to exceed the concurrent connection limit to TFS SQL, thus causing the App servers to become unresponsive.  Our TFS Admins believe this is likely due to large number work items in our collection.

Our TFS Admins won't re-introduce the TFS Aggregator, unless they can open a case and troubleshoot.
Anyone else have this issue and have a resolution?

**Comment by jessehouwing** [comment]
Can you share the rules you have configured (possibly privately)? There can
be a number of reasons but I haven't encountered the issue you've been
experiencing. Some event log messages that catch the exception logs would
be helpful too.

**Comment by jessehouwing** [comment]
Another interesting bit of information would be whether you have impersonation turned on.

And when your SQL Server starts dropping connections what the result of the following procedure returns, it may help us understand what's keeping all the connections busy.

```
USE [Tfs_Configuration]
GO
DECLARE	@return_value int
EXEC	@return_value = [dbo].[prc_QueryWhatsRunning]
SELECT	'Return Value' = @return_value
GO
```
