### ISSUE TITLE
Create tfsaggregator as a VSTS Marketplace extension

### ISSUE THREAD

**Issue by Bebo2345** [tfsaggregator/tfsaggregator#145]
What about creating tfsaggregator as a VSTS Marketplace extension?

I'm sure this has been thought of already. I'll go ahead and get the converstion started here. :-)

I wonder if the extension api is sufficient to do what is currently being done in tfsaggregator or some subset can be done. Having it as an extension should ease installation.

**Comment by jessehouwing** [comment]
Currently not possible. We're looking at making it a service hook.

**Comment by giuliov** [comment]
The current incarnation is a server plug-in that must be installed on the TFS Application Tier on-premise. Implementing #138 this tight coupling is loosened and you can run tfsaggregator on a different machine. At that point an extension can offer a nice UI to configure it.

Usually an extension is simply a piece of Javascript running in the browser and the REST API are limited in many areas compared to the ClientOM.

**Comment by Bebo2345** [comment]
Ah... Good to know. Thank you for the response!

**Comment by ChristianJung2** [comment]
I really would appreciate a Marketplace extension :-)

**Comment by giuliov** [comment]
@ChristianJung2 just to clarify: it not possible to fully implement TFS Aggregator as a VSTS Extension (as long as an Extension is just client-side Javascript code, see [Overview of extensions for VSTS](https://www.visualstudio.com/docs/integrate/extensions/overview)): Aggregator will always be an external service, the extension will just make easy configuring how to call Aggregator.

**Comment by ChristianJung2** [comment]
@giuliov I see. The actual functionality I am interested in is automated creation of tasks when new PBIs have been created. Do you know another way to achieve this?

**Comment by giuliov** [comment]
@ChristianJung2 it is quite possible with TFS Aggregator: use the [MakeNewWorkItem](https://github.com/tfsaggregator/tfsaggregator/wiki/store-Object#makenewworkitem-methods) method.

**Comment by ChristianJung2** [comment]
@giuliov I know. But not with VSTS. Or am I wrong?

**Comment by giuliov** [comment]
Almost: version 2.1 does not support VSTS, but 2.2 will, at least in minimalist form.

Supporting VSTS implies implementing #138 which is well underway. The code in [feature/webhooks](https://github.com/tfsaggregator/tfsaggregator/tree/feature/webhooks) branch is already working both for VSTS and TFS.
If you want to be an alpha tester, you'll be very very welcomed.

**Comment by ChristianJung2** [comment]
I'd be more than glad if I could help out finishing this. I'll send you a mail.

**Comment by philbritton** [comment]
Looks like the new marketplace supports hosted solutions in addition to on premise solutions.  Here's an example, not a great one because of the review, but it is possible to get some more exposure. https://marketplace.visualstudio.com/items?itemName=urbanturtle.urbanturtle

![image](https://cloud.githubusercontent.com/assets/487081/18477910/54b0d882-799d-11e6-86fd-bdf78d880efd.png)

**Comment by giuliov** [comment]
Web Hooks support is in Web Service 2.3 beta at https://github.com/tfsaggregator/tfsaggregator-webhooks
