### ISSUE TITLE
TFS 2015 Update 3 support

### ISSUE THREAD

**Issue by jessehouwing** [tfsaggregator/tfsaggregator#149]
This is just to track compatibility. Currently running Update 3 on one development system without issues.

**Comment by japj** [comment]
Does this mean that Update 3 is "officially" supported on the current release of tfsaggregator?
Or is there an updated release coming soon (now that Update 3 is officially released)

**Comment by jessehouwing** [comment]
As far as I can tell there's no need for a new release. All tests are passing on my machine. But I have to admit that I'm using on-prem TFS less and less

**Comment by jessehouwing** [comment]
@giuliov looks like the installer works as well though we can now make it locked to the correct build number for Update 3 (`14.102.25423.0`). 

Updating the docs to reflect compatibility.
