### ISSUE TITLE
release zipfile missing, cannot perform manual installation

### ISSUE THREAD

**Issue by japj** [tfsaggregator/tfsaggregator#150]
It seems the binary release is only in the form of an MSI and the MSI can only be installed on a TFS server machine.

Previous (Betas) also included zipfiles that could be manually extracted (for manual install), this was also a way to get the console app binary for testing purposes.

**Comment by giuliov** [comment]
See the discussion on #110. I spent some time trying to make Admin install work the way I want (e.g. [this SO question](http://stackoverflow.com/questions/37396236/how-to-extract-files-for-a-specific-conditioned-feature-during-administrative)) but probably I will implement some simple hack like an additional build artifact.

**Comment by giuliov** [comment]
2.2 added option to the installer so you can pick what you need. @japj please open another issue in case this won't satisfy

**Comment by japj** [comment]
@giuliov that solution solves it for me, thanks very much!
