### ISSUE TITLE
Any one else having performance (speed) issues?

### ISSUE THREAD

**Issue by WolfVR** [tfsaggregator/tfsaggregator#153]
I'm working with a TFS system that has users bulk updating 100's to 1000's of work items at a time.  Our install is currently running on only one App Tier, and so the single instance of Aggregator can start running up a time lag of up to 6 hours or more between user change and Aggregator processing.

Is anyone else seeing this behavior, or have any tips to help make it more performant?

**Comment by jessehouwing** [comment]
do you know where the bottleneck is coming from? It'll be hard to tell but 6 hours sounds like a real issue where the SQL server and the AT are on the same machine fighting over the CPU. I haven't seen these kinds of numbers on my environments, but then again those generally have multiple AT's and pretty beefy SQL Servers. What's the CPU/Memory on the AT like? What's the CPU/Memory on the SQL server like? Is SharePoint and/or Report server configured on the same system?

What is the Auth model you have configured? If you've turned on Impersonation, that may be adding extra pressure. And if your changes cascade over the hierarchy, then your rules may be optimizable. Can you share the ruleset so we can inspect it for possible optimizations?

We're working on additional improvements to be able to skip rule processing completely depending on the fields that were changed.

**Comment by WolfVR** [comment]
Unfortunately, our usage base has expanded faster than our infrastructure, so everything is running on one server.  Plans are in the works to remedy this, and in the short term the server has been beefed up a bit, which has seemed to help.

We're not using Impersonation, and some of our rule sets do cause cascading changes, but we've done our best to optimize them, and to have early break out conditions in order to stop once we know no changes are necessary.

The bottle neck seems to be moving between work items that need to be checked.  While watching the trace output the actual processing of a work item is just a few milliseconds, but the time gap between work items is usually a second or two.  I've seen it get as bad as 30 seconds, but that was before the server had been beefed up.  We're guessing it's probably just I/O time with getting the info from SQL.

Mainly I was curious if others had seen similar behavior when under a large backlog, or, as I feared, if it's mainly our system not being set up correctly to handle the new user demands.

**Comment by jessehouwing** [comment]
That makes sense. We have an option to retrieve tree queries in one go, which will be much, much faster than retrieving work items individually... I'd love to walk through the ruleset to check where we could optimize further or provide guidance to other rule authors.

If you want to share it privately, email them to jhouwing@xpirit.com

**Comment by jessehouwing** [comment]
Are you using the FluentQuery API to fetch multiple work items at once? Or each individually?

https://github.com/tfsaggregator/tfsaggregator/blob/master/Aggregator.Core/Navigation/FluentQuery.cs

**Comment by WolfVR** [comment]
Once we determine that a work items children need updating we do use the FluentQuery API.

I think that this issue can be closed as it does seem that problem is with our TFS hardware and configuration.  Once our planned upgrades take place, if we are still having performance issues I'll open a new one.
