### ISSUE TITLE
TFS Aggregator not working as expected

### ISSUE THREAD

**Issue by ShreeSam** [tfsaggregator/tfsaggregator#154]
Hi Team,

Have installed Aggregator plug-in and edit "TFSAggregator2.ServerPlugin.policies". Am able to test it via command. 
TFSAggregator2.ConsoleApp.exe run --policyFile=samples\TFSAggregator2.ServerPlugin.policies --teamProjectCollectionUrl=http://localhost:8080/tfs/DefaultCollection --teamProjectName=TfsAggregatorTest1 --workItemId=42 --logLevel=diagnostic

This works fine. But when i update work-items from visual studio plug-in is not getting triggered. Work-items are not updating.
Please find the below details.
TFS 2015.3
Tfs Aggregator plug-in 2015.3

Please help me with this. 

Thanks,
Shree

**Comment by jessehouwing** [comment]
Please check: https://github.com/tfsaggregator/tfsaggregator/wiki/Troubleshooting

**Comment by ShreeSam** [comment]
Hi,

Thank you.
It worked after adding service account to TFS Collection Administrators group.

Thanks,
Shree
