### ISSUE TITLE
namespace name 'Server' does not exist in the namespace 'Microsoft.TeamFoundation.Framework' 

### ISSUE THREAD

**Issue by datasmithtech** [tfsaggregator/tfsaggregator#156]
The type NotificationType is not defined since the namespace is not resolved

I updated the nuget packages , even to pre-release level

Severity    Code    Description Project File    Line    Suppression State
Error   CS0234  The type or namespace name 'Server' does not exist in the namespace 'Microsoft.TeamFoundation.Framework' (are you missing an assembly reference?)   Aggregator.Core B:\dev-tfs2015\tfsaggregator-master\Aggregator.Core\Facade\NotificationWrapper.cs   3   Active

**Comment by giuliov** [comment]
To rebuild TFS Aggregator follow the instructions in [Local Build](https://github.com/tfsaggregator/tfsaggregator/wiki/Local-Build) wiki page.
Note that you must manually copy some assemblies from a TFS installation to succeed: licensing do not allow redistribution so there is no NuGet package for those, at lest today.

**Comment by jessehouwing** [comment]
Or install the required TFS version on your workstation. Install is enough,
it doesn't have to be configured or to be running.

**Comment by giuliov** [comment]
I faced a similar issue on VSTS Build and ended up in adding more packages.config files and instructing NuGet to scan them all.
Take a look at 2.2 code.
