### ISSUE TITLE
TFSAggregator2.ConsoleApp opens and closes immediately

### ISSUE THREAD

**Issue by jimmy8dmt** [tfsaggregator/tfsaggregator#157]
Hi, I'm using TFS 2015 R2 with Windows Server 2012 R2, so I installed TFSAggregator-2.1.178-Release.msi.  I'm new to using this tool, so I followed the 'Using the console to test Policies' instructions to start testing.

Once I open the console from the server it just closes =(.  Any suggestions?

Thank you

**Comment by giuliov** [comment]
It could be that you have not chosen the right flavor during setup.
You can easily check for this:

![a 2016-07-23_080800](https://cloud.githubusercontent.com/assets/1869724/17076221/6fa97086-50ad-11e6-9cff-df4e938e1c80.png)
![b 2016-07-23_080817](https://cloud.githubusercontent.com/assets/1869724/17076219/6fa7fa62-50ad-11e6-9718-83f9b68dc5f5.png)
![c 2016-07-23_080837](https://cloud.githubusercontent.com/assets/1869724/17076220/6fa8d554-50ad-11e6-9d8c-5b57befade3a.png)

**Comment by jimmy8dmt** [comment]
Thanks Giuliov.  I have 2015.2 installed, however it is version Version 14.95.25229.0 (or v2015.2.1) .

![2016-07-25_8-04-59](https://cloud.githubusercontent.com/assets/20604676/17106024/870aad7a-523e-11e6-9878-313ab18d5349.png)

**Comment by giuliov** [comment]
That works fine: there were no breaking changes after Update 2.

The bug is in the setup: on Update 3 it installs the RTM version.

![2016-07-25_204059](https://cloud.githubusercontent.com/assets/1869724/17112927/74956102-52a8-11e6-8421-8d17412a329d.png)

You can confirm by running the console with no arguments.

I need time to produce a fix because the installer logs shows correct value for the version. It can be something in the build process that generates the MSI.

The quickest fix for you is to pull down the code and recompile it.

**Comment by jimmy8dmt** [comment]
Can you point me to the steps to complete what you suggested?

Thanks,
Jim

**Comment by giuliov** [comment]
Sorry for late answering.
Look at the **Building and modifying** chapter in the wiki, in particular the [Local build](https://github.com/tfsaggregator/tfsaggregator/wiki/Local-Build) page.

In case of issues, do no hesitate to chime in here.

**Comment by giuliov** [comment]
@jimmy8dmt just found a small mistake in the `#if` and it happens that you see **2015.0** even for the **2015.2** flavor. In other word this message
![2016-07-25_204059](https://cloud.githubusercontent.com/assets/1869724/17112927/74956102-52a8-11e6-8421-8d17412a329d.png)
is a red-herring.

We still need to understand why the client does not starts on your environment.

**Comment by jessehouwing** [comment]
Plus, for the client the tfs version should not matter as it is not
dependent on the server object model.

**Comment by jimmy8dmt** [comment]
Hi - I uninstalled the previous version, restarted the server, then installed the latest version (2.1.1).  I am still unable to get the console app to run.  =(

**Comment by jimmy8dmt** [comment]
![2016-08-10_13-49-10](https://cloud.githubusercontent.com/assets/20604676/17570451/49de8294-5f01-11e6-80e3-f0cd501e8b84.png)

**Comment by jimmy8dmt** [comment]
that pic is from the error messages I received after pulling the source and rebuilding.

**Comment by giuliov** [comment]
Select the **Debug-2015.2** (or **Release-2015.2**) build Configuration: we have conditional compile depending on target TFS version as they break the API compatibility more than once, so you must choose the Configuration matching what the TFS you have installed (unless you pick the wrong Reference DLLs).

**Comment by jimmy8dmt** [comment]
Ok that seemed to build successfully, but not sure what to try next.  I installed wix and x.unit, then rebuilt the solution.  After that I tried running the console app via the object folder and got this error:
![2016-08-10_16-41-25](https://cloud.githubusercontent.com/assets/20604676/17574858/699247a2-5f19-11e6-9299-12189efa1094.png)

**Comment by jimmy8dmt** [comment]
Should I try moving this entire directory to program files?  There was a folder there back when I ran the first msi, but no longer exists since the uninstall.

**Comment by jimmy8dmt** [comment]
Ok, got to this step to create the MSI, but one last error:
msbuild build-installer.proj /p:Configuration=Release /p:BuildSolution=False /p:CollectFiles=False /p:BuildMSI=True

![2016-08-10_17-17-10](https://cloud.githubusercontent.com/assets/20604676/17575474/56e99100-5f1e-11e6-9510-9a5a0b7c9e33.png)

**Comment by giuliov** [comment]
You do not need the MSI to run the Console app: you can simply build it from Visual Studio and run from the command line, wherever you located the project.
You see _Could not load file_ error because you run from `obj`, but you must use the `bin` folder.

I need to investigate the error in building the MSI as it does not happens in CI.

**Comment by jimmy8dmt** [comment]
Do you see anything wrong with this command?  I ran this in MSBuild Command Prompt VS2015.
TFSAggregator2.ConsoleApp.exe run --policyFile=samples\TFSAggregator2.ServerPlugin.policies --teamProjectCollectionUrl=http://tfssndbxirvv:8080/tfs/iHerb Projects Collection--teamProjectName=iHerbDev--workItemId=21188 --logLevel=diagnostic

![2016-08-11_8-10-45](https://cloud.githubusercontent.com/assets/20604676/17593560/23fa3d9e-5f9b-11e6-8812-ec71f5468643.png)

**Comment by giuliov** [comment]
Try a full path for the policy file

**Comment by jimmy8dmt** [comment]
Ok, that seemed to help, but still struggling with my project collection, name, or ID.
![2016-08-11_8-21-46](https://cloud.githubusercontent.com/assets/20604676/17594071/ce92cd38-5f9c-11e6-9f26-bcf56981fdf7.png)

Thanks for your help giuliov.  I can't wait to get this working so I can start using the tool.

**Comment by giuliov** [comment]
Separate options using blank space (&emsp;), use full URL (e.g. `http://yourtfs:8080/tfs/yourcollection/`)

**Comment by jimmy8dmt** [comment]
woohoo..hello world from product backlog item #21188

**Comment by jimmy8dmt** [comment]
Sorry for the continued questions, but how do I make this work?  Trying to sum child task original estimate fields to roll up to parent PBI.  I used this example:

  <rule name="RollupTask" appliesTo="Task">
    <![CDATA[
if (self.HasParent())
{
    var parent = self.Parent;
    parent["Microsoft.VSTS.Scheduling.CompletedWork"] = parent.Children.Sum(task => task.GetField<double>("Microsoft.VSTS.Scheduling.CompletedWork", 0d));
    parent["Microsoft.VSTS.Scheduling.RemainingWork"] = parent.Children.Sum(task => task.GetField<double>("Microsoft.VSTS.Scheduling.RemainingWork", 0d));
    parent["Microsoft.VSTS.Scheduling.OriginalEstimate"] = parent.Children.Sum(task => task.GetField<double>("Microsoft.VSTS.Scheduling.OriginalEstimate", 0d));
}
]]>
  </rule>
    
Got this warning:
![2016-08-11_12-57-58](https://cloud.githubusercontent.com/assets/20604676/17602838/486c0a9a-5fc3-11e6-9462-7bf226d90c8a.png)

Trying to roll up the hours:
![2016-08-11_12-59-01](https://cloud.githubusercontent.com/assets/20604676/17602884/7a3311e0-5fc3-11e6-8748-e88f12f93fca.png)

**Comment by giuliov** [comment]
There a few basic sanity check that the policy is correct; that warning means that you defined a _RollupTask_ rule but it is not used. In other word the `policy` element contains no `<ruleRef name="RollupTask" />` to trigger the rule.
It may seems overkill, but in enterprises you need to filter which projects has which rules.

**Comment by jimmy8dmt** [comment]
Ok, that makes sense.  I updated the refname, and the policy seemed to execute successfully, however I'm not seeing the results in TFS.  I created an Original Estimate field referencing the same fields at the task level, but the hours dont seem to be rolling up.

![2016-08-11_14-04-14](https://cloud.githubusercontent.com/assets/20604676/17604885/91284a10-5fcc-11e6-89ca-8a7130207f47.png)

**Comment by giuliov** [comment]
You rule will be interpreted this way: when a Product Backlog Item changes, updates the parent Feature by summing the Scheduling fields.
The standard PBI and Feature work item types in the Scrum Process Template do **not** have those fields, so I assume that you added them to the project using `witadmin importwitd` or similar tool.

**Comment by jimmy8dmt** [comment]
Yes, using power tools 2015 I added a new field to the PBI called Original Estimate, and formatted it exactly like the task Original Estimate field.  They both use: Microsoft.VSTS.Scheduling.OriginalEstimate.  This original rule applied to: task, but I had to change it because every time I ran this policy via msbuild cmd it would return a does not match PBI error.

**Comment by jimmy8dmt** [comment]
Hi again,

Any idea what this is about?
![2016-08-15_14-57-15](https://cloud.githubusercontent.com/assets/20604676/17681130/a7fa482c-62f8-11e6-97f5-0c88a8eb77e7.png)

Thank you!

**Comment by giuliov** [comment]
I guess the rule is trying to read some non-existing object, e.g. a property with null value, but it is impossible to be more specific without reading rule's code.

**Comment by jimmy8dmt** [comment]
Ok =(.  I have two versions of aggregator installed.  One via source, so I can run the console.app, the other via regular install (msi).  So when the console runs, it is using the source installation.  When the policy is called, it exists via the regular installation.  I'll paste the rules code when I get to my desk.  Any chance I can borrow some of your time via chat today to get this working?

**Comment by giuliov** [comment]
I will close this old thread. @jimmy8dmt, you can submit a new issue in case of additional needs. I am retiring Gitter support as I cannot stand yet another chat app.
