### ISSUE TITLE
logger log and verbose output.

### ISSUE THREAD

**Issue by ASolovyev** [tfsaggregator/tfsaggregator#158]
Hi everybody.
I've updated aggregator to the 2.1.0.
and all information about it's working instead of warnings and errors is not displaying.
logging level is "Verbose" now.

and code like
 `logger.Log(LogLevel.Information, @"autogenerated create test");`
and 
`logger.Log("Now creating autogenerated with name AUTOGENERATED!"]);`

Also i've noticed that all service messages like "Applying rule rulename on..." is gone too.

**Comment by giuliov** [comment]
I remember fixing some log related bugs post 2.0, but they should be present in 2.1.

Can you help me with some specific example?

**Comment by ASolovyev** [comment]
Sure! What information instead my policies file do you need?

**Comment by ASolovyev** [comment]
here is my policies file

**Comment by giuliov** [comment]
Take a look at #105: behavior changed from v2.0 to v2.1.

Logging is now managed this way: every message goes to
- Debug output (visible using DebugView)
- Application EventLog (TFS Aggregator source) when Warning or Critical level
- Trace listeners

User messages (`logger.Log` calls in Rules) get a different prefix in Debug output and use a different Trace source.

**Comment by ASolovyev** [comment]
Ok. Thank you! I will use Loglevel.Warning in logger.Log() messages!
