### ISSUE TITLE
Generating new tasks. Assigned To issue.

### ISSUE THREAD

**Issue by ASolovyev** [tfsaggregator/tfsaggregator#159]
Hi! I have a very strange issue.

I am generating workitems with this code:
'var newWI = store.MakeNewWorkItem((string)self["System.TeamProject"], "Task");
newWI["System.AssignedTo"] = (string)self["Custom.ChangedDailyWork"];
newWI["Title"] = "AUTOGENERATED!";
'
Custom.ChangedDailyWork - a field wich contains user, that changed WI (COPY crom currentuser) and it have a format "Name SecondName <DOMAIN\username>"

tasks are creating good when Custom.ChangedDailyWork contains one user (User a). And they are not creating when Custom.ChangedDailyWork contains another (user B). This users have same rights. When i am typing their names - tfs recognises them.

What can be wrong?

**Comment by jessehouwing** [comment]
https://github.com/tfsaggregator/tfsaggregator/issues/97

It has to be the exact display name. Which can be tricky. We may need to provide an api to look up users by their logon name.

**Comment by ASolovyev** [comment]
whe know all their logon names :) and all information from AD. But i can't recognise what is wrong there. It's a regular names.

**Comment by ASolovyev** [comment]
Sorry. I translated yor message wrong. Ill try to cut display name from field.

**Comment by ASolovyev** [comment]
if i try to put display name to AssignedTo field it do not work.

**Comment by ASolovyev** [comment]
Domain name do not work too.
First time i tried to cut display name from that field.

' var name = @"Alexey Solovyev<Domain\ASolovyev>";'
'            name = name.Substring(0, name. LastIndexOf(' '));'
'            this.button1.Text = name;'
it returned "Alexey Solovyev"

now i tried to cut domain name. Result is the same



       '  var name = @"Alexey Solovyev<Domain\ASolovyev>";'

'            int start = name.LastIndexOf('\\');'
'            int end = name.LastIndexOf('>');'
'           newWI["System.AssignedTo"] = assignedto;'

It returned "ASolovyev"

When i tried manually in web put this into assigned to it works. But From the aggregator it does not. Worked only full (Alexey Solovyev<Domain\ASolovyev>) and for all but 2 users 0_o

**Comment by jessehouwing** [comment]
This is a problem with the workitem api. And remember that users can
change their display name.

**Comment by ASolovyev** [comment]
Yes i know it. Can debug help to see why aggregator cant create new task?  It shows no errors about it in event log.

**Comment by jessehouwing** [comment]
With doing a debug trace should give you more details. But in your case it
likely can't find the user.

**Comment by ASolovyev** [comment]
i see. I'll try to debug and will try to create task using api next two days.

**Comment by ASolovyev** [comment]
well...it's really tfs problem. I created my app which only creates a workitem. And my tfs do not create items with several names. Thank you!

**Comment by jessehouwing** [comment]
**Let's see if we can fix this**

We should be able to provide a interface which allows you to query users by other means, that way we can at least try to feed the proper DisplayName to the Field value.

```
IIdentityManagementService2.ReadIdentity(...) : TeamFoundationIdentity
```

Should allow us to get the user by domain name, guid, etc.
