### ISSUE TITLE
Compatibility with TFS "15" (2016/17)

### ISSUE THREAD

**Issue by jessehouwing** [tfsaggregator/tfsaggregator#164]
Required updates:
- [ ] Target framework 4.6
- [ ] Update references to new Server Object Model
- [ ] Update nuget packages for new Client Object Model (-preview)
- [ ] Update other dependent nuget packages
- [ ] Update analyzers to latest versions
- [ ] Update sources to use the TFS2015r2 conditional compile statements
- [ ] Update installer

Harder issues:
- [ ] Enable support for multiple versions of the Nuget packages
- [ ] Enable support for multiple versions of the .NET Framework targets (TFS "15" requires 4.6.1)

**Comment by jessehouwing** [comment]
Trial upgrade done to verify the first set of steps would work:
* https://github.com/tfsaggregator/tfsaggregator/tree/TFS15

**Comment by Russweb** [comment]
Is this why my rules and rolling up are all broken now with TFS 15?
Is this not compatible?

Please reply soon to let me know if that is what I am dealing with.
This creates an emergency for me.

**Comment by jessehouwing** [comment]
You need a build that wss compiled against the latest binaries. Check out
the branch I created.

**Comment by giuliov** [comment]
@Russweb and you can also consider the webhooks branch where TFS aggregator runs out-of-process

**Comment by Russweb** [comment]
downloaded the TFS15 branch you provided via the zip option.
There was no binaries in it, so I tried to compile it.
Tons of errors.
I assume VS 2015 update 3 is not sufficient enough?
Do I need to go pull the binary refs off of my TFS server individually and update the refs in all the projects until the errors are gone?
Better suggestions?

**Comment by jessehouwing** [comment]
I personally have tfs15 insralled om the machine I use to build the
project. We automatically detect the installation and grab the references
from there.

Alternatively, copy the contents of the tfs job agent's collective set of
assemblies from the tfs server and dump them in the right references folder
(which is what we use on the build server linked to this project).

**Comment by giuliov** [comment]
I use a VM with just VS201x.y where I copied the references from other VMs, each running a different TFS version plus the remote debugger agent. This permits me to validate locally the many build configurations and repro bugs on older TFS versions.
Sadly, I still have to add TFS "15" in my configuration and integrate Jesse's work in the build, so I do not have a pre-canned set of file to share.

@jessehouwing I remember you shared with me some details on TFS "15" build, on Slack maybe; it could be that those notes will help @Russweb

**Comment by Russweb** [comment]
K. That does sound like I have not shortcuts :)
I'm working through the build errors now after updating all the refs to the new binaries.
Still have issues with it saying there are references to 12.0.0.0 somewhere, and that I am using 15.0.0.0.
So its not happy.
I'll track it down :/

**Comment by jessehouwing** [comment]
Make sure you select the debug or release configuration for the right tfs
version.

**Comment by giuliov** [comment]
I was able to build locally by copying the following DLLs from `C:\Program Files\Microsoft Team Foundation Server 15.0\Application Tier\Web Services\bin` to _<tfsaggregator_folder>_`\References\2016`.

- Microsoft.TeamFoundation.Common.dll
- Microsoft.TeamFoundation.Framework.Server.dll
- Microsoft.TeamFoundation.Server.Core.dll
- Microsoft.TeamFoundation.WorkItemTracking.Server.DataAccessLayer.dll
- Microsoft.TeamFoundation.WorkItemTracking.Server.DataServices.dll
- Microsoft.TeamFoundation.WorkItemTracking.Server.dll

I also changed line **318** of `TfsReferences.target` to
```
<ServerAssemblies Condition="'$(TfsInstallationDirectory)'=='' And '$(TfsVersion)' == '15.0'">..\References\2016</ServerAssemblies>
```
it had 2015.2 which is incorrect.

**Comment by Russweb** [comment]
I got it to work by
pulling the binaries down from the same place mentioned above on the server, 
swapping out all of the references
changing to 2016 configuration

Thx for your help.

**Comment by Russweb** [comment]
Unrelated.. Sorry...(is there a general Q&A area?)
After a situation like this, when all of your rollups/aggregations, and other rules are now out of date...along with your data....

Is there a simpler way to get everything up to date on thousands and thousands of work items, w/o having to trigger a change on them all?
Currently, I have resorted to doing a bulk add of a tag, and then having to bulk remove it again. :( to trigger a change in all work items.

Thx in advance for any advice.

**Comment by giuliov** [comment]
In GitHub Q&A is an Issue tagged _question_ or a wiki area -- and by the way give everyone permissions to edit this project wiki (note to self: it is not stated clearly).

As per your question, you can use the command line tool. Sadly the current version accept only a single workitem ID, but it should be easy to make a script that invokes the tool for each work item.
