### ISSUE TITLE
Picking children issue.

### ISSUE THREAD

**Issue by ASolovyev** [tfsaggregator/tfsaggregator#165]
Hi everybody again .
A long time ago in issue #64 i asked about picking children. So i used hasfield property. But now i noticed that this property works only for parent and i read about it in wiki. Also i found there a code from #64 

`var child in self.Children.Where(
   child => child.Field.Any(
      field => field.ReferenceName == "Custom.Product")
);`

and i wrote my own code with this

`sorru not fore codeblock. It formatting code below poorly`
foreach (var child in self.Children.Where(child => child.Field.Any(field => field.ReferenceName == "Microsoft.VSTS.Scheduling.OriginalEstimate"))
			{
				if(((string)child["System.WorkItemType"] != "autogenerated") ) 
				{
					checkedValue += (double)(child["Microsoft.VSTS.Scheduling.OriginalEstimate"]??0d);
					othersCount += 1;
				}
				else
				{
					autogeneratedCount += 1;
				}
			}

But i have an error while aggregator start its work:

Error CS1061 in script 'Check_Original_Estimate' at line 9, column 60: 'Aggregator.Core.Interfaces.IWorkItemExposed' does not contain a definition for 'Field' and no extension method 'Field' accepting a first argument of type 'Aggregator.Core.Interfaces.IWorkItemExposed' could be found (are you missing a using directive or an assembly reference?)

**Comment by giuliov** [comment]
It is a typo in the documentation: use `Fields` instead of `Field`.

**Comment by ASolovyev** [comment]
Thank you! It works fine :)

**Comment by giuliov** [comment]
Need to fix wiki (leverage v2.1.1)
