### ISSUE TITLE
Copy Field value from parent work-item to Child Work-item

### ISSUE THREAD

**Issue by ShreeSam** [tfsaggregator/tfsaggregator#171]
Hi Team,

Is it possible to copy field value form parent work-item to child work-item? i have a custom field in Epic and Feature work-item i have to copy value form Epic to Feature after creating and mapping Feature  to Epic.

is it possible? Please share syntax for the same.

Thanks in Advance,
Shree

**Comment by giuliov** [comment]
Of course. You need a rule triggered when a Feature is linked to its Epic, something like this:
```
<rule name="pushDownCustomField" appliesTo="Feature" hasFields="My.CustomField">
var feature = self; // for readability
if (feature.HasParent()) {
  var epic = feature.Parent; // for readability
  if (epic.TypeName == "Epic") { // sanity check
    feature["My.CustomField"] = epic["My.CustomField"];
  }
}
</rule>
```
Please I have not checked this example, follow the suggestions in the [Wiki](https://github.com/tfsaggregator/tfsaggregator/wiki), particularly [Using the console to test Policies](https://github.com/tfsaggregator/tfsaggregator/wiki/Console-App).

**Comment by ShreeSam** [comment]
It Worked :-). 
Thank you so much.

Regards,
Shree

**Comment by ShreeSam** [comment]
Hi,

I have a requirement were parent field has to updated with a value form child.
Eg: We have a field "Definition" with Allowed values "In progress, Complete, Not Started". We need to update feature Definition field as "In progress" if all Child User Story is "In progress".

Is it possible? Please share syntax for the same.
Thanks,
Shree

**Comment by giuliov** [comment]
There is plenty of such examples in the issue and probably in the Wiki also. You will do us a favor if you enrich the Wiki by collecting and polishing them :-)

**Comment by dkelertastspl** [comment]
Is it possible to do this across linked work items, not just parent-child work items? Such as Product Backlog Item and having a create linked test case work item and the test case (with the same custom field defined in the form) gets the value synchronised between the two work items, either once off at creation or ideally values kept in-sync over time

**Comment by giuliov** [comment]
@dkelertastspl can you open a new issue?

**Comment by meermansubdar** [comment]
@giuliov in which file should I define this rule
