### ISSUE TITLE
Cannot retrieve Parent information 

### ISSUE THREAD

**Issue by Fall88** [tfsaggregator/tfsaggregator#172]
Hi,
I have just started using TFSAggregator V2.1.178 and created a test policy file.
When I try to retrieve another workitem such as a child/parent or from the store using a workitem ID I keep getting cast errors?

I have attached the test policy file with the rule I am using, which is quite simple actually, 
I really don't know what I am doing wrong, please advise...
Any help/tips is appreciated...

[TFSAggregator2.ServerPlugin.policies.txt](https://github.com/tfsaggregator/tfsaggregator/files/411397/TFSAggregator2.ServerPlugin.policies.txt)

**Rule code:**
if (self.HasParent()) {
        logger.Log("parent title: {0}", (string)self.Parent["System.Title"]);
}

**Error from console:**
[Information] 00.067 Aggregator.Core started, version: 2.1.178-master, build: 2.
1.178, configuration: Release [TFS 2015.0]
[Information] 00.228 Configuration loaded successfully from 'C:\Temp\TFSAggregat
or2.ServerPlugin.policies'
[Verbose]     01.301 Building Script Engine for C#
[Information] 02.397 Starting processing on workitem #17849
[Critical]    02.587 Exception encountered processing notification: Server was u
nable to process request. ---> There was an error generating the XML document. -
--> Specified cast is not valid.
Stack Trace:   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore
.LoadWorkItem(Int32 id, Int32 rev, Nullable`1 asof, IWorkItemRowSets& witem)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem..ctor(WorkItemSt
ore store, Int32 id)
   at Aggregator.Core.Facade.WorkItemRepository.GetWorkItem(Int32 workItemId) in
 C:\projects\tfsaggregator\Aggregator.Core\Facade\WorkItemRepository.cs:line 50
   at Aggregator.Core.EventProcessor.ProcessEvent(IRequestContext requestContext
, INotification notification) in C:\projects\tfsaggregator\Aggregator.Core\Event
Processor.cs:line 58
   at Aggregator.ConsoleApp.RunCommand.Run(String[] remainingArguments) in C:\pr
ojects\tfsaggregator\Aggregator.ConsoleApp\RunCommand.cs:line 116

**Comment by giuliov** [comment]
It is stopping before executing any rule; it is calling TFS client API to retrieve the work item.
The error may be caused by some conflict in the client machine (say you have multiple versions of TFS client assemblies), a mismatch between client and server or a drop in the connection.
Which version of TFS you are calling?

**Comment by Fall88** [comment]
I am running it on the actual TFS server which has TFS 2015 Update 1.
The strange thing is that the code to retrieve the information of the current workitem (self) does return results....

**Comment by Fall88** [comment]
So the command rule below **does** return a result
    logger.Log("my title: {0} ", (string)self["System.Title"]); 

And the command rule below does **not** return a result but gives the error mentioned above about the cast
    logger.Log("parent title: {0}", (string)self.Parent["System.Title"]);

**Comment by jessehouwing** [comment]
Can you dump the Work Item Type Definitions for self and self.Parent in your case? use `witadmin exportwitd` to export them and attach them to this issue, it may be that there is something fishy about your process template.
