### ISSUE TITLE
Rollup for user stories fields

### ISSUE THREAD

**Issue by ShreeSam** [tfsaggregator/tfsaggregator#173]
Hi Team,

Am trying to get all child User Stories value into Feature. But am not able to get. Please find below settings.

<rule name="RollupUS" appliesTo="User Story">
	<![CDATA[
	if (self.HasParent())
	{
    var parent = self.Parent;
    parent["Custom.ActualHours"] = parent.Children.Sum(user story => user story.GetField<double>("Custom.ActualHours", 0d));
    parent["Custom.PlannedHours"] = parent.Children.Sum(user story => user story.GetField<double>("Custom.PlannedHours", 0d));
	parent["Custom.RemainingHours"] = parent.Children.Sum(user story => user story.GetField<double>("Custom.RemainingHours", 0d));
    parent["Custom.PercentComplete"] = parent.Children.Sum(user story => user story.GetField<double>("Custom.PercentComplete", 0d));
	parent["Microsoft.Custom.POEstimate"] = parent.Children.Sum(user story => user story.GetField<double>("Microsoft.Custom.POEstimate", 0d));
	parent["Microsoft.Custom.IntitalEstimate"] = parent.Children.Sum(user story => user story.GetField<double>("Microsoft.Custom.IntitalEstimate", 0d));
	}
	]]>
</rule>
But nothing works.

Thanks in Advance,
Shree

**Comment by giuliov** [comment]
Must be valid C#, `user story` is not a valid identifier. Try `user_story` instead.

**Comment by chillmanstr8** [comment]
Is there a way to determine valid identifiers?  (I'm not a programmer)

**Comment by giuliov** [comment]
Short answer: a contiguous sequence of letters and numbers starting with a letter.
**Long answer**: [C# Language Specification](https://www.microsoft.com/en-us/download/details.aspx?id=7029), section 2.4.2 page 38.
**Practical answer**: test the policy with the command line tool, if you get a compile error, it is not valid.
