### ISSUE TITLE
Confused on Rollup Sample

### ISSUE THREAD

**Issue by Lehrsj** [tfsaggregator/tfsaggregator#174]
In the documentation there is this rollup sample:

<rule name="Rollup" hasFields="Estimated Dev Work;Estimated Test Work"><![CDATA[
  if (self.HasParent()) {
    self.Parent["Total Estimate"] = (double)self.Parent["Estimated Dev Work"] + (double)self["Estimated Test Work"];
  }
]]></rule>

It says: This aggregation will total the values found in the Estimated Dev Work and Estimated Test Work fields for all Task work items on the parent. The total will go in the Total Estimate field on the parent one level up from the Task.

It says it is going to rollup the two fields - Estimated Dev Work and Estimated Test work from all the tasks to the parent.  Why does it have the Estimated Dev Work that is totalling coming from the parent?  

(double)self.Parent["Estimated Dev Work"]   Shouldn't they both the from self?

**Comment by giuliov** [comment]
Which is the wrong page?
