### ISSUE TITLE
Deleting a work item throws event log Error

### ISSUE THREAD

**Issue by djohnson7789** [tfsaggregator/tfsaggregator#176]
It seems that every time a work item is Deleted using the new Delete functionality in TFS 2015, a rule is fired for that work item type and the following error is thrown:

 TF26198: The work item does not exist, or you do not have permission to access it. 

Logically, this makes sense considering that the work item is now deleted.  But is there any way to modify the Policies file/Rules to prevent rules from being fired on work item deletion?

Any help is greatly appreciated.

**Comment by jessehouwing** [comment]
We'd have to investigate. It may be difficult, since one of the first
things we do is to open the work item to see what is changed.

**Comment by giuliov** [comment]
WebHooks event tells the kind of change (new/changed/deleted/restored).
Hopefully next month we can test this feature enough.

Giulio

**Comment by giuliov** [comment]
Truly `Microsoft.TeamFoundation.WorkItemTracking.Server.ChangeTypes` has been extended in 2015 and now the values are _New_, _Change_, _Delete_ and _Restore_. This means that we can use this information.

@jessehouwing I am inclined to add a multi-valued attribute to specify when the rule should trigger, e.g. `<rule name="MyRule" on="New,Change">` with that default value.

**Comment by jessehouwing** [comment]
That's nice! Backcompat will be fun though.

**Comment by giuliov** [comment]
Available in 2.3, currently only for the Web Service, soon for the Server Plugin
