### ISSUE TITLE
Fetching linked TestCases

### ISSUE THREAD

**Issue by einar20** [tfsaggregator/tfsaggregator#177]
I have created some rules that applies on the "Task" work item type.

When saving a Task with state "Closed", I would like to auto-update the parent UserStory to state Closed, if the following conditions are met:
  - ALL child Tasks are “Closed” (or Removed)
  - At least one link "Tested by " Test Case exist on UserStory
  - ALL linked Test Cases are “Passed” (or Deleted)

Checking state of child Tasks works fine, but I can't see how I can get the linked Test Cases - they are not parent-child links, but linked to UserStory as "Tested By"

The following code exctract might describe my problem:

```
if ((self.HasParent()) && ((string)self.Parent["System.WorkItemType"] == "User Story"))
{
    var myUserStory = self.Parent;
    string myState = (string)self["System.State"];

    switch (myState)
    {             
        // ... actions for other states works fine...

       case "Closed":
             bool closeUserStory = true;   //default until proven otherwise :)

            //First, check if any of parents child tasks are not still "New" or "Active"
            foreach (var child in myUserStory.Children.Where(child => new[] {"Task"}.Contains((string)child["System.WorkItemType"])))
            {
                if (new[] {"Active", "Closed"}.Contains((string)child["System.State"]))
                {
                  closeUserStory = false;
                  break;
                }
            }
                              
          //Secondly, check that there is at least one linked TestCase to myUserStory with state different from deleted - if not set closeUserStory = false
              //-> How to get count of linked TestCases (with state different from Deleted) to myUserStory?
              
          //Finally, check that there are no linked TestCases with state different from "Passed"
              //-> How to loop through each linked TestCase and check that none of them has state different from "Passed" (or "Deleted")  ?
       
                
        //Close UserStory if conditions met
        if (closeUserStory)
        {
            myUserStory.TransitionToState("Closed", "Autoupdated");
        }

        break;   //case "Closed"
                
    default:
        break;
    }     
}
```

Any suggestions?

**Comment by giuliov** [comment]
Current version does not expose the links collection. You can reach a similar result using a [Fluent query](https://github.com/tfsaggregator/tfsaggregator/wiki/self-Object#fluent-queries), although.

**Comment by jessehouwing** [comment]
But I think you can't get access to the current test case status, as that
is exposed by the api as a test point, which isn't a workitem.

Exposing test results, suites and plans with their links isn't yet
supported.

**Comment by einar20** [comment]
@giuliov 
Thanks for your input, pointing to Fluent query.

Seems like I at least can get an object reference to sibling TestCases from a task, by

`
var testCases = myParentUserStory.FollowingLinks("Microsoft.VSTS.Common.TestedBy-Forward").WhereTypeIs("Test Case");
                  foreach (var test in testCases);
                  {
                       //.. do something on test case
                  }
`

Altough, it looks like @jessehouwing is also right about unable to access state of that test case...
`if ((string)test["System.State"] != "Deleted")`
gives an error about "the name 'test' does not exist in the current context" ...

Have to look further into this later this week, I'll post an update if I find a way around

**Comment by einar20** [comment]
Tried this out tonight, and it works as needed :-)
Using  `FollowingLinks("Microsoft.VSTS.Common.TestedBy-Forward").WhereTypeIs("Test` Case") ` on the tasks parent user story item, gave access to all Test Cases testing the parent user story. Getting these test cases state, was also straight forward.

I used the following code to verify whether I could close the parent UserStory item, after a Task item was set to state Closed:

`
      
<rule name="AutoUpdateParentState" appliesTo="Task">
    <![CDATA[
             
    if ((self.HasParent()) && ((string)self.Parent["System.WorkItemType"] == "User Story"))
    {
        string myState = (string)self["System.State"];
        var myParentUserStory = self.Parent;      
        
        switch (myState)
        {             
            // ... actions for other states not shown here...

           case "Closed":
              bool siblingTasksClosed = true;  //default until proven otherwise
              bool testCasesPassed = true;     //default until proven otherwise 
              int testCaseCount = 0;
              
              //First, check if any of parents child tasks are still "New" or "Active"
              foreach (var child in myParentUserStory.Children.Where(child => new[] {"Task"}.Contains((string)child["System.WorkItemType"])))
              {
                  if (new[] {"Active", "New"}.Contains((string)child["System.State"]))
                  {
                      siblingTasksClosed = false;
                      break;
                  }
              }
              
              //Then, verify that at least one TestCase exists, and that all tests are "Passed"
              var testCases = myParentUserStory.FollowingLinks("Microsoft.VSTS.Common.TestedBy-Forward").WhereTypeIs("Test Case");
              foreach (var test in testCases.Where(test => new[] {"Not Implemented", "Ready For Test", "Failed", "Passed"}.Contains((string)test["System.State"])))
              {
                  testCaseCount++;
                  
                  //Check that there are no linked TestCases not yet "Passed"
                  if (new[] {"Not Implemented", "Ready For Test", "Failed"}.Contains((string)test["System.State"]))
                  {
                      testCasesPassed = false; 
                      break;
                  }
              }

              if (siblingTasksClosed && testCasesPassed && (testCaseCount > 0))
              {
                  // This Tasks parent user story has tasks and testcases, and all tasks are "Closed" & all TestCases "Passed"
                  // parent user story can be closed
              }

              break;   //case "Closed"

           default:
              break;
        }

        // Do state transtions according to findings above
    }
    ]]>
 </rule>
  
`
Thanks for pointing me in the right direction, I was kind'a stuck there for a while :-)

**Comment by giuliov** [comment]
Happy to hear, and thanks for sharing.
I see the opportunity for some helpers/extensions to make the rule code more readable (e.g. Strongly Typed properties for core fields).

`new[] {"Not Implemented", "Ready For Test", "Failed"}.Contains((string)test["System.State"]`
may be written
`test.State.In("Not Implemented", "Ready For Test", "Failed")`

similarly
`new[] {"Task"}.Contains((string)child["System.WorkItemType"])`
become
`child.Type.In("Task")`

and BTW [`TypeName`](https://github.com/tfsaggregator/tfsaggregator/wiki/self-Object#miscellaneous-properties) property is already available

**Comment by einar20** [comment]
Thanks again for your feedback @giuliov . Highly appreciated.
Readability is important, unfortunately my programming skills are a bit rusty after some years absence from programming :-)

However, after changing to ` child.Type.In("Task") ` , I got the following error when testing my policy file with TFSAggregator2.ConsoleApp:

_[Error]       01.422 Error CS1061 in script 'UpdateMyChilds' at line 46, column 76: 
'Aggregator.Core.Interfaces.IWorkItem Exposed' does not contain a definition for 'Type' and no extension method 'Type' accepting a first argument of type 
'Aggregator.Core.Interfaces.IWorkItemExposed' could be found (are you missing a using directive or an assembly reference?)_

Codeline:
` foreach (var childTask in self.Children.Where(childTask => childTask.Type.In("Task")))  {  `
Similar result when trying
` foreach (var childTask in self.Children.Where(childTask.Type.In("Task")))  {   `

**Comment by giuliov** [comment]
@einar20  No no, my bad. I meant that we have enhance rule code, not that it is available. The only property you can use is [TypeName](https://github.com/tfsaggregator/tfsaggregator/wiki/self-Object#miscellaneous-properties) like this `self.Parent.TypeName == "Task"`.

**Comment by einar20** [comment]
@giuliov  Aha, I see what you meant now :-) Yes, such enhancements would be appreciated in future updates.

Using Typename is however much more clean and readable than my array with contains, works fine with ` foreach (var childTask in self.Children.Where(childTask => childTask.TypeName == "Task"))  {  `
