### ISSUE TITLE
Infinity loops - question

### ISSUE THREAD

**Issue by einar20** [tfsaggregator/tfsaggregator#179]
I have created a policy file for Aggregator, having a set of rules to apply on custom and system fields for different work item types. For instance, I use my own variants of [AutoOpen and AutoClose](https://github.com/tfsaggregator/tfsaggregator/wiki/Auto-Open-Auto-Close), [Auto-creating children](https://github.com/tfsaggregator/tfsaggregator/wiki/Auto-Create-Children), etc etc.

Many of my rules, applies changes in the parent-child context
- When a Task is saved, this may cause aggregations on the parent UserStory
- When a UserStory is changed, this again may cause aggregations on all/some child Task items

My concern is infinity loops. So far it has not happened, as I'm careful to not update an items value if that item already has the target value.

However, consider the following code (written only in purpose to force such infinity loop and see what happens :)
`
// rule name="UpdateMyChilds" appliesTo="User Story"
        
      foreach (var childTask in self.Children.Where(childTask => childTask.TypeName == "Task"))  {   
          childTask["System.Title"] += " Hello from Story #" + self.Id;
      }

// rule name="UpdateMyParent" appliesTo="Task"

      if (self.HasParent()) {
          self.Parent["System.Title"] += "Hello from Task #" + self.Id;
      } `
- When a UserStory is saved, the policy will change all Tasks
- When those Tasks are changed, that again will cause the userStory to change
- And there we go ...

I assumed setting the rateinterval to changes=2, would stop the loop after a while, ` <rateLimiting interval="00:00:01.0" changes="2" /> `
However, the above loop-code continued for ever until I breaked console app at loop 6 or 7 or so.

Is there any way to make changes to a work item from aggregator policy, without getting that change to once again trigger the aggregator policy? Sort of flag a field change to be performed in "stealth mode", not picked up by aggregator policy's radar?

**Comment by jessehouwing** [comment]
The workitem should detect that there are no real changes to fields and
stop, unless, like you do, you keep adding text to a title recursively.

The loop detection code should kick in when more than x changes to the same
workitem happen in the given time span. It's likely that you won't trigger
this limit if the time span is as small as yours given the usual network
round trip time and the fact that we need to request all child work items
every loop, this will cause additional network round-trip.

Upping the time span to say 5 seconds will probably auto-break the loop.

**Comment by jessehouwing** [comment]
We don't have a high water field or tripwire field built in, you could
write a rule that does that, but the hard part is knowing which rules to
stop and which ones to allow through. Especially if, as in your case you've
created recursive rules that are meant to trigger successive changes.

One way to do it, is write a text to the history field and then check the
value of the previous workitem revision to see if it was saved by the
Aggregator. But be really careful with this field, as it in itself can
cause infinite loops quite easily. See the wiki for more information.

**Comment by einar20** [comment]
Thanks for the feedback, @jessehouwing 

For the rules I have created so far, aggregated changes to a field trigging "kick-back changes" is desired behavior, and I haven't experienced any problems. Just a concern that came to mind, that I would need to be very careful checking current values before assigning a value, to avoid un-needed updates, and that I would need to set an exact value for `rateLimiting interval`.
But if the workitems detects if there are "real" changes to fields or not, at least my current set of rules should be safe :)

**Comment by giuliov** [comment]
This is a subject we discussed but there is no simple answer.
For example, we might store work item ids and versions in a separate store to check for loops, so work item schema is untouched. But the algorithm is hard to implement and, if you think to a TFS farm scenario, you will agree that the impact on deployment and performance is huge.
