### ISSUE TITLE
Extend the Object Model with rich navigation

### ISSUE THREAD

**Issue by giuliov** [tfsaggregator/tfsaggregator#18]
Extend the Object Model with ability to navigate across most all work item link types for many levels deep, with filtering and querying abilities. Kind of enabling LINQ or WIQL or XPath to select work items.

**Comment by rbanks54** [comment]
What do you mean by this one?

**Comment by jessehouwing** [comment]
This is to support other than Parent-Child  navigation using a simple syntax. ".Parent" and ".Children" doesn't suffice and simple tree transversion doesn't work in directed graph and undirected graph scenario's.

This is helpful to find all tests under a requirement for example, or set/unset blocked field based on status transition when using CMMI predecessor/successor relationships. 

Another possible scenario would be to update all work items marked as "duplicate" that the original has changed state.

**Comment by rbanks54** [comment]
Ah. I thought you were referring to the TFS OM. Thanks for clarifying.
If we implement scripting, and keep our interface simple, then this requirement would disappear, wouldn't it? We would leave it up to the script to navigate between work items and determine what calculations it wants to do.

**Comment by jessehouwing** [comment]
I'd prefer a number of helper methods, one to parse the state model for
example,like in the original aggregator.

Intelligent navigation of relations is another.

Letting each developer write their own is such a shame.

**Comment by rbanks54** [comment]
And yet at the same time, trying to dynamically determine all the available navigation options for a work item is going to result in extra processing and be difficult to code from an API perspective without resorting to magic strings. It also feels like reinventing the wheel, and we're presuming we know what the scripts will want to do.

I'm much more strongly in favour of the build v.Next approach, and just make the aggregator a task runner. Let script authors determine what they want to do, don't presume we know what they will want to do, and let them used the published TFS APIs that already exist instead of trying to reinvent the wheel and get them to learn yet another API.

**Comment by jessehouwing** [comment]
The Link types (DirectedNetwork, Network, Tree, or Dependency) are well
known. And a traversal algorithm that accepts the Link name and optional
direction for these would be all that's needed. That would support any and
all links created by the Process templates.

An Enum with well-known linktypes is something we could supply as a bonus.

Dependency (for example) is "safe" to traverse for the TFS Aggregator, as
is "tree". The other two require traversal checks to prevent accidental
loops.

I'm proposing this as a WorkItemHelper, mostly static methods or Extension
Methods that can be injected into the scripts. These would be helpful for
any TFS project and are not entirely specially crafted for this project.
Though I don't know of a library that already has these.

For the scripts to use these type of libraries (like Work Item Linq), we do
need to load them and provide a safe way to get access to the client object
model. A wrapper around the default work item model puts us in control of
cleanup, direct API access is something I'd want more shielding around ;).
This is an important aspect of allowing script vs a simple DSL.

**Comment by giuliov** [comment]
Jesse has cleary unfolded the item: a nice facility to make the script easy to read and write. The ideal implementation is to have our own script language with an ultra-simplifed syntax, but we must limit the effort. For most scripting engine integration, you expose an Object Model with multiple purposes:

 1. simplifying end-user code
 2. limit access to avoid interference and security issues
 3. lazy-loading

**Comment by rbanks54** [comment]
OK. Let's see what we can come up with :-)
