### ISSUE TITLE
read only fields

### ISSUE THREAD

**Issue by mattpdipietro** [tfsaggregator/tfsaggregator#180]
One of the example policies shows setting the value of a read only field (Estimated Work) based on the values of two editable fields (Estimated Dev Work and Estimated Test Work).

However, every time I try to do the same (set a value on a field marked as read only, I get an Invalid field error for that rule.  Is there something in particular that needs to be done to support modifying a read only field value?

**Comment by giuliov** [comment]
We do not have the resources to review everything at each release; it could be that the example goes back to v1.
I invite you to contribute by submitting a PR or directly editing the Wiki to correct information; this also makes our job to review the issue easier.

**Comment by mattpdipietro** [comment]
Thanks for responding. I was able to circumvent the issue by adding a condition on the field definition that it was not read only for the Project Collection Administrators group which allowed the update to occur since we do not have auto impersonation enabled.
