### ISSUE TITLE
Question about updating TFS UI

### ISSUE THREAD

**Issue by LawrenceBeran** [tfsaggregator/tfsaggregator#183]
I am not sure if this is achievable from within TFS Aggregator but I thought I would ask just in case someone here has got a solution for this issue.

I have successfully written some policies that update the state of related work items and also rolled up some values. These work very well.

But within TFS when viewing the items in a query or on the sprint board the related items are not refreshed with the new values until the TFS results are refreshed or the browser is refreshed.

Does any one know if it is possible to mark the updated related work item to be refreshed within the TFS GUI so any chances are shown when made?

Thanks in advance,
Lawrence

**Comment by jessehouwing** [comment]
No. Sorry.

**Comment by jessehouwing** [comment]
This is something the Microsoft Product Team will have to provide. Now that they've adopted SignalR for certain elements of the UI this may become reality in a future version. As for any version up to TFS 15RC, this is not possible.

And even if it were implemented, it's highy unlikely that this will feed back into the Excel and Project integration as well as the Visual Studio native query window.
