### ISSUE TITLE
Split the policies file to two policies file

### ISSUE THREAD

**Issue by helhaddad** [tfsaggregator/tfsaggregator#184]
Can i spleate the policies file to two policies file

1 - One with a rule 
```
         <policy name="Policy1">
        <collectionScope collections="*" />
```
2 - The second with 
```
        <policy name="Policy2">
        <collectionScope collections="*" />
        <projectScope projects="Project1" />
```

**Comment by jessehouwing** [comment]
We've had this as part of our initial design discussions and decided against it. Separating out files bring the requirement to know in which order to load the files. And that was something we didn't want to tackle in the first rewrite.

For certain rules the order of execution is important for performance, and by keeping everything in one file that is easy to ensure.

For now we're not considering revisiting this decision. Though you could build this yourself and propose a pull request.

**Comment by helhaddad** [comment]
Thank you for your answer
In the same file policies we can not have two sections
    "<Policy name =" Policy1 ">
         <CollectionScope collections = "*" /> "
  and
"<Policy name =" Policy2 ">
         <CollectionScope collections = "*" />
         <ProjectScope projects = "Project1" /> "

**Comment by jessehouwing** [comment]
From the XSD:

```
<xs:element minOccurs="1" maxOccurs="unbounded" name="policy">
```

You can repeat the `<policy>` element as many times as you'd like.

**Comment by jessehouwing** [comment]
The whole idea is that you can define all your rules and without having to duplicate them into a gazillion files, re-use hem in different collections or for different process templates.

We recommend you use the Process template policy scope by the way, otherwise you'd have to reconfigure your policies with every project that is added. This way you can align the process template with the ruleset.

**Comment by giuliov** [comment]
That is the reason for naming it the _polic**ies**_ file. I clearly remember the decision of allowing the composition of rules and application scopes so you can mix and match to which Project a Rule will apply.

**Comment by jessehouwing** [comment]
I'd still love to see sharable "rulesets" that we could share off this site or package along with the plugin, but it'd be a lot of work to make it work seamless and sound.

**Comment by helhaddad** [comment]
Let me explain why I need to define two sections policy in my plocies  file
I created two TFS project with the same Process Template and in the same collection.

I have common rules between the two projects (the first policy section) and I have a rule that I want to apply it only on the project1 (La 2 policy section)

**Comment by jessehouwing** [comment]
So you can simply define:

```
        <policy name="GenericPolicy">
            <collectionScope collections="*" />
        </policy>
        <policy name="Project1-Specific">
            <collectionScope collections="CollectionOfProjectOne" />
            <projectScope projects="Project1" />
        </policy>
```

Because the project name isn't unique within a TFS server deployment, you shouldn't use the `collections="*"` on the second policy, but scope it to the correct Project Collection.

**Comment by helhaddad** [comment]
```
    <policy name="GenericPolicy">
        <collectionScope collections="*" />
		<ruleRef name="AutoActivateParents" />
		<ruleRef name="AutoResolvedParents" />
    </policy>
	
	<policy name="SpecificPolicy">
                <collectionScope collections="DefaultCollection" />
		<projectScope projects="Project1" />
		<ruleRef name="AutoUpdateTasksToQaReady" />
    </policy>
```
Rules of the first policy section works ;) and the second policy section does not work !!!!!!

**Comment by jessehouwing** [comment]
Please check and optionally post the debug logs. Each policy scope logs why it decided to apply or not. See: https://github.com/tfsaggregator/tfsaggregator/wiki/Debugging

**Comment by helhaddad** [comment]
Please, I do not see how this 'https://github.com/tfsaggregator/tfsaggregator/wiki/Debugging' link can help me

**Comment by jessehouwing** [comment]
Have you walked through the first link? It helps you grab the logs. The second link is for when you need to validate the implementation of the plugin (our code). Hopefully it won't come to that.

Remember, this is a free, open source TFS plugin we've built in our own spare time. And we're doing what we can to help you resolve the issues. But it's not a commercial product. If you'd like you can hire either of us at our standard consultancy prices, but if not, you'll have to do some of the debugging yourself to help us figure out if there is a mistake in our code so we can fix it. 

Either write a unit test that fails, provide us with a full set of steps to reproduce that doesn't require us to build a environment based on assumptions, provide the detailed logs so we can try to analyze where the mistake in our code is, submit a pull request with an improved piece of code that solves the bug you've found (if any).

**Comment by helhaddad** [comment]
Thank you very much for your help Mr Jesse.
Thank you for this very interesting plugin, and I thank you that you have spend to expand, it is great work, 
Thank you for the time you spend to develop this great job.

To reproduce the anomaly is really sample :
1 - I created 2 Team projects in my TFS  (Project 1 and Project 2)
2 - In the policies file i add 3 rules (state transition)  2 rules is common between the 2 Projects and the second is for the Project 1

,,,
<policy name="GenericPolicy">
        <collectionScope collections="*" />
        <ruleRef name="AutoActivateParents" />
        <ruleRef name="AutoResolvedParents" />
    </policy>

    <policy name="SpecificPolicy">
         <collectionScope collections="DefaultCollection" />
        <projectScope projects="Project1" />
        <ruleRef name="AutoUpdateTasksToQaReady" />
    </policy>
'''
The second section does not work !!!
If i add the rule 'AutoUpdateTasksToQaReady' to the first section it work fin.

Thanks a lot for your help

**Comment by jessehouwing** [comment]
Your team project in your text is `Project 1` and in your policy it's `Project1` (note the space)... Is that possibly the cause? 

PS: You say this is simple for us to repro, but remember, we need to setup a new project collection, update our process template to match your state model, or update the rule to match our model, setup multiple work items with the correct state and then figure out what triggers the rule. It's not as simple as it sounds. It would take me at least an hour to setup and verify the behavior.

**Comment by helhaddad** [comment]
My Project is Project 1 with space, in the rule the project name is project 1

**Comment by helhaddad** [comment]
This was a problem in my rule sorry.

**Comment by giuliov** [comment]
I will check a night of those, no ETA.

**Comment by jessehouwing** [comment]
Glad you've found them and hopefully you now have improved skills in debugging your rules and making them better.
