### ISSUE TITLE
Refresh the navigator each time we make a change in the state of a work

### ISSUE THREAD

**Issue by helhaddad** [tfsaggregator/tfsaggregator#186]
Hello,
When we added the auto state transition it requires to refresh the navigator each time we make a change in the state of a work item to see the automatic state transition of the user story or the dev task – it's very annoying and sometimes users forget to refresh after every action, please can we cancel the refresh action , we want to see the state updates immediately without refreshing it every time ?

**Comment by giuliov** [comment]
Is this the same as #183? Can you read that thread and confirm or state the differences?
