### ISSUE TITLE
User story automatically located in the right swimlane

### ISSUE THREAD

**Issue by helhaddad** [tfsaggregator/tfsaggregator#187]
Can i implement that when a new User story is entered to work it will be automatically located in the right swimlane according to a field X ?

**Comment by jessehouwing** [comment]
No, swim lines are team specific and the tfs Aggregator doesn't have the
context of the team that was used to effect the change. Without that
context it's not possible to set the things that are added through board
customization such as custom kanban columns and swimlanes.

**Comment by helhaddad** [comment]
Thank you for your response Jesse
