### ISSUE TITLE
Changes made by rules don't get saved.

### ISSUE THREAD

**Issue by SAnCherepan** [tfsaggregator/tfsaggregator#188]
Hi everyone!

The issue I've encountered is the fact that the plugin cannot apply the changes it made during the rules execution.

I'll go ahead and describe it step by step.
--------------
Prerequisites.
There is a Feature (WITD: [feature.xml.txt](https://github.com/tfsaggregator/tfsaggregator/files/564322/feature.xml.txt)
), and it has a child Task.

And there is a set of rules to handle them ([TFSAggregator2.ServerPlugin-copy.policies.txt](https://github.com/tfsaggregator/tfsaggregator/files/564326/TFSAggregator2.ServerPlugin-copy.policies.txt)).

There are 3 rules that sum scheduling fields (Original Estimate, Remaining Work and Completed Work) for a Feature from all children tasks.
They are called Check_* rules.

There are also 3 rules that push the difference in a field from a Task to parent Feature (if one happened, of course).
They are called *_Calc rules.

All of them (AFAIK) are made in accordance with your code samples from github.

The remaining 3 rules are:
1) compute the custom field value based on scheduling values (ProgressPercentCalc);
2) change the state of the Feature according to that value (Feature_Status_Update);
3) change some field values when you change the dropdown value to a certain one (test rule).

-----------
Scenario:

Create a Feature and fill in all the necessary fields.
Create a child Task and fill it aswell (here you can fill the Remaining Work and Completed Work), so the plugin can compute the progress field.
Feature scheduling fields get updated, progress field gets updated too and the state moves from "New" to "Assigned" (if the progress is less than 10%). The Accepted By field gets filled just fine.
You keep on working on the child Task, so the progress gets past 10%.

All of that works just fine.

The scheduling fields on parent Feature get updated (they really do), the progress field does NOT get updated and the Feature does NOT move to In Progress and Activated By does NOT get updated.

If you manually move the feature to In Progress and see, how the progress field suddenly gets updated by the plugin again.

----------
Testing.
So I created a test rule to see in which states it does not update the Feature's fields.
It worked in all the states except the Assigned one.
Note that *_Calc rules (that trigger on the child's side) are still able to update the parent's fields.

You can see there is logging in the rules. 
And it says that the fields actually get updated every time, even in the Assigned state (values preserve between different rules during a single transaction).
But they don't get saved after transation completes, the values on the web are all the same.

The service account has Project Collection Administrator rights, so the permissions are unlikely to be an issue.
Unless I am completely blind, there are no limitations on either of the fields.
Both transitions (New -> Assigned and Assigned -> In Progress) are valid.
There is one field that's required to be filled in one of the transitions, but I filled it every time during the Feature creation during the testing process.

And yes, there are more Aggregator rules in production, but these ones have been isolated and tested on a cloned server.

----------
Question.
Is there something I've totally missed out on, or could it be some sort of a plugin-side bug?

Thank you for your time and effort!

**Comment by giuliov** [comment]
An exemplary report, very good.

Sounds like one of those catch-22 scenario, but I to read it in the entirety to be sure and reply properly, which I will do tonight.

**Comment by giuliov** [comment]
@SAnCherepan you shared lot of static information, but no log or trace that would help understand the issue; see the [Troubleshooting](https://github.com/tfsaggregator/tfsaggregator/wiki/Troubleshooting) page for suggestions.

A few things in your rules looks suspicious, maybe they are related.

1. Line 254 of **ProgressPercentCalc** rule could be missing a couple of parenthesis around the or (`||`) operator. The and (`&&`) operator has precedence and the expression will be read as `if ( (WorkItemType == Feature" && State == Closed) || State == Completed" ) { ... } `
2. In line 218 of **MyProject3_Feature_Status_Update** rule, you set the work item state, I suggest adopt [`TransitionToState`](https://github.com/tfsaggregator/tfsaggregator/wiki/Auto-Open-Auto-Close) helper
3. In the same rule, lines 212 and 222, the code assigns a user; I was not able to find a reference but I remember that TFS is picky on the acceptable value
4. Log the value returned by [`IsValid()`](https://github.com/tfsaggregator/tfsaggregator/wiki/self-Object) before exiting a rule, so you can see if some value is unacceptable by the underlying work item type.

Hope this helps.

**Comment by SAnCherepan** [comment]
@giuliov thank you for your reply!

Cutting sensitive info from logs is a bit more complicated procedure, so I decided to start with the static info.
And it proved to be just enough to let you provide the right guidance, it really did help!

About these suspicious things.

1. It works exactly as intended, because the Feature's last State (Closed) differs from the Task's one (Completed).

2. That appeared not to be an issue, workflow transitions that I handle via Aggregator are all one-step and they are all verified not to have any constraints fieldwise.
Still, the method looks pretty useful, especially if it can travel through multiple states (assuming no field restrictions), so thank you for mentioning it.

3. The reference you are looking for is probably the issue #159. I used the parsing method, proposed by @ASolovyev to get the full display name.
It was exactly the source of this current problem. 
Replacing
`var name = (string)self["System.AssignedTo"];`
`name = name.Substring(0, name.LastIndexOf(' '));`
`self["Microsoft.VSTS.CodeReview.AcceptedBy"] = name;`
with
`self["Microsoft.VSTS.CodeReview.AcceptedBy"] = self["System.AssignedTo"];`
solved the problem for me.
The reason I didn't pay attention to it earlier is that I used Admin <DOMAIN\Admin> (which has no last name) as a testing account.

4. The method is really useful for debugging, I will keep that one in mind. 

P.S.: Just to clarify: the changes made by all the rules after the WI is changed are made in one go, right?
That would explain why the progress field calculated in another rule did not get saved either (due to invalid changes made to WI later), but the changes made during the child handling did go live.

**Comment by giuliov** [comment]
Almost.

On the event raised by TFS, Aggregator loads the workitem, applies all matching rules (which may load more work items), and when finished saves all modified workitem in one fell swoop.
**There is one exception** to this: the `TransitionToState` helper. If transitioning from source state to the target state requires intermediate states, the workitem is saved at each partial transition.

**Comment by SAnCherepan** [comment]
Thank you very much for your detailed answers!
