### ISSUE TITLE
The work item does not exist, or you do not have permission to access it. 

### ISSUE THREAD

**Issue by helhaddad** [tfsaggregator/tfsaggregator#189]
When I delete a Work Item from the Kanban Board the tfsaggregator write this error in the even viewer

The description for Event ID 47513 from source TFSAggregator cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Exception encountered processing notification: **TF26198: The work item does not exist, or you do not have permission to access it.** 
Stack Trace:   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.LoadWorkItemFromRowSetInternal(Int32 rev, Nullable`1 asof, IWorkItemRowSets witem)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem..ctor(WorkItemStore store, Int32 id)
   at Aggregator.Core.Facade.WorkItemRepository.GetWorkItem(Int32 workItemId)
   at Aggregator.Core.EventProcessor.ProcessEvent(IRequestContext requestContext, INotification notification)
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties)

the message resource is present but the message is not found in the string/message table

**Comment by giuliov** [comment]
This is a known issue (see #176): deleting work items is a recent feature and I remember implementing support for the feature and testing it, but not of a release.

**Comment by deka** [comment]
I think it's an important issue, 
When end user delete item from web access rollups are not processed  !
Ideas about workaround ?

**Comment by giuliov** [comment]
This is already available in the develop branch. Starting next week I should have some time to dedicate to this project and wrap up some loose strings.

**Comment by jdshkolnik** [comment]
How to handle a rollup on delete? I would want that event to re-aggregate that deleted item's parent's other children.
