### ISSUE TITLE
Configuration auto-refresh for TFS farms

### ISSUE THREAD

**Issue by giuliov** [tfsaggregator/tfsaggregator#19]
Configuration is stored in TFVC monitored by the plugin, which refreshes the local configuration file when it changes, simplifying farm administration

**Comment by jessehouwing** [comment]
I'd love to move the existing config file to a true .NET TfsAgggregator.dll.config and use the configsections in there for a true typed experience. Possibly based on: https://csd.codeplex.com/ which I used in the past with success.

**Comment by giuliov** [comment]
Design sketch:
 - configuration file (not the policy)
   * TFS Collection to monitor
   * version control path (TFVC)
   * polling interval
 - updated policy file is pulled down just-in-time

This feature goes hand-in-hand with #22.

**Comment by giuliov** [comment]
Last night I dreamed of using custom work item to describe the policy, which could be great for delegation.

Sketch:
 * define Policy and Rule work item types
 * configuration file (not the policy)
   - Collection, Project and Query to monitor
   - polling interval
 * build policy in-memory
 * extend install script to deploy custom work item types
