### ISSUE TITLE
TFS2015 Update 3 TFSAggregator not working

### ISSUE THREAD

**Issue by swtrse** [tfsaggregator/tfsaggregator#192]
Hi,

I have a little problem. On my Dev machine all is working fine. But on the production environment TFSAggregator does not work. I checked for errors via DebugView an got this error message, but I have no idea how to solve this.
`00000416	193.58038330	[10300] TfsAggregator.ServerPlugin Information: 41545 : 	
00000418	193.58088684	[10300] TFSAggregator: [Information] Aggregator.Core started, version: 2.1.203-master, build: 2.1.203, configuration: Release [TFS 2015.2] 	
00000419	193.60417175	[10300] TfsAggregator.ServerPlugin Information: 50532 : 	
00000420	193.60420227	[10300] Configuration loaded successfully from 'C:\Program Files\Microsoft Team Foundation Server 14.0\Application Tier\Web Services\bin\Plugins\TFSAggregator2.ServerPlugin.policies' 	
00000421	193.60424805	[10300] TFSAggregator: [Information] Configuration loaded successfully from 'C:\Program Files\Microsoft Team Foundation Server 14.0\Application Tier\Web Services\bin\Plugins\TFSAggregator2.ServerPlugin.policies' 	
00000422	194.40121460	[10300] TfsAggregator.ServerPlugin Critical: 17114 : 	
00000442	194.40130615	[10300]    at Aggregator.Core.Facade.WorkItemRepository..ctor(Uri tfsCollectionUri, IdentityDescriptor toImpersonate, IRuntimeContext context) in C:\projects\tfsaggregator\Aggregator.Core\Facade\WorkItemRepository.cs:line 42 	
00000443	194.40130615	[10300]    at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.<>c.<ProcessEvent>b__2_0(Uri collectionUri, IdentityDescriptor toImpersonate, IRuntimeContext runtimeContext) in C:\projects\tfsaggregator\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 68 	
00000444	194.40130615	[10300]    at Aggregator.Core.Context.RuntimeContext.CreateWorkItemRepository() in C:\projects\tfsaggregator\Aggregator.Core\Context\RuntimeContext.cs:line 170 	
00000445	194.40130615	[10300]    at Aggregator.Core.Context.RuntimeContext.get_WorkItemRepository() in C:\projects\tfsaggregator\Aggregator.Core\Context\RuntimeContext.cs:line 183 	
00000446	194.40130615	[10300]    at Aggregator.Core.EventProcessor..ctor(IRuntimeContext runtime) in C:\projects\tfsaggregator\Aggregator.Core\EventProcessor.cs:line 40 	
00000447	194.40130615	[10300]    at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in C:\projects\tfsaggregator\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 84	
00000451	194.40139771	[10300] TFSAggregator: [Critical]    Exception encountered processing notification: Please contact your administrator. There was an error contacting the server. 	
00000470	194.40139771	[10300]    at Aggregator.Core.Facade.WorkItemRepository..ctor(Uri tfsCollectionUri, IdentityDescriptor toImpersonate, IRuntimeContext context) in C:\projects\tfsaggregator\Aggregator.Core\Facade\WorkItemRepository.cs:line 42 	
00000471	194.40139771	[10300]    at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.<>c.<ProcessEvent>b__2_0(Uri collectionUri, IdentityDescriptor toImpersonate, IRuntimeContext runtimeContext) in C:\projects\tfsaggregator\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 68 	
00000472	194.40139771	[10300]    at Aggregator.Core.Context.RuntimeContext.CreateWorkItemRepository() in C:\projects\tfsaggregator\Aggregator.Core\Context\RuntimeContext.cs:line 170 	
00000473	194.40139771	[10300]    at Aggregator.Core.Context.RuntimeContext.get_WorkItemRepository() in C:\projects\tfsaggregator\Aggregator.Core\Context\RuntimeContext.cs:line 183 	
00000474	194.40139771	[10300]    at Aggregator.Core.EventProcessor..ctor(IRuntimeContext runtime) in C:\projects\tfsaggregator\Aggregator.Core\EventProcessor.cs:line 40 	
00000475	194.40139771	[10300]    at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in C:\projects\tfsaggregator\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 84	
00000479	194.43350220	[10300] TfsAggregator.ServerPlugin Critical: 17114 : 	
00000499	194.43357849	[10300]    at Aggregator.Core.Facade.WorkItemRepository..ctor(Uri tfsCollectionUri, IdentityDescriptor toImpersonate, IRuntimeContext context) in C:\projects\tfsaggregator\Aggregator.Core\Facade\WorkItemRepository.cs:line 42 	
00000500	194.43357849	[10300]    at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.<>c.<ProcessEvent>b__2_0(Uri collectionUri, IdentityDescriptor toImpersonate, IRuntimeContext runtimeContext) in C:\projects\tfsaggregator\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 68 	
00000501	194.43357849	[10300]    at Aggregator.Core.Context.RuntimeContext.CreateWorkItemRepository() in C:\projects\tfsaggregator\Aggregator.Core\Context\RuntimeContext.cs:line 170 	
00000502	194.43357849	[10300]    at Aggregator.Core.Context.RuntimeContext.get_WorkItemRepository() in C:\projects\tfsaggregator\Aggregator.Core\Context\RuntimeContext.cs:line 183 	
00000503	194.43357849	[10300]    at Aggregator.Core.EventProcessor..ctor(IRuntimeContext runtime) in C:\projects\tfsaggregator\Aggregator.Core\EventProcessor.cs:line 40 	
00000504	194.43357849	[10300]    at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in C:\projects\tfsaggregator\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 84	
00000508	194.43368530	[10300] TFSAggregator: [Critical]    Exception encountered processing notification: Please contact your administrator. There was an error contacting the server. 	
00000527	194.43368530	[10300]    at Aggregator.Core.Facade.WorkItemRepository..ctor(Uri tfsCollectionUri, IdentityDescriptor toImpersonate, IRuntimeContext context) in C:\projects\tfsaggregator\Aggregator.Core\Facade\WorkItemRepository.cs:line 42 	
00000528	194.43368530	[10300]    at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.<>c.<ProcessEvent>b__2_0(Uri collectionUri, IdentityDescriptor toImpersonate, IRuntimeContext runtimeContext) in C:\projects\tfsaggregator\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 68 	
00000529	194.43368530	[10300]    at Aggregator.Core.Context.RuntimeContext.CreateWorkItemRepository() in C:\projects\tfsaggregator\Aggregator.Core\Context\RuntimeContext.cs:line 170 	
00000530	194.43368530	[10300]    at Aggregator.Core.Context.RuntimeContext.get_WorkItemRepository() in C:\projects\tfsaggregator\Aggregator.Core\Context\RuntimeContext.cs:line 183 	
00000531	194.43368530	[10300]    at Aggregator.Core.EventProcessor..ctor(IRuntimeContext runtime) in C:\projects\tfsaggregator\Aggregator.Core\EventProcessor.cs:line 40 	
00000532	194.43368530	[10300]    at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in C:\projects\tfsaggregator\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 84	`

**Comment by swtrse** [comment]
Here is the log as file I think that makes it mire readable
[Log.txt](https://github.com/tfsaggregator/tfsaggregator/files/599355/Log.txt)

**Comment by giuliov** [comment]
Check the permission of TFS service account (see also [Troubleshooting](https://github.com/tfsaggregator/tfsaggregator/wiki/Troubleshooting)) or use impersonation.

**Comment by swtrse** [comment]
@giuliov You are correct. It where the permissions. I don't know why they have changed but know TFS Aggregator is back again.
