### ISSUE TITLE
Trigger an aggregator rule on previously closed work items

### ISSUE THREAD

**Issue by einar20** [tfsaggregator/tfsaggregator#193]
I have created different aggregator scripts, that updates information in other linked work items.
 My scripts works fine, and does their magic :satisfied:

However, the updates performed, off course only applies to those work items saved after I created these scripts and customizations to wit's. Work items created earlier, does not have these aggregated information.

Is there a way to trigger an aggregator rule on previously closed work items, without opening them and save?

I could off course use the console app on server, but as far as I have understood, I would then have to peform these action on the work items one by one. Having approx 250 parent items created before the aggregator scripts were installed, that is not a very tempting task to start on :)

**Comment by giuliov** [comment]
@einar20 you are almost there.
The console app is the solution we have at hand, but you have to pick release https://github.com/tfsaggregator/tfsaggregator/releases/tag/v2.2.0-rc.1 which includes feature #178.

**Comment by giuliov** [comment]
Forgot to say that now you can install the client app separately (feature #170) and run it from any client.

**Comment by einar20** [comment]
@giuliov thanks for your fast and helpful advise.
That is excactly the kind of feature needed :-)
I'll give it a try!
