### ISSUE TITLE
TFS 2017 support

### ISSUE THREAD

**Issue by tomkuijsten** [tfsaggregator/tfsaggregator#195]
Will you support TFS 2017?

According to the [documentation](https://www.visualstudio.com/en-us/news/releasenotes/tfs2017-relnotes#a-idknownissues-aknown-issues), you should recompile again the 2017 assemblies:

_Custom TFS server plugins need to be rebuilt against TFS 2017 DLLs
•Issue:
Custom TFS server plugins do not work after upgrading to TFS 2017.
•Workaround:
Rebuild your custom server plugins against the TFS 2017 assemblies._

**Comment by giuliov** [comment]
You missed the announce for [2.2 RC 1](https://github.com/tfsaggregator/tfsaggregator/releases/tag/v2.2.0-rc.1).
Please test and give us feedback.

**Comment by dasMulli** [comment]
Works on my (production) machine 😄 👍 
No super-complex rules though (just copying custom fields to new child items, activate / resolve hierarchy)

**Comment by tomkuijsten** [comment]
My bad, I saw the readme on the master branh which didn't mention 2017 yet.
