### ISSUE TITLE
Not sure why these are not working??? Any help would be greatly appreciated.

### ISSUE THREAD

**Issue by jkuroski** [tfsaggregator/tfsaggregator#197]
```
<rule name="RollDownIterationPath1" appliesTo="Product Backlog Item" hasFields="System.IterationPath"><![CDATA[
    foreach (var child in self.Children)
    {
        if (child.TypeName == "Task" && (child["System.State"] == "In Progress" || child["System.State"] == "In QA" || child["System.State"] == "To Do"))
        {
            child["System.IterationPath"] = self["System.IterationPath"];
        }
    }
]]>
</rule>
<rule name="RollDownIterationPath2" appliesTo="Bug" hasFields="System.IterationPath"><![CDATA[
    foreach (var child in self.Children)
    {
        if (child.TypeName == "Task" && (child["System.State"] == "In Progress" || child["System.State"] == "In QA" || child["System.State"] == "To Do"))
        {
            child["System.IterationPath"] = self["System.IterationPath"];
        }
    }
]]>
</rule>
```

**Comment by jkuroski** [comment]
`<rule name="RollDownIterationPath1" appliesTo="Product Backlog Item" hasFields="System.IterationPath"><![CDATA[
        foreach (var child in self.Children)
        {
          if (child.TypeName == "Task" && (child["System.State"] == "In Progress" || child["System.State"] == "In QA" || child["System.State"] == "To Do"))
          {
            child["System.IterationPath"] = self["System.IterationPath"];
          }
        }
        ]]>
  	</rule>
  	<rule name="RollDownIterationPath2" appliesTo="Bug" hasFields="System.IterationPath"><![CDATA[
        foreach (var child in self.Children)
        {
          if (child.TypeName == "Task" && (child["System.State"] == "In Progress" || child["System.State"] == "In QA" || child["System.State"] == "To Do"))
          {
            child["System.IterationPath"] = self["System.IterationPath"];
          }
        }
        ]]>
  	</rule>`

**Comment by giuliov** [comment]
They looks good at face value.
It would be very useful to test them using the [Console app](https://github.com/tfsaggregator/tfsaggregator/wiki/Console-App) and see what appears in the log; you should also take a look at the [Troubleshooting](https://github.com/tfsaggregator/tfsaggregator/wiki/Troubleshooting) page for suggestions.

**Comment by jkuroski** [comment]
Everything seems to work, but it doesn't update the child records.

C:\Program Files\TFS Aggregator\bin>tfsaggregator2.consoleapp -fTFSAggregator2.S
erverPlugin.policies -chttp://localhost:8080/tfs/visionweb -pTransitions -n20748
 -ldiagnostic
Aggregator.ConsoleApp 2.0.138-master
Console tool to test TFS Aggregator polices
Build: 2.0.138, Configuration: Debug
Copyright (c) TFS Aggregator Team 2015

Executing run (Applies a policy file to specified work item(s)):

[Information] 00.005 Aggregator.Core started, version: 2.0.138-master, build: 2.
0.138, configuration: Debug
[Information] 00.030 Configuration loaded successfully from 'C:\Program Files\TF
S Aggregator\bin\TFSAggregator2.ServerPlugin.policies'
[Diagnostic]  00.212 Built a new Work Item Repository for http://localhost:8080/
tfs/visionweb
[Verbose]     00.213 Building Script Engine for C#
[Information] 00.528 Starting processing on workitem #20748
[Diagnostic]  00.687 Policy scope Collections(visionweb) matches VisionWeb
[Diagnostic]  00.688 Policy scope Projects(Transitions) matches Transitions
[Verbose]     00.756 Policy 'DefaultPolicy' applies
[Verbose]     00.757 Evaluating Rule 'RollupTask'
[Diagnostic]  00.758 Rule scope WorkItemTypes(Task) does not match Product Backl
og Item
[Verbose]     00.758 Evaluating Rule 'RollDownIterationPath1'
[Diagnostic]  00.758 Rule scope WorkItemTypes(Product Backlog Item) matches Prod
uct Backlog Item
[Verbose]     00.758 Applying Rule 'RollDownIterationPath1' on #20748
[Diagnostic]  00.886 Output from script 'RollDownIterationPath1': []
[Verbose]     00.886 Evaluating Rule 'RollDownIterationPath2'
[Diagnostic]  00.886 Rule scope WorkItemTypes(Bug) does not match Product Backlo
g Item
[Information] 00.887 Processing completed: Success
Succeeded.

**Comment by jessehouwing** [comment]
Stupid question maybe, but do they ready have the correct value?

**Comment by jkuroski** [comment]
I can't seem to get any of the child field values other tag child.Typename,
so it isn't entering the loop.

**Comment by giuliov** [comment]
`Build: 2.0.138` is a year old, better upgrade to 2.1.1 or even 2.2 RC1, but I think the issue is the `==` operator on the field value.

If you see [here](https://github.com/tfsaggregator/tfsaggregator/wiki/self-Object#fields-collection), we suggests to cast the value, like in [this example](https://github.com/tfsaggregator/tfsaggregator/wiki/Auto-Open-Auto-Close). In your case something like

```
string childState = child["System.State"].ToString();
if (child.TypeName == "Task" && (childState == "In Progress" || childState == "In QA" || childState == "To Do"))
{
    child["System.IterationPath"] = self["System.IterationPath"];
}
```

**Comment by jkuroski** [comment]
That was it apparently... Thanks giuliov
