### ISSUE TITLE
TFS 2017 : Refresh the navigator each time we make a change in the state of a work

### ISSUE THREAD

**Issue by helhaddad** [tfsaggregator/tfsaggregator#200]
Hi,

Refresh the navigator each time we make a change in the state of a work, it can be done in the new TFS 2017 please?

If yes it's provided in the new version 2.3 of Aggregator?

It's possible to tell us the release date of the new version V2.3 of Aggregator?

Thank you very much for your answer

**Comment by jessehouwing** [comment]
No the Aggregator can't solve this. This needs to be implemented by the
product team on the work item form. I suggest you file a feature request on
the visual Studio user voice.

**Comment by giuliov** [comment]
@helhaddad the plan is to promote 2.2 RC to RTM in the next couple of weeks; 2.3 requires more testing and polishing, but the focus for 2.3 is supporting WebHooks/VSTS, no more. What you are looking for?
