### ISSUE TITLE
Configurazione TFSAggregator2.ServerPlugin.policies

### ISSUE THREAD

**Issue by passgab** [tfsaggregator/tfsaggregator#201]
Ciao, non riesco a far funzionare TFS Aggregator con template diversi da Scrum malgrado abbia replicato i file con i nomi della collection e template corretti.
Successivamente ho notato, utilizzando Scrum, che devo sempre eseguire la Console App affinché vengano recepite le modifiche del cambio stato e non viene memorizzato automaticamente. Cosa mi manca da configurare????
Grazie Gabriele

**Comment by giuliov** [comment]
Per aiutarti dovremo vedere le regole che usi; intanto ti suggerisco di verificare su [Work item field index](https://www.visualstudio.com/en-us/docs/work/guidance/work-item-field) se i campi che usi sono definiti nel template impiegato dal progetto.

Quanto al cambio di stato dipende cosa intendi: spostare un work item da un colonna ad un altra in una Board cambia il campo `System.BoardColumn`, ma  puo' lasciare invariato il campo `System.State`. Di nuovo servirebbe vedere le regole come suggerito alla pagina [Troubleshooting](https://github.com/tfsaggregator/tfsaggregator/wiki/Troubleshooting#support).

Un ultimo consiglio: se possibile usare l'inglese su GitHub.

**Comment by passgab** [comment]
Hi Giulio, We have customized the files Policies ( "TFSAggregator2.ServerPlugin.policies") with the data of our collection and our template CUSTOM but we can not make the switch to automatic status as our custom template does not have the value of the member of Default work item (eg. Active, Done, Close ...) How can we also correctly configure the states of our work item? Furthermore, our need is to automatically change the status of a work item type child when his father was changing and not the other. Thanks Gabriele

**Comment by giuliov** [comment]
@passgab see [Auto-Open, Auto-Close](https://tfsaggregator.github.io/using/examples/Auto-Open-Auto-Close/) for some examples of managing state. `TransitionToState` is useful to change work items' state see #9.
[Fluent Queries](https://tfsaggregator.github.io/using/objects-reference/self-Object/#fluent-queries) may help in finding children and parents.

Use the [Console](https://tfsaggregator.github.io/admin/console-app/) to quickly test Rules.
