### ISSUE TITLE
TFS 2017 Console Works, but not from the App

### ISSUE THREAD

**Issue by jkuroski** [tfsaggregator/tfsaggregator#204]
Wondering what I'm missing here. Ran the installer and I see the .pdb and .dll files in C:\Program Files\Microsoft Team Foundation Server 15.0\Application Tier\Web Services\bin\Plugins but nothing fires from the web interface of TFS.

**Comment by giuliov** [comment]
Can you check if the suggestions in issue #199 may apply?
Have you followed the steps in [troubleshooting](https://tfsaggregator.github.io/admin/troubleshooting/) page?

**Comment by jkuroski** [comment]
*This is a new installation of 2017 on a fresh server, so I do not believe
it is related to #199.*

*DLLs and POLICIES file present.*

[image: Inline image 1]

*I am using this Service Account with proper Permissions: *
[image: Inline image 2]

*Command line works:*

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

H:\>c:

C:\>cd program files/tfs aggregator/bin

C:\Program Files\TFS Aggregator\bin>tfsaggregator2.consoleapp.exe
-fTFSAggregator2.ServerPlugin.policies -chttp://CORPTFS:8080/tfs/visionweb
-pTransitions -n29289 -ldiagnostic
Aggregator.ConsoleApp 2.2-alpha
Console tool to test TFS Aggregator polices
Build: 2.2.0.0, Configuration: Release [TFS 2017.0]
Copyright (c) TFS Aggregator Team 2015-16

Executing run (Applies a policy file to specified work item(s)):

[Information] 00.263 Aggregator.Core started, version: 2.2-alpha, build:
2.2.0.0, configuration: Release [TFS 2017.0]
[Information] 00.606 Configuration loaded successfully from 'C:\Program
Files\TFS Aggregator\bin\TFSAggregator2.ServerPlugin.policies'
[Verbose]     00.635 Connecting to http://corptfs:8080/tfs/visionweb as
jkuroski
[Diagnostic]  22.688 Built a new Work Item Repository for
http://corptfs:8080/tfs/visionweb
[Verbose]     22.697 Building Script Engine for C#
[Information] 25.433 Starting processing on workitem #29289
[Diagnostic]  25.995 Policy scope Collections(visionweb) matches VisionWeb
[Diagnostic]  25.996 Policy scope Projects(Transitions) matches Transitions
[Verbose]     26.792 Policy 'DefaultPolicy' applies
[Verbose]     26.792 Evaluating Rule 'RollupTask'
[Diagnostic]  26.799 Rule scope WorkItemTypes(Task) matches Task
[Verbose]     26.800 Applying Rule 'RollupTask' on #29289
[Diagnostic]  27.018 Output from script 'RollupTask': []
[Verbose]     27.018 Evaluating Rule 'RollupBug'
[Diagnostic]  27.018 Rule scope WorkItemTypes(Bug) does not match Task
[Verbose]     27.018 Evaluating Rule 'RollupPBI'
[Diagnostic]  27.018 Rule scope WorkItemTypes(Product Backlog Item) does
not match Task
[Verbose]     27.018 Evaluating Rule 'RollDownIterationPath1'
[Diagnostic]  27.018 Rule scope WorkItemTypes(Product Backlog Item) does
not match Task
[Verbose]     27.018 Evaluating Rule 'RollDownIterationPath2'
[Diagnostic]  27.018 Rule scope WorkItemTypes(Bug) does not match Task
[Verbose]     27.028 Bug [29286] is valid to save.
[Information] 28.645 Processing completed: Success
[Information] 28.679 Starting processing on workitem #29286
[Diagnostic]  28.679 Policy scope Collections(visionweb) matches VisionWeb
[Diagnostic]  28.679 Policy scope Projects(Transitions) matches Transitions
[Verbose]     28.679 Policy 'DefaultPolicy' applies
[Verbose]     28.679 Evaluating Rule 'RollupTask'
[Diagnostic]  28.679 Rule scope WorkItemTypes(Task) does not match Bug
[Verbose]     28.679 Evaluating Rule 'RollupBug'
[Diagnostic]  28.679 Rule scope WorkItemTypes(Bug) matches Bug
[Verbose]     28.679 Applying Rule 'RollupBug' on #29286
[Diagnostic]  28.682 Output from script 'RollupBug': []
[Verbose]     28.682 Evaluating Rule 'RollupPBI'
[Diagnostic]  28.682 Rule scope WorkItemTypes(Product Backlog Item) does
not match Bug
[Verbose]     28.682 Evaluating Rule 'RollDownIterationPath1'
[Diagnostic]  28.682 Rule scope WorkItemTypes(Product Backlog Item) does
not match Bug
[Verbose]     28.682 Evaluating Rule 'RollDownIterationPath2'
[Diagnostic]  28.682 Rule scope WorkItemTypes(Bug) matches Bug
[Verbose]     28.682 Applying Rule 'RollDownIterationPath2' on #29286
[Diagnostic]  28.684 Output from script 'RollDownIterationPath2': []
[Information] 28.684 Processing completed: Success
Succeeded.

I am getting nothing in DebugView for *TFSAggregator*

**Comment by jkuroski** [comment]
Apologies forgot to turn on GlobalWin32

[1084] TFSAggregator: [Critical]    Exception encountered processing
notification: TF400324: Team Foundation services are not available from
server https://tfs.visionweb.com/tfs/VisionWeb/.

We have not created tfs.visionweb.com yet in our DNS. I suspect that's the
issue.

**Comment by giuliov** [comment]
Makes sense, furthermore you should have errors in three Event log

**Comment by giuliov** [comment]
Try adding the DNS name to hosts file, just to validate the finding.

**Comment by jkuroski** [comment]
That was it. Thanks for your help.
