### ISSUE TITLE
ConsoleApp shows version 2.2.0-alpha in 2.2 release

### ISSUE THREAD

**Issue by martinh2011** [tfsaggregator/tfsaggregator#207]
1 Install 2.2 on TFS 2015.2
2. Open Command or PowerShell prompt
3. Run TFSAggregator2.ConsoleApp.exe

App shows:

> Aggregator.ConsoleApp 2.2-**alpha**
> Console tool to test TFS Aggregator polices
> Build: 2.2.0.0, Configuration: Release [TFS 2015.2]
> Copyright (c) TFS Aggregator Team 2015-16

There should be no "alpha" in a released build, shouldn't it?

**Comment by giuliov** [comment]
Nice catch: it seems that the new build has not overwritten the version number. I will look into it the next days.

**Comment by giuliov** [comment]
It is fixed now: you have to re-download the MSI though.
