### ISSUE TITLE
Method not found exception 

### ISSUE THREAD

**Issue by martinh2011** [tfsaggregator/tfsaggregator#208]
- TFS 2015.2
- TfsAggregator 2.2.0 release
- Only the sample "MyFirstRule" rule is active
- When TFS triggers I always get this:

> TfsAggregator.ServerPlugin	Information	41545	Aggregator.Core started, version: 2.2.0+Branch.master.Sha.aad3cd6c88a88df370c91831053c656244be247c, build: 2.2.0.0, configuration: Release [TFS 2015.2]
> TfsAggregator.ServerPlugin	Information	50532	Configuration loaded successfully from 'D:\Microsoft Team Foundation Server 14.0\Application Tier\Web Services\bin\Plugins\TFSAggregator2.ServerPlugin.policies'
> TfsAggregator.ServerPlugin	Critical	47513	Exception encountered processing notification: Method not found: '!!0[] System.Array.Empty()'. 
> Stack Trace:   at Aggregator.Core.Monitoring.TextLogComposer.Connecting(ConnectionInfo ci)
>    at Aggregator.Core.Facade.WorkItemRepository..ctor(IRuntimeContext context) in D:\a\1\s\Aggregator.Core\Facade\WorkItemRepository.cs:line 42
>    at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.<>c.<ProcessEvent>b__2_0(IRuntimeContext runtimeContext) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 67
>    at Aggregator.Core.Context.RuntimeContext.CreateWorkItemRepository() in D:\a\1\s\Aggregator.Core\Context\RuntimeContext.cs:line 219
>    at Aggregator.Core.Context.RuntimeContext.get_WorkItemRepository() in D:\a\1\s\Aggregator.Core\Context\RuntimeContext.cs:line 233
>    at Aggregator.Core.EventProcessor..ctor(IRuntimeContext runtime) in D:\a\1\s\Aggregator.Core\EventProcessor.cs:line 40
>    at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 84

**Comment by giuliov** [comment]
Weird, I started looking into this but it will take time

**Comment by jessehouwing** [comment]
Looks related to this one: 

https://connect.microsoft.com/VisualStudio/feedback/details/1097462/missingmethodexception-additional-information-method-not-found-0-system-array-empty

**Comment by giuliov** [comment]
@jessehouwing you are probably right, somehow the target framework is 4.6.1 on master. I will fix this and do a full regression in the next days.

**Comment by jessehouwing** [comment]
It needs to be 4.6.1 for tfs 2017...

**Comment by giuliov** [comment]
@martinh2011 can you test [release 2.2.1](https://github.com/tfsaggregator/tfsaggregator/releases/tag/v2.2.1)? Hopefully I found the root causes and solutions for this and #207.

**Comment by martinh2011** [comment]
Works. 👍
