### ISSUE TITLE
Can i delete WorkItemLink by tfsaggregator

### ISSUE THREAD

**Issue by helhaddad** [tfsaggregator/tfsaggregator#210]
Hi,

Can i delete WorkItemLink by tfsaggregator?

Thanks in advance

Best regards

**Comment by jessehouwing** [comment]
Currently not supported. Seems like it could be a small change in the WorkItemLinkCollectionWrapper class to support it. Pull requests are appreciated. The change would have to go through TFSAggregator-Core: https://github.com/tfsaggregator/tfsaggregator-core/tree/master/Facade

**Comment by helhaddad** [comment]
Hi,

THanks for your response, can you please explaine me more.

I don't now what can i do to add this function to aggregator

Thanks in advance for your help

**Comment by giuliov** [comment]
Can you try
https://github.com/tfsaggregator/tfsaggregator/releases/tag/v2.3-beta.2 ?

**Comment by helhaddad** [comment]
Can you please give me a sample how to use the function RemoveWorkItemLink

self.RemoveWorkItemLink(WorkItemImplementationBase.ChildRelationship);

thanks in advanced

**Comment by giuliov** [comment]
Look in the docs at https://tfsaggregator.github.io/using/objects-reference/self-object/#removeworkitemlink-method-v2-3

**Comment by helhaddad** [comment]
THanks for your response, 

My rule in the policie file is':'

	<rule name="RemoveLink" appliesTo="Bug">
        <![CDATA[
			IWorkItemLinkExposed link = WorkItemImplementationBase.ChildRelationship;
			self.RemoveWorkItemLink(link);
        ]]>

i receive this error ':'

17.021 Error CS0029 in script ''RemoveLink'' at line 4, column 32: Cannot implicitly convert type 'string' to 'Aggregator.Core.Interfaces.IWorkItemLinkExposed'

Can you help me please?

**Comment by giuliov** [comment]
Just follow the sample in the doc: iterate the links and remove the one

```
foreach (var link in self.WorkItemLinks) {
   if (link.LinkTypeEndImmutableName == WorkItemImplementationBase.ChildRelationship) {
       self.RemoveWorkItemLink(link);
       break;
   }
}
```

Note that you must exit the loop: if you want to remove more then one link you should queue them for subsequent removal:

```
var linksToRemove = new List<IWorkItemLinkExposed>();
foreach (var link in self.WorkItemLinks) {
   if (link.LinkTypeEndImmutableName == WorkItemImplementationBase.ChildRelationship) {
       linksToRemove.Add(link);
   }
}
foreach (var link2 in linksToRemove) {
   linksToRemove.Add(link2);
}
```

**Comment by helhaddad** [comment]
Thank you so much Giulio Vian it work fine.
