### ISSUE TITLE
GetEmailAddress Library.

### ISSUE THREAD

**Issue by p13x** [tfsaggregator/tfsaggregator#212]
Hi,
GetEmailAddress Library always returns default value.
How can I verify why?

**Comment by giuliov** [comment]
I guess it is picking `Aggregator.Core.Script.ScriptLibrary` class, instead of `Aggregator.Core.Facade.ScriptLibrary`. I will look into it in the next days.

**Comment by giuliov** [comment]
Can you check if https://github.com/tfsaggregator/tfsaggregator/releases/tag/v2.3-beta.2 solves your issue?

**Comment by p13x** [comment]
I tried to use the domain name and user display name.
Still without luck.

**Comment by giuliov** [comment]
How are you checking this? Using the Server Plugin, the Web Service or the Console App ?
Beware: Console uses some fake code.

**Comment by giuliov** [comment]
Added note to doc, thanks for asking.
