### ISSUE TITLE
getting error ... Item with the same key has already been added

### ISSUE THREAD

**Issue by ricardocovo** [tfsaggregator/tfsaggregator#213]
I am getting the following error: 

![aggregatorerror](https://cloud.githubusercontent.com/assets/1675545/24103807/d36905a8-0d56-11e7-97b4-1039e25771f1.PNG)

Conditions:

- Rule is very simple. It does nothing but log a message
- The rule runs correctly with the Console App
-  The server has collections with projects with the same name as shown below
Collection A
    -> Cool Project
Collection B
    -> Cool Project

If you need any other info, please let me know.
-Ricardo

**Comment by giuliov** [comment]
I see something weird happening. Which TFS & Aggregator version are you using?

**Comment by ricardocovo** [comment]
I am using TFS2017; and the upgraded the aggregator last week, so it must be latest. I will confirm the version asap.

**Comment by giuliov** [comment]
Thanks, please be patient as this is non-trivial: yesterday I spent my _community-time-slot_ just to align my lab with updates.

This issue occurs also on the Console app? Have you considered the [Web Service](https://tfsaggregator.github.io/admin/install-webhooks/) version?

**Comment by ricardocovo** [comment]
Thanks Giulio. I will look into the web service.

I did test witht he ConsoleApp (from my pc and from the server) and it
works, but yesterday I realized my console app has version 2.1.0.0; so I
was planning to test the console app with the newer version.

Thanks again,

**Comment by ricardocovo** [comment]
Giulio,

I have been trying this thing on my end and figure I would share; I got the latest version from github  last Friday, and got it working on my machine.

The console application worked correctly; but when I deployed server plugin, it did not.

Both the console and the server plugin use the same Core library, so maybe the issue is on the context executing the request?

Thanks for looking into it.

**Comment by ricardocovo** [comment]
Hi Giulio... do you have any insights on this one?

**Comment by giuliov** [comment]
no sorry, bad days
have you tried to narrow the problem, e.g. renaming the project or disabling one of the collections ?

**Comment by ricardocovo** [comment]
Thanks for the reply.

I actually renamed all other projects so there is no duplicate project names that we can see on the surface. I will try disabling and let you know.

I also confirmed it works withe the Console App.

Thanks again,

**Comment by giuliov** [comment]
@ricardocovo I was able to reproduce the issue on TFS 2017.1. At first this is a bug in TFS, so I will touch base with them.
In the meantime you can reach me via email or Slack if you need to find a quick solution. BTW have you tried the [Web Service](https://tfsaggregator.github.io/admin/install-webhooks/) version?

**Comment by ricardocovo** [comment]
@giuliov thanks for your time. I will ping you on slack.
