### ISSUE TITLE
Current PBI Status

### ISSUE THREAD

**Issue by calbrecht2017** [tfsaggregator/tfsaggregator#214]
Currently we create Tasks that we have outlined that are required to be prefixed with DEV Coding, QA Testing, UAT Testing, etc.  But it is impossible to query using the online query tool to know what the current status of a PBI is in without looking at the Tasks and figuring it out or using the board.  So we want to use TFSAggregator to have a policy to update the Custom field on the PBI (PBI Current State) when Tasks are changed.  Has anyone written this type of policy and can it be accomplished.

**Comment by giuliov** [comment]
Yes, it is a common scenario to automatically update the parent (PBI/Use Case/Bug) when any of the children (Tasks/Bug) change.
You can look https://tfsaggregator.github.io/using/policy-examples/#using-linq-to-aggregate as a starting point.

**Comment by calbrecht2017** [comment]
Began writing a simple policy to just get familiar with this is the following:

<?xml version="1.0" encoding="utf-8"?>
<AggregatorConfiguration>

    <runtime>
        <logging level="Diagnostic"/>
    </runtime>

  

    
    <rule name="PBICurrentState" appliesTo="Task"><![CDATA[
    if (self.Title.StartsWith("UAT Testing"))
    {
       if (self.HasParent())
       {
          var parent = self.Parent;
          parent["SCOR.PBI.Current.State"] = "Ready for UAT Testing";
       }
    }
    ]]></rule>

    <policy name="DefaultPolicy">
        <collectionScope collections="*" />
        <ruleRef name="PBICurrentState" />
    </policy>

</AggregatorConfiguration>

where am i going wrong

**Comment by giuliov** [comment]
I see nothing wrong. Follows the suggestions at [Using the console to test Policies](https://tfsaggregator.github.io/admin/console-app/) and [Troubleshooting](https://tfsaggregator.github.io/admin/troubleshooting/) to test it all.

**Comment by calbrecht2017** [comment]
I am using the console to test and this is what it gives me


[Error]       02.219 Error CS1061 in script 'PBICurrentState' at line 2, column
14: 'Aggregator.Core.Interfaces.IWorkItemExposed' does not contain a definition
for 'Title' and no extension method 'Title' accepting a first argument of type '
Aggregator.Core.Interfaces.IWorkItemExposed' could be found (are you missing a u
sing directive or an assembly reference?)

**Comment by giuliov** [comment]
Title is not exposed, use `self["Title"]` and maybe add `?.ToString()`

**Comment by calbrecht2017** [comment]
Thanks for your help I got it to work
