### ISSUE TITLE
Update the state of a PBI (or any parent) to "Done" when all children get moved to "Done" or "Removed"

### ISSUE THREAD

**Issue by calbrecht2017** [tfsaggregator/tfsaggregator#215]
Can someone provide an example that has been written that does what the tool advertises in ready for production format

**Comment by calbrecht2017** [comment]
Update the state of a PBI (or any parent) to "Done" when all children get moved to "Done" or "Removed"

**Comment by giuliov** [comment]
LINQ usually helps here.

```
// this rule triggers on children, but updates the father
if (self.HasParent()) {
  var parent = self.Parent;
  if (parent.Children.All( child => child["System.Status"].ToString() == "Done" )) {
    parent.TransitionToState("Done", "Closed by TFS Aggregator");
  }
}
```

I wrote this sample on the spot: it may contain errors.

**Comment by calbrecht2017** [comment]
This is my runtime
    <runtime debug="false">
         <rateLimiting interval="00:00:01.0" changes="5" />
         <logging level="Diagnostic" />
         <script language="C#" />
         <server baseUrl="http://localhost:8080/tfs/SGLADefaultCollection" />
         <authentication autoImpersonate="false" />
    </runtime>

But when running the console I get this error:

[Error]       00.037 Error in policy file at line 9, position 11: The element 'r
untime' has invalid child element 'authentication'.

**Comment by jessehouwing** [comment]
Should be 

```
<AggregatorConfiguration>
    <runtime... />
    <rateLimuting... />
    Etc
```

**Comment by giuliov** [comment]
No @jessehouwing, `rateLimiting` must be a child of `runtime`.

@calbrecht2017 in [Editing A Policy](https://tfsaggregator.github.io/using/writing-rules/writing-rules/#editing-a-policy) we suggest to leverage [TFSAggregator XSD schema](https://github.com/tfsaggregator/tfsaggregator-core/blob/links_manipulation/Configuration/AggregatorConfiguration.xsd) to get Intellisense and validate in Visual Studio.

TFSAggregator raises that error applying the XSD to the policy file before using its content, so there must be something wrong in the file, but I cannot see what from your snippet or the error message. Can you send it in full (replace sensitive data with `***` where appropriate) to tfsaggregator@outlook.com?

**Comment by calbrecht2017** [comment]
Sorry this is my runtime

    <runtime debug="false">
         <rateLimiting interval="00:00:01.0" changes="5" />
         <logging level="Diagnostic" />
         <script language="C#" />
         <server baseUrl="http://localhost:8080/tfs/SGLADefaultCollection" />
         <authentication autoImpersonate="false" />
    </runtime>

And I still get this error:

[Error] 00.037 Error in policy file at line 9, position 11: The element 'r
untime' has invalid child element 'authentication'.

**Comment by calbrecht2017** [comment]
Moved authentication above the server and now getting this error:

Error: TF400324: Team Foundation services are not available from server http://l
ocalhost:8080/tfs/SGLADefaultCollection.
Technical information (for administrator):
  Unable to connect to the remote server
TF400324: Team Foundation services are not available from server http://localhos
t:8080/tfs/SGLADefaultCollection.
Technical information (for administrator):
  Unable to connect to the remote server
TF400324: Team Foundation services are not available from server http://localhos
t:8080/tfs/SGLADefaultCollection.
Technical information (for administrator):
  Unable to connect to the remote server

**Comment by giuliov** [comment]
The `server` element is optional and not needed in the greatest majority of scenario; we implemented it for very specific scenarios.
Remove it.

**Comment by calbrecht2017** [comment]
Fixed issue above  Where is the best place for documentation on how to get this policy to be placed on server to test it without the Console.  I have the following so this should only get applied to only the Eve2015_Sandbox project Correct so it wont get fired on my production Project?

    <policy name="DefaultPolicy">    
        <collectionScope collections="*" />
        <projectScope projects="Eve2015_Sandbox" />
        <ruleRef name="PBICurrentStatus" />
    </policy>

**Comment by giuliov** [comment]
The file must be named `TFSAggregator2.ServerPlugin.policies` and placed in the `Plugins` folder. TFS senses the changes and restart our plugin automatically.
The Admin guide should be complete in this respect, see [Installing the Server Plugin](https://tfsaggregator.github.io/admin/install/).

**Comment by calbrecht2017** [comment]
Thanks so much you have been a great help.  Couple other things to clarify:
1.)  My project scope will limit to Eve2015_Sandbox project
2.)  So what fires the policy?
3.)  Does this slowdown TFS at all?

**Comment by giuliov** [comment]
1. Yes, we extract collection and project name and rules apply only for matches
2. when you touch work items, see [How it works](https://tfsaggregator.github.io/intro/how-it-works/)
3. yes and no -- yes, the server plugin runs in the same process space as TFS, but it can be negligible unless the machine is low on resources. We do some caching and the rules' code is compiled not interpreted: you get a hit on the first execution to prepare these things.

**Comment by calbrecht2017** [comment]
All the help is fantastic.  So now I have a scenario that if I move a Task to Done I still want to evaluate what is in To Do to see what still has to be done.  So DEV coding Task is moved to Done and now I want to see if there is a Task in the To Do that the PBI is ready for.  Example I move DEV Coding task to Done and their is a QA Testing task in To Do I want to update my PBI Current State (Custom Field) to "Ready for QA Testing".  So can someone help me with how to evaluate this scenario.  Currently my code works great for those tasks that have change but I want to evaluate all Tasks under the Parent

**Comment by calbrecht2017** [comment]
This is my code but not sure why it's not updating the PBI:

        
    <rule name="PBICurrentStatus" appliesTo="Task"><![CDATA[
    if ((string)self.Parent["System.State"] == "Committed")  
    { 
      foreach (var childTask in self.Children.Where(childTask => childTask.TypeName == "Task"))
      {
        if (self.HasParent()) 
        {
          var parent = self.Parent;
          parent["SCOR.PBI.Current.State"] = "Development Test";
        }
      }  
    }
		]]>
	  </rule>

**Comment by giuliov** [comment]
`self.Children` refers to the Task's children, not the PBI's.

I suggest to write it this way (note the initial check)
```
if (self.HasParent()) 
{
  var parent = self.Parent;
  if ((string)parent["System.State"] == "Committed")  
  { 
    foreach (var childTask in parent.Children.Where(childTask => childTask.TypeName == "Task"))
    {
      parent["SCOR.PBI.Current.State"] = "Development Test";
    }
  }  
}
```

**Comment by giuliov** [comment]
Now I see that the `foreach` loop is completely useless. Maybe, you want to express some condition, e.g.:

```
if (self.HasParent()) 
{
  var parent = self.Parent;
  if ((string)parent["System.State"] == "Committed")  
  {
    // any children completed?
    if (parent.Children.Any(child => child.TypeName == "Task"
        && (string)child["System.State"] == "Done"))
    {
      parent["SCOR.PBI.Current.State"] = "Development Test";
    }
  }  
}
```

**Comment by calbrecht2017** [comment]
Perfect Thanks so much for your help

**Comment by calbrecht2017** [comment]
So the latest code will go through all the Tasks for a given PBI to see if any of them meet a criteria.  Should the Console be tested with the PBI ID or can it be done with just one of the workitems to evaluate all the Tasks to see if a criteria is met.  Because it seems when I test with the Console I am not getting the result as expected.  Thanks.

**Comment by giuliov** [comment]
If you pass to the Console app the Id of a PBI, that Rule will not trigger because you set the condition `appliesTo="Task"`; only the Id of a Task may trigger such Rule.

**Comment by calbrecht2017** [comment]
So I have a Task Titled DEV Coding that is Done and a Task Prod Deploy that is To Do and I run the Console with the DEV Coding ID and this code doesn't update the PBI with "Ready for Prod Deploy" what do you see wrong with it

    <rule name="PBICurrentStatus" appliesTo="Task"><![CDATA[
    if ((string)self.Parent["System.State"] == "Committed")  
    { 
      if (self.HasParent()) 
      {
        var parent = self.Parent;
        var Title = self["Title"].ToString();
        if (parent.Children.Any(child => child.TypeName == "Task" 
            && (string)child["System.State"] == "Done" 
            && Title.Contains("DEV Cod") == true
            && (string)child["System.State"] == "To Do"
            && Title.Contains("Prod Dep") == true))
        {
          parent["SCOR.PBI.Current.State"] = "Ready for Prod Deploy";
        }
      }
    }
		]]>
	  </rule>

**Comment by giuliov** [comment]
The condition will always be false. I guess you want to write something like
```
    if (parent.Children.Any(child => child.TypeName == "Task" 
        && (
            ((string)child["System.State"] == "Done" 
            && Title.Contains("DEV Cod") == true
           ) || (
            (string)child["System.State"] == "To Do"
            && Title.Contains("Prod Dep") == true
           )
        )))
```

**Comment by calbrecht2017** [comment]
Can you tell me why this doesn't work:

        
    <rule name="InitialStatus" appliesTo="Product Backlog Item"><![CDATA[
      if ((string)self.Parent["System.State"] == "Committed")
      {
        var parent = self.Parent;
        parent["SCOR.PBI.Current.State"] = "Not Started"
      }            
    ]]>
	  </rule>

[Critical]    04.300 Exception encountered processing notification: Object refer
ence not set to an instance of an object.
Stack Trace:   at RESERVED.Script_InitialStatus.RunScript(IWorkItemExposed self,
 IWorkItemRepositoryExposed store, IRuleLogger logger, IScriptLibrary Library)
   at Aggregator.Core.Script.DotNetScriptEngine`1.RunScript(Assembly assembly, S
tring scriptName, IWorkItem self, IWorkItemRepository store) in D:\a\1\s\Aggrega
tor.Core\Script\DotNetScriptEngine{TCodeDomProvider}.cs:line 153
   at Aggregator.Core.Script.DotNetScriptEngine`1.Run(String scriptName, IWorkIt
em workItem, IWorkItemRepository store) in D:\a\1\s\Aggregator.Core\Script\DotNe
tScriptEngine{TCodeDomProvider}.cs:line 243
   at Aggregator.Core.EventProcessor.ApplyRule(Rule rule, IWorkItem workItem) in
 D:\a\1\s\Aggregator.Core\EventProcessor.cs:line 109
   at Aggregator.Core.EventProcessor.ApplyRules(IWorkItem workItem, IEnumerable`
1 rules) in D:\a\1\s\Aggregator.Core\EventProcessor.cs:line 95
   at Aggregator.Core.EventProcessor.ProcessEvent(IRequestContext requestContext
, INotification notification) in D:\a\1\s\Aggregator.Core\EventProcessor.cs:line
 62
   at Aggregator.ConsoleApp.RunCommand.Run(String[] remainingArguments) in D:\a\
1\s\Aggregator.ConsoleApp\RunCommand.cs:line 120

**Comment by jessehouwing** [comment]
You're accessing self.parent.State before checking self.hasparent.

**Comment by calbrecht2017** [comment]
Thanks and so shouldn't this Rule get fired if I run the Console with the PBI referenced?  It doesn't seem to be firing.

**Comment by calbrecht2017** [comment]
This is the condition I want to meet though when the DEV Coding Task is Done and there is a QA Deploy Task in To Do and with an OR it is always TRUE with or Without the QA Deploy task 

<rule name="PBICurrentStatus" appliesTo="Task"><![CDATA[
if ((string)self.Parent["System.State"] == "Committed")  
{ 
  if (self.HasParent()) 
  {
    var parent = self.Parent;
    var Title = self["Title"].ToString();
    if (parent.Children.Any(child => child.TypeName == "Task" 
        && (string)child["System.State"] == "Done" 
        && Title.Contains("DEV Cod") == true
        && (string)child["System.State"] == "To Do"
        && Title.Contains("Prod Dep") == true))
    {
      parent["SCOR.PBI.Current.State"] = "Ready for Prod Deploy";
    }
  }
}
	]]>
  </rule>

**Comment by calbrecht2017** [comment]
So I want to Update the PBI Current State when Both Conditions Are TRUE Only

        // ***** DEV Coding Is Complete QA Testing Task In Progress
        if (
            (parent.Children.Any(child => child.TypeName == "Task" && (((string)child["System.State"] == "Done" && Title.Contains("DEV Cod") == true))))
        &&  (parent.Children.Any(child => child.TypeName == "Task" && (((string)child["System.State"] == "To Do" && Title.Contains("QA Dep") == true))))
           )
        {
           parent["SCOR.PBI.Current.State"] = "Ready for QA Deploy";
           goto Outer;
        }
      }
    }

**Comment by giuliov** [comment]
`&&` is the logical and operator: the condition you wrote will _always_ be false.

Above I show you two important corrections:

1. test `HasParent()` **before** accessing `Parent` property
2. use an or `||` operator

Using functions you can simplify your rules.

```
<function>
bool IsTask(IWorkItemExposed workItem) {
  return workItem.TypeName == "Task";
}
bool HasState(IWorkItemExposed workItem, string state) {
  return (string)workItem["System.State"] == state;
}
bool TitleMatches(IWorkItemExposed workItem, string s) {
  return ((string)workItem["System.Title"]).Contains(s);
}
</function>
<rule name="PBICurrentStatus" appliesTo="Task"><![CDATA[
// self is Task
if (self.HasParent()) 
{
    // parent is PBI
    var parent = self.Parent;
    // ***** DEV Coding Is Complete QA Testing Task In Progress
    if (TitleMatches(parent,"DEV Cod")
        && parent.Children.Any(child => IsTask(child) && HasState(child,"Done"))) {
           parent["SCOR.PBI.Current.State"] = "Ready for QA Deploy";
    }
    if (TitleMatches(parent,"QA Dep")
        && parent.Children.Any(child => IsTask(child) && HasState(child,"To Do"))) {
           parent["SCOR.PBI.Current.State"] = "Ready for QA Deploy";
    }
}
]]></rule> 
``` 

but it will be easier for you to write down your conditions in table and then write Rule code.

**Comment by calbrecht2017** [comment]
It is weird it was working through the console putting in one of the Task IDs and now it doesn't seem to be working at all.  Do you see something wrong.  And would your suggestion be to have a Rule per scenario?

<?xml version="1.0" encoding="utf-8"?>
<AggregatorConfiguration>

    <runtime debug="false">
         <logging level="Diagnostic" />
         <script language="C#" />
         <authentication autoImpersonate="false" />
     </runtime>
     
     <function>
       bool IsTask(IWorkItemExposed workItem) 
       {
         return workItem.TypeName == "Task";
       }

       bool HasState(IWorkItemExposed workItem, string state) 
       {
         return (string)workItem["System.State"] == state;
       }
       
       bool TitleMatches(IWorkItemExposed workItem, string s) 
       {
         return ((string)workItem["System.Title"]).Contains(s);
       }
    </function>        
     
    <rule name="PBIQADeploy" appliesTo="Task"><![CDATA[
      
      // self is Task
      if (self.HasParent()) 
      {
        // parent is PBI
        var parent = self.Parent;
        // ***** DEV Coding Is Complete QA Testing Task In Progress
        if (TitleMatches(parent,"DEV Cod")
            && parent.Children.Any(child => IsTask(child) && HasState(child,"Done"))) 
        {
          parent["SCOR.PBI.Current.State"] = "Development Done";
        }
        if (TitleMatches(parent,"QA Dep")
            && parent.Children.Any(child => IsTask(child) && HasState(child,"To Do"))) 
        {
          parent["SCOR.PBI.Current.State"] = "Ready for QA Deploy";
        }
      }
		  ]]>
	  </rule>    
    
    <policy name="PBIStatus">    
        <collectionScope collections="*" />
        <projectScope projects="Eve2015_Sandbox" />
        <ruleRef name="PBIQADeploy" />
    </policy>

</AggregatorConfiguration>
