### ISSUE TITLE
Update the PBI Custom Field When Two Tasks Criteria is met

### ISSUE THREAD

**Issue by calbrecht2017** [tfsaggregator/tfsaggregator#217]
I am wanting to update the PBI with the Current Status based on Logic when 2 Tasks are Sitting In Different Status

Example:  When Task Dev Coding is Done and QA Deploy Task is To Do I want to have that Criteria update.  This is what I have but I need HELP I have tried numerous methods

So I want to Update the PBI Current State when Both Conditions Are TRUE Only

    // ***** DEV Coding Is Done QA Testing Task To Do
    if (
        (parent.Children.Any(child => child.TypeName == "Task" && (((string)child["System.State"] == "Done" && Title.Contains("DEV Cod") == true))))
    &&  (parent.Children.Any(child => child.TypeName == "Task" && (((string)child["System.State"] == "To Do" && Title.Contains("QA Dep") == true))))
       )
    {
       parent["SCOR.PBI.Current.State"] = "Ready for QA Deploy";
       goto Outer;
    }
  }
}

**Comment by giuliov** [comment]
COPY AND PASTE FROM ISSUE #216 


&& is the logical and operator: the condition you wrote will always be false.

Above I show you two important corrections:

test HasParent() before accessing Parent property
use an or || operator
Using functions you can simplify your rules.

<function>
bool IsTask(IWorkItemExposed workItem) {
  return workItem.TypeName == "Task";
}
bool HasState(IWorkItemExposed workItem, string state) {
  return (string)workItem["System.State"] == state;
}
bool TitleMatches(IWorkItemExposed workItem, string s) {
  return ((string)workItem["System.Title"]).Contains(s);
}
</function>
<rule name="PBICurrentStatus" appliesTo="Task"><![CDATA[
// self is Task
if (self.HasParent()) 
{
    // parent is PBI
    var parent = self.Parent;
    // ***** DEV Coding Is Complete QA Testing Task In Progress
    if (TitleMatches(parent,"DEV Cod")
        && parent.Children.Any(child => IsTask(child) && HasState(child,"Done"))) {
           parent["SCOR.PBI.Current.State"] = "Ready for QA Deploy";
    }
    if (TitleMatches(parent,"QA Dep")
        && parent.Children.Any(child => IsTask(child) && HasState(child,"To Do"))) {
           parent["SCOR.PBI.Current.State"] = "Ready for QA Deploy";
    }
}
]]></rule> 
but it will be easier for you to write down your conditions in table and then write Rule code.
