### ISSUE TITLE
Help : ILocationService' does not contain a definition for 'GetSelfReferenceUri'

### ISSUE THREAD

**Issue by helhaddad** [tfsaggregator/tfsaggregator#218]
Hi,

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'ILocationService' does not contain a definition for 'GetSelfReferenceUri' and no extension method 'GetSelfReferenceUri' accepting a first argument of type 'ILocationService' could be found (are you missing a using directive or an assembly reference?)	Aggregator.Core.Plugin	C:\Projets\tfsaggregator23\Aggregator.Core\Facade\RequestContextWrapper.cs	100	Active

Can you help me to solve this error please

**Comment by jessehouwing** [comment]
Looks like your reference assemblies for the tfs server version don't match
the selected project configuration.

Make sure you are building against the tfs version installed on your system
or that you have placed the correct reference assemblies in the external
dependencies folder.

If that's not the case, you may be building against a TFS version we do not
(yet) support, in which case we'd need to extend the project configurations
to fix that.

**Comment by helhaddad** [comment]
My TFS version is : 2017
I added the assemblies from the folder : C:\Program Files\Microsoft Team Foundation Server 15.0\Application Tier\Web Services\bin

I don't now wath is the problem

**Comment by jessehouwing** [comment]
What is the solution configuration you have selected?

**Comment by helhaddad** [comment]
Release-2017

**Comment by helhaddad** [comment]
It's OK i used a old dll my tfs it's a migration from 2015 to 2017.

Thank you so mush Jesse
