### ISSUE TITLE
Problem about automatically changing the field state of raw requirement by the "trace from" linked feature

### ISSUE THREAD

**Issue by ShawnTung** [tfsaggregator/tfsaggregator#219]
Hi
**System**:
TFS server version 14.95.25229.0 of 2015
Aggregator version 2.1
**Background**:
Assume there is one Raw Requirement is linked to several Features by the “trace from” link type.
**What to do**:
According to the customized rule, when the field state of one of these Features is changed, we want to automatically change the field state of Raw Requirement.
The step of achievement is as follow:
1. To locate the changed Feature;
2. Locate the linked Raw Requirement by the changed Feature;
3. Locate all the linked Features;
4. Judge all the field states of linked Features by the customized rule;
5. According to the judgement, automatically change the field state of Raw Requirement.

**Problem**:
The difficulty is step 2 and 3. And the two steps are related.To achieve step 2 and 3, there are two ways. 
One way can achieve the step 2, but when come to step 3, there comes to a new problem.
The other way which is suggested by Giulio Vian is not supported by our service, but this is the opimal option.

A. the FluentQuery way
The following code is for step 2, and it is able to locate Raw Requirement.
```
// For step 2
FluentQuery fluentQuery = new FluentQuery(self);
fluentQuery.LinkType = "xxxxx.Trace-Forward";
IWorkItemExposed TraceFromRequirement = self.GetRelatives(fluentQuery).Where(i => i["System.WorkItemType"].ToString().Equals("Raw Requirement")).SingleOrDefault();
```
When want to achieve step 3, there comes to an error, and the message is "there is more than one element in the array".
```
// For step 3
FluentQuery fluentQuery1 = new FluentQuery(TraceFromRequirement);
fluentQuery1.LinkType = "xxxxx.Trace-Reverse";
IWorkItemExposed TraceToFeature = TraceFromRequirement.GetRelatives(fluentQuery1).Where(i => i["System.WorkItemType"].ToString().Equals("Feature")).SingleOrDefault();
```			

B. the FollowingLinks way
This way is suggested by Giulio Vian, but not supported.
```
// self is a PBI workitem
var tests = self.FollowingLinks("xxxxx.Trace-Reverse").WhereTypeIs("Feature");
foreach (var test in tests)
{
   // do something to test case workitem
}
```

**Comment by giuliov** [comment]
If I read correctly, your Rule should go along these lines

```
var changedFeature = self;
var linkedRequirement = changedFeature.FollowingLinks("xxxxx.Trace-Forward").WhereTypeIs("Raw Requirement").SingleOrDefault();
var featuresForRequirement = changedFeature.FollowingLinks("xxxxx.Trace-Forward").WhereTypeIs("Feature");

// all linked Features in Done state?
bool allDone = featuresForRequirement.All(f => "Done" == ((string)f["System.State"]));

// there is a Feature in ToDo state?
bool oneNotStarted = featuresForRequirement.Any(f => "To Do" == ((string)f["System.State"]));

// etc

if (allDone) {
  linkedRequirement.TransitionToState("Done", "Closed by TFS Aggregator");
} else if (/*...*/) {
  //...
}
```

**Comment by ShawnTung** [comment]
Problem Solved! 
Thanks
