### ISSUE TITLE
Multiple Rules

### ISSUE THREAD

**Issue by calbrecht2017** [tfsaggregator/tfsaggregator#220]
Is it best to write specific rules and have multiple rules for each task you want performed/evaluated or is it best to try and keep everything in minimal rules for performance

**Comment by jessehouwing** [comment]
If you have multiple rules that act on previous iterations or query all
children of a rule, it may be beneficial to bunch them up.

But since work item instances are kept loaded while rules execute I do not
expect a massive performance difference.

We haven't executed performance tests to measure such differences.

**Comment by calbrecht2017** [comment]
Thanks it seems with the amount of logic in one rule it seems to have put alot of task on the SQL Server end of our TFS

**Comment by calbrecht2017** [comment]
Attached is rule set that I am executing and it is maximizing our server:

[TFSAggregator2.ServerPlugin.txt](https://github.com/tfsaggregator/tfsaggregator/files/873474/TFSAggregator2.ServerPlugin.txt)

**Comment by jessehouwing** [comment]
Things that cause bug increases in processing:

* updating multiple workitem based on a work item change (recursively
triggers the aggregator)
* iterating through older versions of a workitem. Each older revision
causes another SQL query
* traversing relations between work items.

There are a few features in the Aggregator to increase performance.
Hasparent and haschildren doesn't impact performance. There are a few lazy
query iterators that allow you to fetch complex tree structures in one go
so you won't have to fetch each layer individually.

You can increase performance by scoping rules to just the types of work
items that need to trigger it and with the most version, also the ability
to trigger only when certain fields have changed.

**Comment by jessehouwing** [comment]
Have you tried storing parent.children in a variable to keep a link to the
same collection?

**Comment by calbrecht2017** [comment]
can you reference an example in the code I posted

**Comment by calbrecht2017** [comment]
Ok today I am getting error below:
[Critical]    04.310 Exception encountered processing notification: TF26198: The
 work item does not exist, or you do not have permission to access it.
Stack Trace:   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.Load
WorkItemFromRowSetInternal(Int32 rev, Nullable`1 asof, IWorkItemRowSets witem)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem..ctor(WorkItemSt
ore store, Int32 id)
   at Aggregator.Core.Facade.WorkItemRepository.GetWorkItem(Int32 workItemId) in
 D:\a\1\s\Aggregator.Core\Facade\WorkItemRepository.cs:line 52
   at Aggregator.Core.EventProcessor.ProcessEvent(IRequestContext requestContext
, INotification notification) in D:\a\1\s\Aggregator.Core\EventProcessor.cs:line
 58
   at Aggregator.ConsoleApp.RunCommand.Run(String[] remainingArguments) in D:\a\
1\s\Aggregator.ConsoleApp\RunCommand.cs:line 120

With this code:

<?xml version="1.0" encoding="utf-8"?>
<AggregatorConfiguration>

    <runtime debug="false">
         <rateLimiting interval="00:00:10.00" changes="10" />
         <logging level="Diagnostic" />
         <script language="C#" />
         <authentication autoImpersonate="false" />
     </runtime>
     
     <function>
       bool IsTask(IWorkItemExposed workItem) 
       {
         return workItem.TypeName == "Task";
       }

       bool HasState(IWorkItemExposed workItem, string state) 
       {
         return (string)workItem["System.State"] == state;
       }
       
       bool TitleMatches(IWorkItemExposed workItem, string s) 
       {
         return ((string)workItem["System.Title"]).ToLower().Contains(s.ToLower());
       }
    </function>    
    
    <rule name="PBICurrentState" appliesTo="Task"><![CDATA[
    
      if (self.HasParent()) 
      {
        
        var parent = self.Parent;             
        
        if ((string)self.Parent["System.State"] == "Committed")
        {
          if (TitleMatches(self,"DEV Cod") && IsTask(self) && HasState(self,"To Do"))
          {
            parent["SCOR.PBI.Current.State"] = "Not Started";
          }         
        }
        
        //Parent Status
        if ((string)self.Parent["System.State"] == "Prod_Approved")
        {
          parent["SCOR.PBI.Current.State"] = "Prod Approved";
        }
        if ((string)self.Parent["System.State"] == "Done")
        {
          parent["SCOR.PBI.Current.State"] = "Complete";
        }
      }

      ]]>
	  </rule> 
    
    <policy name="PBIStatus">    
        <collectionScope collections="*" />
        <projectScope projects="Eve2015_Sandbox" />
        <ruleRef name="PBICurrentState" /> 
    </policy>

</AggregatorConfiguration>

**Comment by giuliov** [comment]
`TF26198: The work item does not exist, or you do not have permission to access it.` is self-explanatory: you are passing the wrong Id to the Console app or the user running the app has no permission on your TFS.

**Comment by calbrecht2017** [comment]
is there a way to only fire a rule if the status is the only thing that has been updated.  So if title or description is updated it won't fire.

Thanks.
