### ISSUE TITLE
SQL Server performance

### ISSUE THREAD

**Issue by calbrecht2017** [tfsaggregator/tfsaggregator#221]
We seem to be experiencing some increase in SQL Server CPU usage after we post a new Policy file on the TFS Server.  Then after sometime it seems to settle and the rules get applied and we can really load the system with no issues.  Would you agree that we might see this type of performance hit

Thanks.

**Comment by giuliov** [comment]
Can you tell us more? Do you have any logs? What versions of software are you using? Have captured any performance metric or graph?
The [Troubleshooting](https://tfsaggregator.github.io/admin/troubleshooting/) page gives some suggestion on proper issue reporting.

Reminder: this is a community project, time and resources are _very_ limited, we get no money for this, quite the opposite.

**Comment by jessehouwing** [comment]
When you introduce a new cascading rule, that could make sense. I also
wonder what your tfs server does after an app pool recycle. It may just be
that the caches need to be restored.

**Comment by giuliov** [comment]
This gave my the idea of adding some custom perf counter: tracked as issue #222.
