### ISSUE TITLE
Does aggregator support time-triggered scenario ?

### ISSUE THREAD

**Issue by ShawnTung** [tfsaggregator/tfsaggregator#223]
Except the common scenario, does aggregator support time-triggered scenario?

When there are millions of work items used by thousands of users, con't stand for the time delay. 
If there are several work items changed at the same time, the result might be wrong.

the common scenario: 
https://tfsaggregator.github.io/intro/how-it-works/

**Comment by giuliov** [comment]
Interesting, very interesting.
I will sketch here some ideas, but I suggest to get in touch privately to drill down.

If you use the Server Plugin or the Web Service, the event it is triggered by TFS for work items.
For the Console App you have to specify:
- a single work item
- a list of work items
- the work item specified via a WIQL query (a new feature that will be soon available in beta)
on which apply the rules.
You can leverage this by scheduling the Console App or create a custom tool based on it.

My guess is that you would like to _queue_ the triggering and have the Aggregator run through all queued events in one fell swoop. If you are looking for such a thing, it requires a different architecture and a notable effort (to be discussed privately).
