### ISSUE TITLE
Team Foundation could not update the work item because it was already updated by another user, it does not exist, or you do not have permission to update it.

### ISSUE THREAD

**Issue by Wylde44** [tfsaggregator/tfsaggregator#225]
Hi!
There is a problem which appears only when creating new "feature" item in my case.
![aggregator_error](https://cloud.githubusercontent.com/assets/16348172/25235144/f64d62b8-25ec-11e7-8671-2dc456bc871c.png)
Item's history shows that "backlog priority" field was changed right after the creation, so maybe this is the key, but aggregator says that the item is valid to save.
Thanks in advance!

**Comment by Wylde44** [comment]
Aggregator v2.1.1.
TFS 2015.3

**Comment by jessehouwing** [comment]
That's sparsification kicking in and probably not something we can do
anything about.

**Comment by Wylde44** [comment]
What do you think, maybe it is possible to do something like that 
```
if (workItem.IsDirty) {
     workItem.SyncToLatest();
     workItem.Save();
}
```
or use 
`workItem.Save(SaveFlags.MergeAll);`
?

**Comment by jessehouwing** [comment]
Does it matter? It will be triggered again for the new revision, your rule will trigger again.
