### ISSUE TITLE
Readonly field

### ISSUE THREAD

**Issue by tango-charly** [tfsaggregator/tfsaggregator#226]
Hello,

Is it possible to auto-sum a readonly field ? It seems

```
[Verbose]     00.055 Connecting to http://mytfs:8080/tfs/myCollectionas user_c
[Diagnostic]  00.539 Built a new Work Item Repository for http://mytfs:8080/tfs/myCollection
[Verbose]     00.541 Building Script Engine for C#
[Information] 00.728 Starting processing on workitem #1326
[Diagnostic]  00.811 Policy scope Collections(*) matches myCollection
[Verbose]     00.975 Policy 'DefaultPolicy' applies
[Verbose]     00.976 Evaluating Rule 'CalcEstimated'
[Diagnostic]  00.977 Rule scope WorkItemTypes(Pilotage) matches Pilotage
[Verbose]     00.978 Applying Rule 'CalcEstimated' on #1326
[Diagnostic]  00.989 Output from script 'CalcEstimated': []
[Verbose]     00.999 Pilotage [1326] is NOT valid to save.
[Verbose]     01.000 Invalid fields: Path.ToMy.Field

[Information] 01.001 Processing completed: Success
Succeeded.
```

My field : Path.ToMy.Field is in ReadOnly.

So i think it's the problem, but i prefer to ask to be sure. :smile: 

Thank's

**Comment by giuliov** [comment]
The message `Pilotage [1326] is NOT valid to save` raise from the validation stage _before_ saving

If validation does not pass, the in-memory changes are not saved to the database (see https://github.com/tfsaggregator/tfsaggregator-core/blob/master/EventProcessor.cs#L149-L156).

**Comment by tango-charly** [comment]
Thank's
I understandood this, but my question is : Does readonly field make item not valid to save ?

**Comment by jessehouwing** [comment]
It does.

**Comment by tango-charly** [comment]
Thank's guys :)
