### ISSUE TITLE
Can i use self.AddWorkItemLink(newRelatedLink, "System.LinkTypes.Related")

### ISSUE THREAD

**Issue by helhaddad** [tfsaggregator/tfsaggregator#227]
In Aggregator 2.3V can I use this code
`self.AddWorkItemLink(newRelatedWI, "System.LinkTypes.Related");`
to add a related relation between Task and Bug?

**Comment by helhaddad** [comment]
Hi,

I need your help please

**Comment by giuliov** [comment]
I do not see a reason for this not working.

Do you get an error?

**Comment by jessehouwing** [comment]
What's your question exactly?

**Comment by Nyx54** [comment]
I try it (because that's also what I want on my WorlItem) and it seems that an error occurs
"Specified argument was not in limits of the valid range"
Parameter name: linkTypeName
![capture](https://cloud.githubusercontent.com/assets/13660037/25343760/43ca37de-2910-11e7-844d-22b19878dc63.PNG)

**Comment by Nyx54** [comment]
OK I fix it.
It seems that if you only use "Related" instead of "System.LinkTypes.Related" it works !

**Comment by helhaddad** [comment]
I received the same error as you Nyx54.

I need just to replace "System.LinkTypes.Related" by "Related" ??

**Comment by Nyx54** [comment]
Yes, it worked for me

**Comment by helhaddad** [comment]
Thank you, I test it today and i let you know.

**Comment by helhaddad** [comment]
Thank you Nyx54, it worked for me also.

**Comment by giuliov** [comment]
That's weird: the code tries to match the immutable (reference) name or the localized name. I guess this happens as it is a Network Topology link type which is different from the usual Tree or Directed topology.

**Comment by SAnCherepan** [comment]
Might be a bit late, but just like with parent/child or any other link type, there are 2 different types of `Related`:
`System.LinkTypes.Related-Forward`
`System.LinkTypes.Related-Reverse`

My favourite part about it is that the short name for both is `Related`, which is... not that intuitive.
