### ISSUE TITLE
Dynamically create a list

### ISSUE THREAD

**Issue by Nyx54** [tfsaggregator/tfsaggregator#228]
Hello,
I post here in case you can help me.

I recover all WorkItem titles and try to create a list from them (to use it in a specific WorkItemType).
Actually, this WorkItem has a string type field. When I inject what I recover, I have the string :
![capture](https://cloud.githubusercontent.com/assets/13660037/25426964/463bded4-2a71-11e7-997a-d07c5db4b0aa.PNG)

I try to transform this string into a list.

I continue to search but, is it possible to do or not ?

Thanks

**Comment by Nyx54** [comment]
Or, in other words, Is it possible to create a field and inject it into a WorkItem programmatically ?

**Comment by giuliov** [comment]
IMHO it would be simpler to use a Global List. Sadly, Aggregator [expose a method to read](https://tfsaggregator.github.io/using/objects-reference/store-object/#getgloballist-method) a Global List but no methods to edit it.

**Comment by Nyx54** [comment]
Thanks for the answer. 

As I understand, it seems that I can't do what I want.
Because I need to modify the list when a user add/delete a WorkItem.

Don't be sad, Aggregator is a very good product !

**Comment by giuliov** [comment]
Yes you can refer to a global list once in the work item type definition (using Process Editor or witadmin) and simply alter the list content dynamically from an Aggregator Rule.
It is not hard to write an update method, but requires some time... can you submit a PR to tfsaggregator-core?

**Comment by Nyx54** [comment]
Not sure If I have the time to do it (it was just an idea of improvment, not really needed).

Sorry for the disturbing ~
