### ISSUE TITLE
Exception encountered processing notification: Specified ca st is not valid.

### ISSUE THREAD

**Issue by jlema0590** [tfsaggregator/tfsaggregator#229]
**Hi,** 
**At the time of verification with TFSaggregator2.ConsoleApp.exe**

Stack Trace:   at RESERVED.Script_CalcWFJS.RunScript(IWorkItemExposed self, IWor
kItemRepositoryExposed store, IRuleLogger logger, IScriptLibrary Library)
   at Aggregator.Core.Script.DotNetScriptEngine`1.RunScript(Assembly assembly, S
tring scriptName, IWorkItem self, IWorkItemRepository store) in D:\a\1\s\Aggrega
tor.Core\Script\DotNetScriptEngine{TCodeDomProvider}.cs:line 153

   at Aggregator.Core.Script.DotNetScriptEngine`1.Run(String scriptName, IWorkIt
em workItem, IWorkItemRepository store) in D:\a\1\s\Aggregator.Core\Script\DotNe
tScriptEngine{TCodeDomProvider}.cs:line 243

   at Aggregator.Core.EventProcessor.ApplyRule(Rule rule, IWorkItem workItem) in
 D:\a\1\s\Aggregator.Core\EventProcessor.cs:line 109

   at Aggregator.Core.EventProcessor.ApplyRules(IWorkItem workItem, IEnumerable`
1 rules) in D:\a\1\s\Aggregator.Core\EventProcessor.cs:line 95

   at Aggregator.Core.EventProcessor.ProcessEvent(IRequestContext requestContext
, INotification notification) in D:\a\1\s\Aggregator.Core\EventProcessor.cs:line
 62

   at Aggregator.ConsoleApp.RunCommand.Run(String[] remainingArguments) in D:\a\
1\s\Aggregator.ConsoleApp\RunCommand.cs:line 120

**Thanks for the help**

**Comment by jessehouwing** [comment]
Please share your rule

**Comment by jlema0590** [comment]
What I need is to add three values ​​and divide by a third to have the calculation of the WSJF field

**example**
(Business Value + Time Criticality + RR-OE Value) / Effort = WSJF

**Comment by giuliov** [comment]
I favor the use of GetField
```
<rule name="CalcEstimated" appliesTo="Feature"><![CDATA[

self.Fields["COB WSJF"] = self.GetField<double>("Business Value", 0.0) + self.GetField<double>("COB Time Criticality", 0.0);
// self[""COB WSJF"] = (double)self["Business Value"] + (double)self["COB Time Criticality"] + (double)self["COB RROE"];

]]></rule>

```
and use the C# line comment `//` to skip code.

**Comment by jlema0590** [comment]
**When using the GetField in the rule of error.**

Error CS0029 in script 'CalcEstimated' at line 4, column 27 : Cannot implicitly convert type 'double' to 'Aggregator.Core.Interfaces.IField'

**Thanks for the help**

**Comment by giuliov** [comment]
```
self.Fields["COB WSJF"].Value = self.GetField<double>("Business Value", 0.0) + self.GetField<double>("COB Time Criticality", 0.0);
```

**Comment by jlema0590** [comment]
If I have the Value field of the business with value integer as I can put in the rule

Business Value = Integer

**Thanks for the help**

**Comment by giuliov** [comment]
Not sure what you mean. If the `COB WSJF` field is an integer, then you have to cast the result, e.g.
```
var bizValue = self.GetField<double>("Business Value", 0.0) + self.GetField<double>("COB Time Criticality", 0.0);
self.Fields["COB WSJF"].Value = (int)bizValue;
```
or 
```
self.Fields["COB WSJF"].Value = (int) Math.Round(bizValue);
```
It is just C# code.

**Comment by jlema0590** [comment]
The field that is integer is the "Business Value"

Business Value = Integer value
COB Time Criticality= Double value
COB WSJF = Double value

elf.Fields["COB WSJF"].Value = **self.GetField<int>("Business Value", 0)** + self.GetField<double>("COB Time Criticality", 0.0);

Thanks for the help

**Comment by jlema0590** [comment]
The formula that I need is the following

Business Value = Integer value
COB Time Criticality= Double value
COB RROE = Double value
Effort = Double value
COB WSJF = Double value

**COB WSJF = ( Business Value + COB Time Criticality + COB RROE ) \ Effort**

self.Fields["COB WSJF"].Value = self.GetField<double>("Business Value", 0.0) + self.GetField<double>("COB Time Criticality", 0.0) + self.GetField<double>("COB RROE", 0.0) \ self.GetField<double>("Effort ", 0.0) ;

**Thanks for the help**

**Comment by giuliov** [comment]
Now I see the point.

You can simply use `0` for the default value, i.e. `self.GetField("Business Value", 0)`, or force the type `self.GetField<int>("Business Value", 0)`; with this you match the field type.
The sum will use the implicit conversion from `int` to `double`, no need to add a cast.

**Comment by jlema0590** [comment]
Thank you

To make a division with the example above as I can perform.


**COB WSJF = ( Business Value + COB Time Criticality + COB RROE ) \ Effort**


<?xml version="1.0" encoding="utf-8"?>
<AggregatorConfiguration>

self.Fields["COB WSJF"].Value = self.GetField<int>("Business Value", 0) + self.GetField("COB Time Criticality", 0.0) + self.GetField("COB RROE", 0.0) **\ self.GetField("Effort ", 0.0) ;**

</AggregatorConfiguration>

**Thanks for the help**

**Comment by giuliov** [comment]
That is
```
self.Fields["COB WSJF"].Value = ( self.GetField("Business Value", 0) + self.GetField("COB Time Criticality", 0.0) + self.GetField("COB RROE", 0.0) ) / self.GetField("Effort ", 0.0) ;
```
Note the parenthesis and the division sign; there is no `\` operator in C#.

**Comment by jlema0590** [comment]
**Thanks for the help**

:) :) 🥇

**Comment by jlema0590** [comment]
**Error**

[Error]       34.051 Error CS1026 in script 'CalcEstimated' at line 4, column 12
2: ) expected
[Error]       34.051 Error CS1525 in script 'CalcEstimated' at line 4, column 12
2: Invalid expression term ','
[Error]       34.051 Error CS1002 in script 'CalcEstimated' at line 4, column 12
4: ; expected
[Error]       34.051 Error CS1002 in script 'CalcEstimated' at line 4, column 12
7: ; expected
[Error]       34.051 Error CS1525 in script 'CalcEstimated' at line 4, column 12
7: Invalid expression term ')'
[Error]       34.051 Error CS1002 in script 'CalcEstimated' at line 4, column 17
0: ; expected
[Error]       34.051 Error CS1525 in script 'CalcEstimated' at line 4, column 17
0: Invalid expression term ')'


**Example Rule**

<?xml version="1.0" encoding="utf-8"?>
<AggregatorConfiguration>

    <runtime>
        <logging level="Diagnostic"/>
    </runtime>

	<rule name="CalcEstimated" appliesTo="Feature">
<![CDATA[

self.Fields["COB WSJF"].Value = ( self.GetField<int>("Business Value", 0) + self.GetField<double>("COB Time Criticality"), 0.0) + self.GetField<double>("COB RROE", 0.0) ) / self.GetField<double>("Effort ", 0.0) ;

]]>
    </rule>

    <policy name="DefaultPolicy">
        <collectionScope collections="DefaultCollection" />
        <ruleRef name="CalcEstimated" />
    </policy>

</AggregatorConfiguration>


**Thanks for the help**

**Comment by giuliov** [comment]
That error depends on the input values: if the formula reduces to `0/0` the result is `NaN` that fails a guard,
I will issue a patch to output a meaningful message before failing, but you have to re-think your formula.
Maybe you can use a default value of `1.0` for the denominator, i.e. `self.GetField("Effort", 1.0)`.

**Comment by jlema0590** [comment]
Thanks for the help,

A question can be used some rule where the field with the modified value is automatically updated

**Comment by jlema0590** [comment]
Thanks for the  help @giuliov 

I have solved the problem
