### ISSUE TITLE
Childer in state Accepted

### ISSUE THREAD

**Issue by jlema0590** [tfsaggregator/tfsaggregator#231]
Hi, 

How can I get the values ​​of the children's fields in the accepted state.

**Error**

[Error]       37.559 Error CS1061 in script 'RollupFeatureAccepted' at line 6, c
olumn 45: 'Aggregator.Core.Interfaces.IWorkItemExposed' does not contain a defin
ition for 'child' and no extension method 'child' accepting a first argument of
type 'Aggregator.Core.Interfaces.IWorkItemExposed' could be found (are you missi
ng a using directive or an assembly reference?)

**Example**

        if (self.HasParent())
        {
			var parent = self.Parent;
			if (parent.Children.All( child => child["System.Status"].ToString() == "Accepted" )) {
			parent["COB Total Effort Accepted"] = parent.Children.Sum(story => story.GetField<double>("Effort", 0d));

**Thanks for the help**

**Comment by giuliov** [comment]
Sorry for late answer, it was a busy week.

The message is about a syntax error that is not evident in the code you posted, maybe is in some other part of the rule.

**Comment by jlema0590** [comment]
Hello,

I attach the rules I have

[Rules.txt](https://github.com/tfsaggregator/tfsaggregator/files/1019549/Rules.txt)

I need to get the value of the stories only in Accepted state

**Thanks for the help**

**Comment by giuliov** [comment]
If I understand you want a rule like this
```
<rule name="RollupFeatureAccepted" appliesTo="Story"><![CDATA[
if (self.HasParent())
{
    parent["Cobiscorp.TotalEffortAccepted"] = parent.Children.Where(child => WorkItemType(child,"Story") && HasState(child,"Accepted")).Sum(story => story.GetField<double>("Microsoft.VSTS.Scheduling.Effort", 0d));
}
]]></rule>
```
I suggest that you ask some developer to help you writing the proper conditions and Linq code.

**Comment by jlema0590** [comment]
**Thanks for the help**
