### ISSUE TITLE
Problem setting up simple rule "AutoOpen" (from samples) on our on premise TFS (2015.2) instance: TF26027

### ISSUE THREAD

**Issue by Jazzman82** [tfsaggregator/tfsaggregator#232]
Using the server-Plugin. The first test with the console-App already fails with the TF26027-Exception complaining that the no field named "State" is found. (see attached tfsaggregator.txt-File for console output).
[tfsaggregator.txt](https://github.com/tfsaggregator/tfsaggregator/files/1007710/tfsaggregator.txt)

We are using the standard "Agile" Template (German-Version) so issue could be that the field is not named "State" but "Zustand" and the internal name being "System.State" instead of "State" and the code is leaving out the "System." when performing "TransitionToState" in Aggregator.Core.Navigation.StateWorkFlow.

Also attached our "TFSAggregator2.ServerPlugin.policies"-File and the "Tasks.xml" from the TFS-Process-Template: [temp.zip](https://github.com/tfsaggregator/tfsaggregator/files/1007733/temp.zip)

**Comment by Jazzman82** [comment]
I managed to get it to work with a build from my fork where I just changed all "State"-Strings to "System.State" in StateWorkflow.cs

So shall make a PR for this?

Remark: I had pretty much trouble getting it compiling and then running on our TFS instance due to reference problems. (I ended up brute-force: Copied all necessary references from TFS-Server to a single dir and referencing them from there).

I would only PR the changes in this single file.

**Comment by giuliov** [comment]
Please, go ahead.

I have some additional comments, so do not close this issue.

**Comment by Jazzman82** [comment]
Sorry, your reply ended up in spam folder, so didn’t see it before.

 

I made the PR today in https://github.com/tfsaggregator/tfsaggregator-core and was already merged in @jessehouwing already merged it.

Anything else to do? Is it necessary to integrate in this project as well?

 

 

Von: Giulio Vian [mailto:notifications@github.com] 
Gesendet: Donnerstag, 18. Mai 2017 09:24
An: tfsaggregator/tfsaggregator <tfsaggregator@noreply.github.com>
Cc: Jazzman82 <tobibuhl@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [tfsaggregator/tfsaggregator] Problem setting up simple rule "AutoOpen" (from samples) on our on premise TFS (2015.2) instance: TF26027 (#232)

 

Please, go ahead.

I have some additional comments, so do not close this issue.
