### ISSUE TITLE
Issue with console app on tfs 2017 update 1

### ISSUE THREAD

**Issue by galekseev** [tfsaggregator/tfsaggregator#233]
Hello, I'm trying to set up tfs aggregator for TFS 2017 update 1.
It successfully installs but when I try to set up any simple rule and check it with console application it fails even before applying any rules with "Object reference not set to an instance of an object" exception.
I tried with 2.2.1 and 2.3 with same result and checked all items in troubleshouting document with no help.

Any clues what could go wrong?

Below is console log and policies configuration in the attachment [SumFeatureEffort.policies.txt](https://github.com/tfsaggregator/tfsaggregator/files/1029222/SumFeatureEffort.policies.txt)

Aggregator.ConsoleApp 2.3.0-unstable.10+Branch.develop.Sha.8b3a5f87710636ed514c8f2988e145e20d9c3ba0
Console tool to test TFS Aggregator polices
Build: 2.3.0.0, Configuration: Release [TFS 2017.0]
Copyright (c) TFS Aggregator Team 2015-16
Executing run (Applies a policy file to specified work item(s)):
[Information] 00.008 Aggregator.Core started, version: 2.3.0-unstable.10+Branch.develop.Sha.8b3a5f87710636ed514c8f2988e145e20d9c3ba0, build: 2.3.0.0, configuration: Release [TFS 2017.0]
[Information] 00.049 Configuration loaded successfully from 'C:\Program Files\TFS Aggregator\samples\SumFeatureEffort.policies.txt'
[Verbose]     00.058 Connecting to https://tfs02.bmps.com/DefaultCollection impersonating WindowsIntegratedAuthenticationToken, running as galekseev
[Diagnostic]  00.508 Built a new Work Item Repository for https://tfs02.bmps.com/DefaultCollection using a WindowsIntegratedAuthenticationToken
[Verbose]     00.510 Building Script Engine for C#
[Critical]    00.822 Exception encountered processing notification: Object reference not set to an instance of an object.
Stack Trace:   at Aggregator.ConsoleApp.Notification..ctor(Int32 workItemId, ChangeTypes changeType, String teamProjectCollectionUrl, String projectName) in D:\a\1\s\Aggregator.ConsoleApp\Notification.cs:line 32
   at Aggregator.ConsoleApp.RequestContext.get_Notification() in D:\a\1\s\Aggregator.ConsoleApp\RequestContext.cs:line 56
   at Aggregator.ConsoleApp.RunCommand.Run(String[] remainingArguments) in D:\a\1\s\Aggregator.ConsoleApp\RunCommand.cs:line 116

**Comment by giuliov** [comment]
Gotcha: the Project name (`teamProjectName`) is wrong.

**Comment by galekseev** [comment]
Thank you. It helped.
teamProjectName is case-sensitive that's why it failed.
