### ISSUE TITLE
How automatically modify a field value when a link is manually added to a workitem?

### ISSUE THREAD

**Issue by francesco-sclano** [tfsaggregator/tfsaggregator#235]
I'm using TFS 2017 update 1 on premises. Is there any way with TFS Aggregator to automatically modify a field value when a link (e.g. parent/child, related etc.) is manually added to a work item by users on TFS Web Interface? If yes, could you please show me a code snippet example or the right documentation link?

**Comment by ExSF** [comment]
Ideally you could do it by tracking the History field and using the revision object to get access to all the links that were added on the last modification. The  [TFS revision API](https://www.visualstudio.com/en-us/docs/integrate/api/wit/revisions) support this but tfsaggregator [revision object](https://github.com/tfsaggregator/tfsaggregator/blob/master/Aggregator.Core/Facade/RevisionWrapper.cs) does not support links.

https://github.com/tfsaggregator/tfsaggregator/blob/master/Aggregator.Core/Facade/RevisionWrapper.cs
