### ISSUE TITLE
Is it possible to dinamically change the label of a TAB in workitem form?

### ISSUE THREAD

**Issue by tfs-dev** [tfsaggregator/tfsaggregator#237]
I'm using TFS 2017 update 1 on premises with still old form layout. Since in my custom workitem type I have more than one Description TAB (e.g. Trigger tab, Pre-conditions tab etc.), I'd like to dynamically change the label of TABS when some tetx is written inside (e.g. adding a * as suffix to the label) in order to give TFS users the possibility to immediately know which TAB effectively contains informations without the need to open them all.

**Comment by jessehouwing** [comment]
No this is not possible with the tfs Aggregator.
