### ISSUE TITLE
Please help me to understand my problem

### ISSUE THREAD

**Issue by helhaddad** [tfsaggregator/tfsaggregator#239]
Hi,
I have a problem that I do not understand, can you help me please ?

On my policy file I have 51 rules, the modifications are successfully done on the WIT but I see the changes only after 10 refreshe or more.

I use TFS 2017.1, TFSAggregator 2.3.

Please Help

**Comment by giuliov** [comment]
TFS call asynchronously Aggregator, so it will never be instantaneous.
Have you checked your server's performance?

**Comment by helhaddad** [comment]
It's not because I use version 2.3 beta ?

**Comment by giuliov** [comment]
Do not think so. Truly, I never tested with 50+ rules, so _maybe_ they have an impact.
When I complete the work on 2.3, I would like to add some performance counters so that we can have more information in scenario like yours.

**Comment by helhaddad** [comment]
Thanks a lot Giulio for your help, do you have an idea about the time it takes to finalize version 2.3 ?

**Comment by jessehouwing** [comment]
We're currently not doing any work to support multiple rule files.
