### ISSUE TITLE
Inconsistency in Docs - which TFS version supported

### ISSUE THREAD

**Issue by 1Bazs** [tfsaggregator/tfsaggregator#240]
Hello,
According to the [introduction ](https://tfsaggregator.github.io/intro/) TFS2015.4  supported. 
According to the [admin guide](https://tfsaggregator.github.io/admin/install/) it doesn't.
These two sections contain different informations. Please help to clarify.
Thank you,

**Comment by giuliov** [comment]
Gotcha, need to update the [Install](https://tfsaggregator.github.io/admin/install/) page.

The rule is: our "support" follows the same rules as Microsoft's that is the RTM version and the latest Update, which is Update 4 for TFS 2015.

Background: we need to cut down the number of tests and environments.
