### ISSUE TITLE
OriginalValue doesn't seem to be working (2017 RC1)

### ISSUE THREAD

**Issue by alexvaccaro** [tfsaggregator/tfsaggregator#241]
I have setup a number of rules to trigger updates only when the value (e.g. an IterationPath) changes, and I believed that comparing **OriginalValue** vs **Value** would give me the means to check if a value was being changed:

``` c#
var oldIteration = self.Fields["System.IterationPath"].OriginalValue;
var newIteration = self.Fields["System.IterationPath"].Value;
logger.Log(LogLevel.Verbose, "Iteration Path for #{0} was '{1}' and is now '{2}'", self.Id, oldIteration, newIteration);
```

However when I run this in DebugView the values of 'oldIteration' and 'newIteration' are the same. Was my assumption incorrect or is there an issue here?

**Comment by giuliov** [comment]
Referring to https://tfsaggregator.github.io/intro/how-it-works/#server-plugin the Plugin is notified _after_ the change has been persisted to the database, so `OriginalValue` refers to the value when Aggregator first read it from TFS.

If you want to compare to the value before user's save, you have to use [`PreviousRevision`](https://tfsaggregator.github.io/using/objects-reference/self-object/#history-and-related-properties) that forces an additional query to the database to get the previous snapshot of the workitem.

**Comment by alexvaccaro** [comment]
Hi Giulio, thank you for your comments, I have successfully used `PreviousRevision` to achieve what I was looking for.
