### ISSUE TITLE
Can't get the TFS Aggregator Server Plugin 2.3 Release Candidate to work on TFS 2017 update 2

### ISSUE THREAD

**Issue by musicman3113** [tfsaggregator/tfsaggregator#243]
I installed and imported the policy file, and it isn't working.  I have a test scenario where It when a feature is changed to a different iteration it changes the Target date.  After I reinstalled Aggregator and Successfully updated the policy, Checking the event log, this is what I see.

The description for Event ID 47513 from source TFSAggregator cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Exception encountered processing notification: Method not found: 'Void Microsoft.TeamFoundation.Integration.Server.ICommonStructureService.GetProjectProperties(Microsoft.TeamFoundation.Framework.Server.IVssRequestContext, System.String, System.String ByRef, System.String ByRef, Microsoft.TeamFoundation.Integration.Server.CommonStructureProjectProperty[] ByRef)'. 
Stack Trace:   at Aggregator.Core.Facade.RequestContextWrapper.GetProjectProperties(Uri projectUri)
   at Aggregator.Core.Configuration.TemplateScope.GetTemplateInfo(IRequestContext currentRequestContext, INotification currentNotification) in d:\a\1\s\Aggregator.Core\Configuration\TemplateScope.cs:line 55
   at Aggregator.Core.Configuration.TemplateScope.Matches(IRequestContext currentRequestContext, INotification currentNotification) in d:\a\1\s\Aggregator.Core\Configuration\TemplateScope.cs:line 39
   at Aggregator.Core.EventProcessor.<>c__DisplayClass7_0.<FilterPolicies>b__1(PolicyScope scope) in d:\a\1\s\Aggregator.Core\EventProcessor.cs:line 84
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Aggregator.Core.EventProcessor.ProcessEvent(IRequestContext requestContext, INotification notification) in d:\a\1\s\Aggregator.Core\EventProcessor.cs:line 54
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in d:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 85

the message resource is present but the message is not found in the string/message table

**Comment by giuliov** [comment]
Weird, I tested the MSI on that TFS version. Can you share a sanitized version of your rule?

**Comment by musicman3113** [comment]
Are you referring to the policy file we imported.  How would one sanitize it?



tim


________________________________

**Comment by giuliov** [comment]
By sanitize I mean coping the rule code and replace sensitive information with a placeholder.

**Comment by musicman3113** [comment]
<?xml version="1.0" encoding="utf-8"?>
<AggregatorConfiguration>

    

    
    <runtime debug="false">
        
        <rateLimiting interval="00:00:01.0" changes="5" />
        
        <logging level="Diagnostic" />
        
        <script language="C#" />
        
        <authentication autoImpersonate="false" />
    </runtime>
    
    
    
    
    <rule name="MyFirstRule" appliesTo="Task" hasFields="Title">
        
        <![CDATA[
        logger.Log("Hello, World from {1} #{0}!", self.Id, self.TypeName);
        ]]>
    </rule>
    
	<rule name="CalculateWSJF" appliesTo="Initiative,Feature" hasFields="Microsoft.VSTS.Common.BusinessValue;Microsoft.VSTS.Common.TimeCriticality;KHA.AppDev.SAFe.RiskReductionOpportunityEnablement;KHA.AppDev.SAFe.WeightedShortestJobFirst">
        
        <![CDATA[
        string effortFieldName;
        if (self.TypeName == "Initiative")
          effortFieldName = "KHA.AppDev.Scheduling.RemainingEffort"; // Initiative
        else
          effortFieldName = "Microsoft.VSTS.Scheduling.Effort"; // Feature

		// if any of the numeric fields are blank (null) or if the remaining effort (denominator) is zero then clear the WSJF field.
		if (self["Microsoft.VSTS.Common.BusinessValue"] == null   // Blank BusinessValue
			|| self["Microsoft.VSTS.Common.TimeCriticality"] == null  // Blank TimeCriticality
			|| self["KHA.AppDev.SAFe.RiskReductionOpportunityEnablement"] == null // Blank RiskReductionOpportunityEnablement
			|| self.GetField<double>(effortFieldName, 0d) == 0)  // Blank or Zero effort (prevent divide by zero error)
		{
			self["KHA.AppDev.SAFe.WeightedShortestJobFirst"] = null;
		}
		else
		{
			var costOfDelay = 
				(int)self["Microsoft.VSTS.Common.BusinessValue"] +
				(double)self["Microsoft.VSTS.Common.TimeCriticality"] +
				(int)self["KHA.AppDev.SAFe.RiskReductionOpportunityEnablement"];

			var wsjf = costOfDelay / (double)self[effortFieldName];
			
			self["KHA.AppDev.SAFe.WeightedShortestJobFirst"] = (int)wsjf;

			//logger.Log("costOfDelay={0}", costOfDelay);
			//logger.Log("wsjf={0}", wsjf);
			//logger.Log("e={0}", (double)self[effortFieldName]);
			//logger.Log("bv={0}", (int)self["Microsoft.VSTS.Common.BusinessValue"]);
			//logger.Log("tc={0}", (double)self["Microsoft.VSTS.Common.TimeCriticality"]);
			//logger.Log("rr={0}", (int)self["KHA.AppDev.SAFe.RiskReductionOpportunityEnablement"]);
      
      return (int)wsjf;
		}
        ]]>
    </rule>

	<rule name="SetInitiativeToImplementing" appliesTo="Feature" hasFields="System.State">
        <![CDATA[

		if (self.HasParent()) // if the Feature has a parent Initiative
		{
			//logger.Log("has parent");
			//logger.Log("self state={0}", (string)self["System.State"]);
			if ((string)self["System.State"] == "In Progress") // if the Feature is 'In Progress'
			{
				//logger.Log("yes, self is in progress");
				if ((string)self.Parent["System.State"] != "In Progress") // if the parent Initiative is not 'In Progress'
					self.Parent["State"] = "In Progress";
			}
		}

        ]]>
    </rule>

	<rule name="SetFeatureToInProgress" appliesTo="Product Backlog Item,Bug" hasFields="System.State">
        <![CDATA[

		if (self.HasParent()) // if the PBI/Bug has a parent Feature
		{
			//logger.Log("has parent");
			//logger.Log("self state={0}", (string)self["System.State"]);
			if ((string)self["System.State"] == "Committed") // if the PBI/Bug is 'Committed'
			{
				//logger.Log("yes, self is committed");
				if ((string)self.Parent["System.State"] != "In Progress") // if the parent Initiative is not 'In Progress'
					self.Parent["State"] = "In Progress";
			}
		}

        ]]>
    </rule>

	<rule name="SetFeatureTargetDate" appliesTo="Feature" hasFields="System.IterationPath,Microsoft.VSTS.Scheduling.TargetDate">
        <![CDATA[

		///
		/// Set the Feature TargetDate field if it is blank and the iteration is set to a PI
		///

		logger.Log("TargetDate field is null={0}", self["Microsoft.VSTS.Scheduling.TargetDate"] == null);

		// Date fields are null when plank
		if (self["Microsoft.VSTS.Scheduling.TargetDate"] == null) // is null when field is blank
		{
			string iterationPath = (string)self["System.IterationPath"];
			logger.Log("iterationPath={0}", iterationPath);
			
			// Grab last 8 characters from the iteration path
			string toParse = "";
			if (iterationPath.Length > 7)
				toParse = iterationPath.Substring(iterationPath.Length - 8);

			// Validate PI format (e.g. "2016.Q1A")
			if (toParse.Length == 8 &&
				toParse[0] == '2' &&
				toParse[1] == '0' &&
				toParse[2] >= '0' && toParse[2] <= '9' &&
				toParse[3] >= '0' && toParse[3] <= '9' &&
				toParse[4] == '.' &&
				toParse[5] == 'Q' &&
				toParse[6] >= '1' && toParse[6] <= '4' &&
				(toParse[7] == 'A' || toParse[7] == 'B' || toParse[7] == 'X'))
			{
				logger.Log("IterationPath DOES end in a PI format.");

				// Parse PI string
				int year = System.Convert.ToInt32(toParse.Substring(0, 4));
				int quarter = System.Convert.ToInt32(toParse.Substring(6, 1));
				char quarterPart = toParse.Last();

				logger.Log("PI components: year={0}, quarter={1}, quarterPart={2}", year, quarter, quarterPart);

				var piStartDate = new System.DateTime(year, ((quarter - 1) * 3) + 1, 1);

				if (piStartDate.DayOfWeek == System.DayOfWeek.Tuesday)
					piStartDate = piStartDate.AddDays(-1);
				else
					while (piStartDate.DayOfWeek != System.DayOfWeek.Monday) { piStartDate = piStartDate.AddDays(1); }

				logger.Log("calculated piStartDate={0}", piStartDate);

				System.DateTime piEndDate;

				if (quarterPart.Equals('B'))
					piStartDate = piStartDate.AddDays(7 * 6);
				else if (quarterPart.Equals('X'))
					piStartDate = piStartDate.AddDays(7 * 12);

				piEndDate = piStartDate.AddDays(39);

				logger.Log("setting TargetDate={0}", piEndDate);
				self["Microsoft.VSTS.Scheduling.TargetDate"] = piEndDate;
			}
		}

        ]]>
    </rule>
	
		<rule name="SetSprintTitle" appliesTo="Sprint" hasFields="System.Title,System.IterationPath">
        <![CDATA[
					string iterationPath = (string)self["System.IterationPath"];
					string[] parts = iterationPath.Split('\\');

					if (parts.Length > 0)
						self["System.Title"] = parts.Last().ToString();
					else
					  self["System.Title"] = "No iteration";
        ]]>
    </rule>

		<rule name="SetPITitle" appliesTo="Program Increment" hasFields="System.Title,System.IterationPath">
        <![CDATA[
					string iterationPath = (string)self["System.IterationPath"];
					string[] parts = iterationPath.Split('\\');

					if (parts.Length > 0)
						self["System.Title"] = "PI " + parts.Last().ToString();
					else
					  self["System.Title"] = "No iteration";
        ]]>
    </rule>

    
    
    
    
    
    <policy name="MyFirstPolicy">
        
        <collectionScope collections="DefaultCollection" />
        
        <templateScope name="Scrum" />
        
        
        <projectScope projects="TfsAggregatorTest1" />
        
        
        <ruleRef name="MyFirstRule" />
        
        
        
    </policy>
	
	<policy name="ProductsPolicy">
        
        <collectionScope collections="DefaultCollection" />
        
        
        
        
        <projectScope projects="Products" />

        
        <ruleRef name="CalculateWSJF" />
		<ruleRef name="SetInitiativeToImplementing" />
		<ruleRef name="SetFeatureToInProgress" />
		<ruleRef name="SetFeatureTargetDate" />
		<ruleRef name="SetSprintTitle" />
		<ruleRef name="SetPITitle" />
		
		
        

    </policy>

    

</AggregatorConfiguration>

**Comment by giuliov** [comment]
Try remove the `templateScope` clause: if you see in #234 it stopped working with some TFS breaking change

**Comment by musicman3113** [comment]
That seems to be the issue.  What effects will taking that out have.  I would like to document the change.

**Comment by giuliov** [comment]
It was designed for the scenario where you have many projects but you want to apply the rules only to the subset of projects using a specific Process Template.
The "language" is pretty flexible and you can map rules to projects in many ways.

**Comment by giuliov** [comment]
We found a problem in the MSI: it installed the wrong version of assemblies.
@musicman3113 can you retry with the re-released version?

**Comment by jessehouwing** [comment]
We've released an updated beta version with full support for TFS 2017u2, u3 and TFS 2018.
