### ISSUE TITLE
Aggregator logs status changes to new Discussion control

### ISSUE THREAD

**Issue by einar20** [tfsaggregator/tfsaggregator#244]
Hi

We're running TFS Server 2017 Update 2, with Aggregator v2.2.

I have created aggregator rules that auto-update state of UserStories, based on status changes to their children (task and test status). These updates works fine.

However, we recently moved to the new web form layout provided in TFS 2017.
A new Discussion control is added in the new layout, and I notice that state changes performed by Aggregator, adds an entry to the Discussion field - not only to History as expected.

See attached screenshot
![aggregator_entrytodiscussioncontrol](https://user-images.githubusercontent.com/22055060/29413594-2c28c7e2-835d-11e7-9b41-df83b36bcf09.jpg)

The status message is not from my code, the line of code performing the change of state, does however contain the word "Autoupdated":
`parentUserStory.TransitionToState(parentNewState, "Autoupdated");`

Is there any way I could avoid having Aggregator insert a comment to the Discussion control?

Best Regards,
Einar

**Comment by einar20** [comment]
Tried to add label Question to this post, but just couldn't figure out where and how to add labels...

**Comment by jessehouwing** [comment]
At the moment a log message is always added, which shows up in the
discussion control (always did by the way, but the control is more front
and center now).

Wouldn't be hard to provide away to suppress logging I suppose.

**Comment by einar20** [comment]
An option to suppress logging to Discussion control, would be highly appreciated.

The state change is also logged to History, which should be sufficient
![aggregator_entrytohistory](https://user-images.githubusercontent.com/22055060/29415495-88aac834-8363-11e7-9364-84e278dacdf1.jpg)

It seems like it's only state changes that are logged also to the new Discussion control. Other changes from Aggregator, such as aggregated hours for estimate from child items, is not logged to Discussion, but to History only.

We use the Discussion control to exchange information and comments from different stake holders, and additional entries from background aggregator state updates is not expedient in Discussion - only in History tab

**Comment by einar20** [comment]
Seems like it's not only state update messages from TFS Aggregator being added to Discussion control.
Buildservice also adds updates to field "Fixed in" to Discussion...
Maybe I've misunderstood something, by believing Discussion control was meant for user inputs only

**Comment by giuliov** [comment]
The code touches just the `History` property (see https://github.com/tfsaggregator/tfsaggregator/blob/master/Aggregator.Core/Navigation/StateWorkflow.cs#L96). IIRC there is some magic in TFS that filters history comments that will show in the Discussion pane: we need to understand the logic behind.

**Comment by Crashdummyy** [comment]
Any news on this ? still very annoying...

**Comment by jessehouwing** [comment]
Send a pull request.
