### ISSUE TITLE
Library.GetEmailAddress fails with exception when display name has special characters

### ISSUE THREAD

**Issue by RangerDjanger** [tfsaggregator/tfsaggregator#245]
Calling Library.GetEmailAddress when a username/display name has special characters fails with:

Exception encountered processing notificaiton: TF10158: The user or group name LASTNAME, FirstName (Team) contains unsupported characters, is empty, or is too long.

This looks potentially am issue with the TFS IdentityManagementService?

**Comment by jessehouwing** [comment]
Yeah, ran into this with the TFVC build tasks as well, seems to be a change
in the api validation routines and I haven't found a workaround for it yet,
apart from not using the display name, but feeding it a upn instead.

Unfortunately you may not have the upn available if you're using a identity
field to feed to source the value from.
