### ISSUE TITLE
TFS Aggregator doesn't work on TFS 2017 update 2 (But tests works)

### ISSUE THREAD

**Issue by wedun** [tfsaggregator/tfsaggregator#247]
Hello.
I was update TFS to TFS 2017 update 2. Reinstall TFS aggregator.
Now TFS aggregator doesn't work automatically, but tests via TFSAggregator2.ConsoleApp works fine.
Event Viewer doesn't contains messages from TFSAggregator.
Could you please tell me how can i fix it?

**Comment by giuliov** [comment]
Have you used the [latest MSI](https://github.com/tfsaggregator/tfsaggregator/releases/tag/v2.3-RC1)? Update 2 breaks compatibility (again) and older versions will not work.
The Console app emulates TFS and will work in any case.

**Comment by wedun** [comment]
Yes. i have problem with this version.

**Comment by giuliov** [comment]
Can you check the Plugin version?
```
$pathToAssemblyFile = "C:\Program Files\Microsoft Team Foundation Server 15.0\Application Tier\Web Services\bin\Plugins\TFSAggregator2.ServerPlugin.dll"
[System.Reflection.Assembly]::LoadFile($pathToAssemblyFile).GetCustomAttributesData() | ?{ $_.AttributeType -in ([System.Reflection.AssemblyInformationalVersionAttribute],[System.Reflection.AssemblyConfigurationAttribute]) } | select ConstructorArguments
```
and the TFS version?
```
$highestTFSversion = "{0:N1}" -f (
	Get-ChildItem -Path "HKLM:\SOFTWARE\Microsoft\TeamFoundationServer" |
		Split-Path -Leaf |
		foreach { $_ -as [double] } |
		sort -Descending |
		select -First 1)
(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\TeamFoundationServer\$highestTFSversion" -Name BuildNumber).BuildNumber
```
I expect these results:

Item | Value
-----|-----
Aggregator configuration | Release [TFS 2017.2]
Aggregator build | 2.3.0-RC.1+Branch.release/2.3.Sha.35672d45830283d1cb12b1196acba474eab89a23
TFS build | 15.117.26714.0

**Comment by wedun** [comment]
{"Release [TFS 2017.2]"}
{"2.3.0-RC.1+Branch.release/2.3.Sha.35672d45830283d1cb12b1196acba474eab89a23"}

Build number: 15.117.26714.0

**Comment by giuliov** [comment]
There must be some clues in the Event Log, at least TFS complaining that the plugin raised an exception.  Look also in Touch or add any file in the TFS `Plugins` folder: it forces TFS to reload everything.
Check also the *Microsoft-Team Foundation Server* in addition to classic *Application* log for clues.

**Comment by jessehouwing** [comment]
Are you using the process template scope? That is currently broken due to a
change by the product team that we haven't been able to fix yet.

**Comment by wedun** [comment]
Thank you!
The plugin now works well.
I commented out the line with template scope.

**Comment by jessehouwing** [comment]
I just pushed a change to develop that changes the way project properties are retrieved.

I talked to the product team and they indicated this is what we should now be using. This should fix the template scope, but I haven't actually gone through the full test.

**Comment by jessehouwing** [comment]
Needed to add another Server Assembly to the list of references. It's missing on the build server,

Microsoft.TeamFoundation.Server.Types.dll

**Comment by Pyropace** [comment]
@jessehouwing. Did that resolve the issue? I have issues with update 2 as well. Build from master works ?

**Comment by jessehouwing** [comment]
Still. In develop.

**Comment by kvo181** [comment]
I too commented out the line with template scope and afterwards no more errors with the PlugIn.
Any update on the progress?

**Comment by jessehouwing** [comment]
See: https://github.com/tfsaggregator/tfsaggregator/pull/266
