### ISSUE TITLE
When using 2 Policy Files for two different collections the second policy file doesn't work

### ISSUE THREAD

**Issue by musicman3113** [tfsaggregator/tfsaggregator#248]
Is it possible to have two different collections in TFS to use two different policy files that are independent of eachother.  We have two distinct teams in our organization using our TFS on premise server.  There are two different policy files because each team is independent of eachother and use different policies for the Aggregator.  We have been having trouble getting this to work correctly, and need assistance.

**Comment by jessehouwing** [comment]
A single file is required, but you can scope a set of rules to a single
collection using a colletionscope.

**Comment by musicman3113** [comment]
If i attached two files, would you be able to add the collection scope for the two collections?  I'm not sure how to do that.(url)

[policy files.zip](https://github.com/tfsaggregator/tfsaggregator/files/1315272/policy.files.zip)

**Comment by jessehouwing** [comment]
You can only have one file, so add the rules from the first file to the
second and then create a second policy tag selecting the right rules and
scoping it to the correct collection.
