### ISSUE TITLE
How to  install this tool in VSTS?  I am unable to find the option to install,  please provide a setup notes

### ISSUE THREAD

**Issue by ramakrishnaAeries** [tfsaggregator/tfsaggregator#249]
Hi Team

How to  install this tool in VSTS?  I am unable to find the option to install,  please provide a setup notes.

**Comment by giuliov** [comment]
See https://tfsaggregator.github.io/admin/install-webhooks/

You need to provide a hosting environment for it, then configure both VSTS and Aggregator so they can talk to each other.
You can use the *Deploy to Azure* button on https://github.com/tfsaggregator/tfsaggregator-webhooks to quickly get the hosting environment, but you still have to follow the steps above.

**Comment by giuliov** [comment]
By the way, you should have used the *Q&A* section instead of *User Reviews* in the Marketplace. Now I cannot answer there.

**Comment by ramakrishnaAeries** [comment]
Thank you so much for reply,
I will check and let you know if I have any issues.

Thanks,
Ramakrishna.Tankala,
Tfs Administrator,
Ramakrishna.Tankala@DTIGlobal.com<mailto:Ramakrishna.Tankala@DTIGlobal.com>,
Mobile: (+91) 9652587022.
__________________________________________________
1st  & 8th Floor, # 8-2-682, Lakshmi Cyber Centre, Road No. 12,
Banjara Hills, Hyderabad – 500 034 India

**Comment by ramakrishnaAeries** [comment]
Sure, Thank you.

Thanks,
Ramakrishna.Tankala,
Tfs Administrator,
Ramakrishna.Tankala@DTIGlobal.com<mailto:Ramakrishna.Tankala@DTIGlobal.com>,
Mobile: (+91) 9652587022.
__________________________________________________
1st  & 8th Floor, # 8-2-682, Lakshmi Cyber Centre, Road No. 12,
Banjara Hills, Hyderabad – 500 034 India
