### ISSUE TITLE
How add a<br> tag at the end of any html field avoiding recursion?

### ISSUE THREAD

**Issue by francesco-sclano** [tfsaggregator/tfsaggregator#252]
In order to avoid a bug with AIT WordToTFS that cuts last text line in exported html fields of workitem in Word, the solution seems to be adding a carriage return (new line) at the end of every html field (Description, Aceeptance Criteria etc.). How can I automatically add this carriage return (new line or </br> tag) avoiding infinite recursion?

**Comment by jessehouwing** [comment]
Check whether it already ends with the right number of newlines? Only add
one if needed.

**Comment by tfs-dev** [comment]
Ok and is there a way to recognize if a field is of html type?

**Comment by giuliov** [comment]
IIRC the answer is negative. We should expose the [`FieldDefinition`](https://msdn.microsoft.com/en-us/library/microsoft.teamfoundation.workitemtracking.client.fielddefinition(v=vs.120).aspx) so you can access the [`FieldType`](https://msdn.microsoft.com/en-us/library/microsoft.teamfoundation.workitemtracking.client.fieldtype(v=vs.120).aspx), but we don't.

It is an easy patch, if you want to submit a PR

**Comment by tfs-dev** [comment]
If I set  <rateLimiting interval="00:00:01.00" changes="5" /> means that TFSAggregator stops anyway after maximum five execution on same workitem? Or it means that in 1 second there can be maximum 5 execution of TFSAggregator?

**Comment by jessehouwing** [comment]
Instead of adding the br at the end every time, you could check whether there is br at the end right now, if not add it.

That prevents any recursion, since the newline will be present the next run.
