### ISSUE TITLE
What happen to System.Description of HTML type containing an image if it is modified by modication through TFSAggregator?

### ISSUE THREAD

**Issue by francesco-sclano** [tfsaggregator/tfsaggregator#253]
Consider this scenario:
- I have a System.Description of HTML type containing an image 
- I want append through TFSAggregator a string at the end of System.Description
What happen to the image contained in System.Description after appending a String to System.Description? I guess that image in System.Description is memorized as path to a image file internally created by TFS, if is actually in this way there is no problem. Is it right?

**Comment by jessehouwing** [comment]
Try it. I suppose the URL will be a full path.
