### ISSUE TITLE
How manage consecutive publishes from Word/Excel

### ISSUE THREAD

**Issue by francesco-sclano** [tfsaggregator/tfsaggregator#256]
I set many rules that obviously increment revision of affected workitems. How can I manage consecutive publishes from Excel/Word. Is the only way communicate to TFS users to perform a refresh after publish? Is there any other workaround/best practice?

**Comment by jessehouwing** [comment]
Unfortunately no way to inform users that the server did things with their
work items. Education is your only hope.
