### ISSUE TITLE
Polices file can be replaced at runtime in any windows version?

### ISSUE THREAD

**Issue by francesco-sclano** [tfsaggregator/tfsaggregator#257]
I'm using on my local environment win 7 + tfs 2017 update 1 on premises + last TFSAggregator stable version. When I replace polices file I have first to stop iis otherwise tfs will block. I confirm this block in other local environments with same configuration.  I'd like to know if have to do the same in my production environment where I have win server 2012 r2. As you can guess stopping iis in production environmentis is not good for TFS users.

**Comment by giuliov** [comment]
Normally you can simply replace the .polices files with the new version and TFS will take care of reloading the Server Plugin. I noticed a problem when SSH is turned on: is that your case?
If you need to "turn off" and on TFS there is a command line utility to do it cleanly: [`tfsservicecontrol`](https://docs.microsoft.com/en-us/vsts/tfs-server/command-line/tfsservicecontrol-cmd).

**Comment by tfs-dev** [comment]
SSH turned on is not my case.

**Comment by giuliov** [comment]
Maybe it is Win7. Honestly I never tested on anything less than Windows Server 2012 R2.

**Comment by tfs-dev** [comment]
How much time usually takes replacement of polices file before TFS comes back online?

**Comment by jessehouwing** [comment]
Should be in seconds. Same time it takes to do. An app pool recycle.
