### ISSUE TITLE
Is it blocking for TFS users an error occurred in TFSAggregator rules?

### ISSUE THREAD

**Issue by francesco-sclano** [tfsaggregator/tfsaggregator#258]
I'd like to know if I have to manage with try catch possible errors occurred in my rules. By default does TFS Aggregator catch any kind of error? Does TFS Aggregator allow users to continue using TFS in case of any error occurred in my rules?

**Comment by jessehouwing** [comment]
Aggregator runs after the user changes have already been saved. So if a
rule errors out we log that to the event log and continue processing other
rules.

**Comment by giuliov** [comment]
@francesco-sclano if you are worried about TFS reliability, be assured that TFS runs all extensions (including Aggregator) in separate AppDomain to protect itself.
