### ISSUE TITLE
Is string.InStr method available in TFSAggregator?

### ISSUE THREAD

**Issue by francesco-sclano** [tfsaggregator/tfsaggregator#259]
Is string.InStr method available in TFSAggregator? How can I check what methods are available/exposed? I red https://tfsaggregator.github.io/using/scripting/ but I didn't understand what methods are available. I tryied to use string.Instr but I received following error: The name 'Instr' does not exist in the current context.

**Comment by giuliov** [comment]
No, it is not.
Basically, you can only reference Aggregator API, System and Microsoft.TeamFoundation.WorkItemTracking. See the [GetAssemblyReferences](https://github.com/tfsaggregator/tfsaggregator-core/blob/cece14210aae5c05710879a6cb56328b8917d8d7/Script/DotNetScriptEngine%7BTCodeDomProvider%7D.cs#L40-L64) method.

You can update the docs in https://github.com/tfsaggregator/tfsaggregator-docs-hugo through a Pull Request.

**Comment by robnelder** [comment]
I haven't used this in TFSAggregator, but you might find that String.IndexOf can do what you need. It is in the System namespace.

[https://msdn.microsoft.com/en-us/library/system.string.indexof(v=vs.110).aspx](https://msdn.microsoft.com/en-us/library/system.string.indexof(v=vs.110).aspx)
