### ISSUE TITLE
"TF30063: You are not authorized to access URL"

### ISSUE THREAD

**Issue by jaredwhite** [tfsaggregator/tfsaggregator#26]
While trying to implement this solution on our TFS Server, every run of the TFS Aggregator spits out this error: "TFSAggregator: Exception encountered processing Work Item [######]: TF30063: You are not authorized to access https://tfs.abcde.com/tfs/DefaultCollection."

It does this irrespective of which credentials are passed in by the aggregatoritems.xml. I tried this without credentials, and with numerous other sets, including our root TFSservice user to no effect. 

I'm still pretty sure that I'm doing something wrong, but not sure what it could be. I have the rest of the Stack Trace handy if it would be beneficial.

**Comment by giuliov** [comment]
Hi Jared,
this version is missing the patch supporting User/Pwd in the configuration file. Your options are:
 1. give permission to the user running the plugin, i.e. the "TFS Service Account"
 2. use [patch 14867](https://tfsaggregator.codeplex.com/SourceControl/list/patches) from Codeplex

I would favor the first option, to avoid clear text password in a configuration file.
