### ISSUE TITLE
unable to use System.Xml to parse TestCase Steps

### ISSUE THREAD

**Issue by djohnson7789** [tfsaggregator/tfsaggregator#260]
Hi!

I may be pushing the limits of the plugin here, but I was wondering if it was possible to use the System.Xml types to work with Test Steps/Results.  If not, is there potentially a workaround you'd suggest?

Thanks,
-David

**Comment by jessehouwing** [comment]
I would be amazed if tfs doesn't load the system.xml into memory. But
you'll have to use the full name space prefix because we don't include the
right using statements.

The powershell handler would also be able to use the built in powershell
support for xml.
