### ISSUE TITLE
Hundreds of Event Logs say the same thing, although intergration is running, and working somewhat.

### ISSUE THREAD

**Issue by musicman3113** [tfsaggregator/tfsaggregator#261]
Source:  TFS Aggregator

General Tab:
The description for Event ID 42 from source TFSAggregator cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

FeatureUpdate: Last stateNew

the message resource is present but the message is not found in the string/message table

**Comment by jessehouwing** [comment]
Looks like logging is set at a high level.

**Comment by jessehouwing** [comment]
See https://tfsaggregator.github.io/admin/logging/

**Comment by musicman3113** [comment]
Our logging level is diagnostic, isn't that what it should be?

**Comment by jessehouwing** [comment]
Not if you don't want 3000 events in your event log every hour ;).
'Warning'  or 'error'  would be normal.
