### ISSUE TITLE
How to get Work Items by a field diferente than ID

### ISSUE THREAD

**Issue by helhaddad** [tfsaggregator/tfsaggregator#264]
Please can i create a rule to get a collection of  Work Items by custom field # the Id

Select Work Items from dataBase where customfield1 = "xxx" and  customfield2 = 100

Thanks in advance for your response

**Comment by jessehouwing** [comment]
Looks. Like this can't currently be done. We don't expose a query option
that doesn't require related links.

**Comment by helhaddad** [comment]
Thanks a lot Jesse for your response.

I want to import work items (tasks) from excel file and in the import i want to select a specified User story to created on it a related link to the imported task.

Do you have any solution for this please. ?

**Comment by jessehouwing** [comment]
Script the import using powershell and the client object model? Or provide
us with a PR that queries other work items using Linq2wiql.

**Comment by helhaddad** [comment]
I don't understand your Idea can you explaine it to me please with more detail ?

**Comment by giuliov** [comment]
If I understand @helhaddad request, you want to use TFS Aggregator interactively. @jessehouwing says that its design is non-interactive, event-driven server plugin: if you want an interactive tool, you have to write your own, using C# or Powershell or else plus the Client Object Model (or the REST API if you use a recent version of TFS).

**Comment by helhaddad** [comment]
i want just to get work item use the function store.GetWorkItem(id)  with a field diferent than the id it's possible?

**Comment by jessehouwing** [comment]
No.

**Comment by helhaddad** [comment]
I don't know if it's possible to create a new function to this work.
I propose to add a function like public IWorkItem GetWorkItem(int IterationId, string AreaPath).
can i do this ??

**Comment by jessehouwing** [comment]
I'd suggest adding a function that can execute a wiql query, take
parameters and as long as the return values contain a work item ID, it
allows you to iterate over those work items.

**Comment by helhaddad** [comment]
Thanks a lot @jessehouwing for your help, it's a very good idea i like it
