### ISSUE TITLE
[QUESTION]: Sendemail body from text file?

### ISSUE THREAD

**Issue by p13x** [tfsaggregator/tfsaggregator#269]
Hi,
Is it possible to get email body from a file?

**Comment by jessehouwing** [comment]
You can use the classes from system.io, you will just have to use their
fully qualified names pace as we do not import them by default.

**Comment by p13x** [comment]
Hi,
It works.

Example:
`string path = @"c:\temp\text.txt";
string body = System.IO.File.ReadAllText(path);`

Thank you for advice.
