### ISSUE TITLE
TFS 2017 Send Email doesn’t work in my environment

### ISSUE THREAD

**Issue by helhaddad** [tfsaggregator/tfsaggregator#270]
Hi,
I can't send email in my environment (TFS 2017 and Aggregator 2.3.0)

string to = "test@gmail.com";
string subject = "Sent from a Rule";
string body = "It worked!";
Library.SendMail(to, subject, body);

the email configuration is done in TFSAdministration, I receive the modificatiopn of the work Items by Email

Thanks in advance

**Comment by helhaddad** [comment]
any help please

**Comment by jessehouwing** [comment]
Hard to tell.

**Comment by helhaddad** [comment]
Please how can i Troubleshoot this rule??

**Comment by jessehouwing** [comment]
@helhaddad that's hard to tell as well. If the rule doesn't throw an exception, the email could have gotten lost anywhere in the myriad of servers that are involved int he actual email distribution.

Troubleshooting and logging guidance:
 * https://tfsaggregator.github.io/admin/troubleshooting/
 * https://tfsaggregator.github.io/admin/logging/
