### ISSUE TITLE
How use DateTime format in TFS Aggregator?

### ISSUE THREAD

**Issue by denisza** [tfsaggregator/tfsaggregator#272]
Hi, friends!
Help me please in my problem.
How use DateTime in fields with data type DateTime.

For examle:
self["t3"] = DateTime.Now;

How does it do correctly?

Thanks!

**Comment by jessehouwing** [comment]
Self[xxx].Value = Datetime etc.

You can't assign directly to the field object.

**Comment by denisza** [comment]
Thank you!
How am I can get DateTime.Now in TFS Aggregator?

**Comment by helhaddad** [comment]
Hi,

I created a rule in the policy file this rule assigned DateTime.now to a specified feild in a specified case when i test the rule i have this error

[Error]       19.795 Error CS0103 in script 'XXXRule' at line 7, column 46: The name 'Datetime' does not exist in the current context

help please

**Comment by jessehouwing** [comment]
Capital T in Time.

**Comment by helhaddad** [comment]
The same error message, I use Aggregator 2.3 version with TFS 2017 !

**Comment by giuliov** [comment]
Have you tried `self["t3"] = System.DateTime.Now;` ?

**Comment by denisza** [comment]
Oh really! It worked! Thank you!
