### ISSUE TITLE
TFS Aggregator

### ISSUE THREAD

**Issue by jainat** [tfsaggregator/tfsaggregator#273]
I upgraded to tfs 2018 from 2017 and I am facing issues with the child items are not getting applied to parent in the target date(The cascading is not happening from the parent to the child). I feel that the tfs aggregator is not supporting the TFS 2018 version. Any taughts?

**Comment by jessehouwing** [comment]
We do not yet have a supported 2018 version. A few contributors are
currently looking into changing the solution structure to support all the
different dependencies needed to support so many server side versions due
to the constant breaking changes in the server api.

**Comment by dasMulli** [comment]
@jessehouwing speaking of which, I wrote you an email but probably to the wrong address. Could you write me a line to the one in my profile?

**Comment by ArieHein** [comment]
@jainat its quite obvious from the main page and the GitHub repo readme file, that Aggregator doesn't support TFS 2018 yet including other issues already opened about it. My thought is that you need to do rethink how you do plan upgrades of complex and crucial products like TFS

**Comment by jessehouwing** [comment]
See: https://github.com/tfsaggregator/tfsaggregator/pull/266
