### ISSUE TITLE
Is there an original value for link count?

### ISSUE THREAD

**Issue by jdshkolnik** [tfsaggregator/tfsaggregator#275]
Hi,

I aggregate effort values for all of a feature's child work items (mainly PBIs). This is triggered at the PBI level and works fine. What I'm missing is a way to trigger the feature when a PBI has been deleted. I can't do it at the PBI level since the PBI no longer exists.

I think I'd want to handle it by comparing the original count of a feature's child links to the new count and recalculate if they aren't the same. Is there an original value for link count?

**Comment by jessehouwing** [comment]
I'm not sure whether the link count field is updated. But we currently do not expose the links on the older revisions. I've looked into that in the past, but unfortunately the links collection uses a different set of classes and my last attempt ran into "too much impact" causing me to abandon it for now.

**Comment by jdshkolnik** [comment]
How would you handle the triggering of a recount for the parent of a deleted child?

**Comment by jessehouwing** [comment]
We do detect deletes. But I think you won't be able to access the details. I'm not sure whether TFS will trigger a change on the parent. I currently have no active involvement with a client using this tool, so I'd suggest asking this in the Slack channel, I suspect that others may have experimented with this.

The whole "delete" option is a nasty one...

**Comment by giuliov** [comment]
I can only think of is exposing the previous state of the deleted work item to rules, using AsOf behind the scene.

**Comment by jessehouwing** [comment]
I suppose the best way to figure this one out is by putting it to the
product team. I may be able to arrange a talk about these kinds of topics
at the Mvp summit. I suppose Edwald would be the first person to talk to.

**Comment by jessehouwing** [comment]
This commit may help. 
https://github.com/tfsaggregator/tfsaggregator-core/tree/features/revision-links 

I'd like to revisit Links completely to expose External, Related and other link types as well, but this is a start.
