### ISSUE TITLE
<function> not accepted ?

### ISSUE THREAD

**Issue by codeknox** [tfsaggregator/tfsaggregator#277]
Hey guys,

I'm following https://tfsaggregator.github.io/using/scripting/#code and creating a function, like:
```
<function><![CDATA[
  int MyFunc() { return 42; }
]]></function>
```
but when run, I get error:

`The element 'AggregatorConfiguration' has invalid child element 'function'. List of possible elements expected: 'rule, policy'.`

**Comment by jessehouwing** [comment]
What version are you running?

**Comment by jessehouwing** [comment]
You a clue?

**Comment by IronGem** [comment]
Are you asking for further information?  Let me know what you need to help track this down.  Thank you.

**Comment by jessehouwing** [comment]
I think the function needs to be down in the rules section of the config, not in the root level.

**Comment by IronGem** [comment]
So I should nest `<function>` inside a `<rule>`? Like this:
```
<AggregatorConfiguration>
  <runtime>
    --
  </runtime>
  <rule name="name">
    <![CDATA[
      --
    ]]>
    <function>
      <![CDATA[
        --
      ]]>
    </function>
  </rule>
  <policy name="name">
    --
  </policy>
</AggregatorConfiguration>
```
If so, would that function be able to be used by other rules?

**Comment by giuliov** [comment]
No, the function section precedes rules, e.g.

```
<AggregatorConfiguration>
  <runtime>
    --
  </runtime>
    <function><![CDATA[
        --
]]></function>
  <rule name="name"><![CDATA[
      --
]]></rule>
  <policy name="name">
    --
  </policy>
</AggregatorConfiguration>
```

The ultimate truth is the [XML schema](https://github.com/tfsaggregator/tfsaggregator-core/blob/master/Aggregator.Core.Plugin/Configuration/AggregatorConfiguration.xsd); you may notice that the [doc page](https://tfsaggregator.github.io/using/policy-syntax/) follows the same order.

**Comment by giuliov** [comment]
Correct: you must explicitly pass those objects to your methods; something like this
```
    <function><![CDATA[
void DoNothing(IWorkItemExposed self, IWorkItemRepositoryExposed store, IRuleLogger logger, IScriptLibrary library)
{
  return;
}
]]></function>
  <rule name="name"><![CDATA[
      DoNothing(self,store, logger, library);
]]></rule>
```
(untested code, just a guidance, you can pass just the object needed by the method)
