### ISSUE TITLE
tfs aggregator not allow to update all work items for Task entity.

### ISSUE THREAD

**Issue by shaykpent** [tfsaggregator/tfsaggregator#278]
Hello

i'm using tfs aggregator 2.2 and it force me to enter list of work items to apply the rule i defined (sum fields on task entity).
the console app works fine and it updates the specific work items successfully.   
is it possible to update all work items under task entity (without mention specific work items) ?

Thanks

**Comment by jessehouwing** [comment]
No. We do not provide that functionality, but it wouldnt be hard to pass a
WIQL parameter to the console app and handle it as input.

We're open for pull requests.

Not sure how you'd want to trigger a rule on all tasks from the webservice,
I'd highly recommend not to do that due to performance reasons.

**Comment by giuliov** [comment]
The support for WIQL is already working in some development branch; obviously is limited to the ConsoleApp to solve the scenario #205 .

**Comment by shaykpent** [comment]
Hello

Thanks for your reply.
We are working with on-premise TFS (installed server plugin)
Not the web service.
Is it possible to apply this for each new opened tasks?



Sincerely,

Shay Kravitz
QA Engineer
PENTAGON 2000 Software, Inc
SOFTWARE EMPOWERING THE ENTERPRISE

Echad Haam 9
Shalom Tower
17th Floor
6525101
Tel Aviv - Israel
Tel:  +972-3-516-6566 Ext: 117
Fax: +972-3-516-6885

shay.kravitz@pentagon2000.com<mailto:shay.kravitz@pentagon2000.com>
www.pentagon2000.com<blocked::http://www.pentagon2000.com>

Register for Training<http://www.pentagon2000.com/contact.asp?newsid=76>
Join our Mailing List<http://www.pentagon2000.com/support.asp>
Payments via PayPal<https://www.paypal.me/pentagon2000>

[logos-for-signature_32Y_080118_all]

CAUTION - This message may contain privileged and confidential information intended only for the use of the addressee named above. If you are not the intended recipient of this message you are hereby notified that any use, dissemination, distribution, or reproduction of this message is prohibited. If you have received this message in error please notify Pentagon 2000 Software, Inc. immediately. Any views expressed in this message are those of the individual sender and may not necessarily reflect the views of Pentagon 2000 Software, Inc.

**Comment by shaykpent** [comment]
Thanks Giulio

How can I know that the plugin installed on my tfs?
I ran the console app with specific work items and it worked (it calculate the total work = dev work + qa work for specific work items)
What I want to see is on my tfs is:
Opening new task on tfs and enter fields: dev work + qa work will calculate in total work field (same as in console app)
Is it possible to do it ? or should I do it only from the console app?



Sincerely,

Shay Kravitz
QA Engineer
PENTAGON 2000 Software, Inc
SOFTWARE EMPOWERING THE ENTERPRISE

Echad Haam 9
Shalom Tower
17th Floor
6525101
Tel Aviv - Israel
Tel:  +972-3-516-6566 Ext: 117
Fax: +972-3-516-6885

shay.kravitz@pentagon2000.com<mailto:shay.kravitz@pentagon2000.com>
www.pentagon2000.com<blocked::http://www.pentagon2000.com>

Register for Training<http://www.pentagon2000.com/contact.asp?newsid=76>
Join our Mailing List<http://www.pentagon2000.com/support.asp>
Payments via PayPal<https://www.paypal.me/pentagon2000>

[logos-for-signature_32Y_080118_all]

CAUTION - This message may contain privileged and confidential information intended only for the use of the addressee named above. If you are not the intended recipient of this message you are hereby notified that any use, dissemination, distribution, or reproduction of this message is prohibited. If you have received this message in error please notify Pentagon 2000 Software, Inc. immediately. Any views expressed in this message are those of the individual sender and may not necessarily reflect the views of Pentagon 2000 Software, Inc.

**Comment by giuliov** [comment]
Check the content of the Plugin directory, e.g.
`dir C:\Program Files\Microsoft Team Foundation Server 15.0\Application Tier\Web Services\bin\Plugins\TfsAgg*.dll`
for 2017, `14.0` for 2015 etc.

The Console shares the Rule interpreter (not really an interpreter, but I do not have a better name) with the Plugin, so if it works with one it should work with the other.
The most frequent issue is related to permissions (Console use windows auth, the Plugin can use additional authentication methods, but it runs as the TFS user).

One caveat: do not expect that the UI (web or Visual Studio) automatically refresh: Aggregator receive an event _after_ data has been saved and talks directly to API, bypassing user UI.
One must refresh to see changes introduced by Rules, maybe after many seconds (TFS events are asynchronous).

**Comment by shaykpent** [comment]
Giulio

Thanks for your help
I’m using TFS 2013 Update 5.
TFS aggregator 2.2
I copied all TfsAgg*.dll and policy file to plugin folder.

To:
C:\Program Files\Microsoft Team Foundation Server 12.0\Application Tier\Web Services\bin\Plugins

When loading the visual studio (2015) I get this error in event log (see attached)

Looks like something is wrong with the aggregator plugin

What could be the reason for this ?




Sincerely,

Shay Kravitz

**Comment by giuliov** [comment]
If you haven't used the MSI, you have to be careful to build the assemblies using the right configuration for your TFS. The error looks like you are using a plugin built for a different version of TFS.
You can find notes on how to build and install the plugin at https://tfsaggregator.github.io/.
