### ISSUE TITLE
How do I query if a field exists in self.Parent

### ISSUE THREAD

**Issue by IronGem** [tfsaggregator/tfsaggregator#279]
I would like to write a rule that checks if a field exists in the parent before pulling down information similar to:
>if (self.HasParent() && self.Parent.HasField["Field.Name"]){
        self["Field.Name"] = self.Parent["Field.Name"]
}

I just want to make sure that the parent has Field.Name in its WIT Definition before I try to pull down the info so it doesn't throw.  Is there a way to accomplish this?
Thanks.

**Comment by giuliov** [comment]
As of today, you can't: there is no method like `HasField`.
The nearest result is to check the `TypeName` property to infer if the Parent has the field, and wrap your code in a `try`..`catch` block if the field is still missing, e.g.
```
var okTypes = new string[] { "Feature", "User Story" };
string myField = "Field.Name";
if (self.HasParent() && okTypes.Contains(self.Parent.TypeName)) {
  try {
    self[myField] = self.Parent[myField];
  } catch (Exception e) {
    logger.Log(LogLevel.Warning, "{0} has no {1} field", self.Parent.TypeName, myField);
  }
}
```

```

**Comment by IronGem** [comment]
Would 
`self.Parent["Field.Name"].Status == FieldStatus.Valid`
return true if the field didn't exist, or would that throw an exception?

**Comment by SAnCherepan** [comment]
Try using LINQ:
`bool hasField = self.Parent.Fields.Any(field => field.ReferenceName == "FieldRefName");`
Do not forget to use appropriate reference name, e.g. "System.State".

**Comment by IronGem** [comment]
@SAnCherepan This method worked perfectly.  Thank you very much for the suggestion.
