### ISSUE TITLE
Want to verify that I installed the right plugin

### ISSUE THREAD

**Issue by mclagett** [tfsaggregator/tfsaggregator#284]
Hi --

I am running TFS Version 14.102.25423.0 (which if I understand correctly is 2015 Update 3).  I ran the https://github.com/tfsaggregator/tfsaggregator/releases/download/v2.4.0-RC1/TFSAggregator-2.4.0-RC.1-release.msi installer and it appeared to install correctly, although I was trying to install the server plugin and not deploy the web service.  I noticed, however, that the binaries got installed into Application Tier/Web Services/bin/Plugins.   I haven't been able to get my policy to work yet and I just wanted to make sure that this is actually the server plugin that I installed (even though it is under the Application Tier/Web Services folder).  Could someone please confirm that I do in fact have the server plugin installed?

Thanks very much.

Regards,

Mike

**Comment by jessehouwing** [comment]
The plugin is installed into the tfs application tier. You have the right
package.

**Comment by mclagett** [comment]
Thank you.  But I realize now that I installed the newest release candidate and probably should have installed the latest stable version (2.2.1).  Any idea how to uninstall, because it is telling me a newer version has been installed and not letting me install the older version.

**Comment by mclagett** [comment]
Never mind.  Stupid me.  Just windows uninstall.

**Comment by jessehouwing** [comment]
We're about to promote 2.4.0 to final. I'd consider it more stable than
2.2.0
