### ISSUE TITLE
Unable to run wizard for VSTS

### ISSUE THREAD

**Issue by mattel92** [tfsaggregator/tfsaggregator#286]
Hi All,

I am completely new to this so please forgive my inexperience. 
I am trying to set up VSTS as a webservice on a VM but whenever I run the wizard it fails. Recently it give me a new error, usually I just get error failed,  "The current api-version doesnt' support RBAC users. Please use a newer version instead". My account has not changed so I am not sure why I am now getting this error.

![errorrbac](https://user-images.githubusercontent.com/38550430/39032100-ee7cf6d6-4420-11e8-8e1f-f3e738690876.PNG)

I tried finding manual instructions on how to set it up but I cannot find any, not sure if I am just not seeing it.

Could anyone assist in helping me set this up or pointing me in the right direction?

**Comment by curtis-wk** [comment]
Not sure if this will help but I do get the same issue via our corp tied instances but it works on my personal msdn instance (also had to run it outside of the office network).   Web deployment does still work for me via the msdn did it about 2 days ago while troubleshooting a different issue.
