### ISSUE TITLE
500 error with every post and updating already deployed site

### ISSUE THREAD

**Issue by DanHibbert** [tfsaggregator/tfsaggregator#288]
Hi,
We are using VSTS and had setup TFS aggregator on Azure around October 2017
I'm getting a consistent 500 error with every post to the site and I'm struggling to find the log file.  I've gone onto the site and via Diagnostic Console trawled through every folder and log file but can't find a reference to the problem.

For Info : https://linklaterstfsaggregator.azurewebsites.net/api/workitem returns hello
Files amended - HelloWorld.policies and web.config

I wondered whether I need to update the site with the latest code and how I could do that

Thanks in advance
Dan

**Comment by DanHibbert** [comment]
Ignore me on log files - got that sorted.  Have updated PATToken but looking at the logs, it's returning a 404 on the VSTS site.  Have checked the url from the logs and all is ok.  Then updated the PAT token but still with no joy.

**Comment by giuliov** [comment]
We found some bug since last year, so I suggest updating to the latest version from `develop`, it will be merged when we finish the deployment script. **Careful:** you must build and deploy yourself.

**Comment by DanHibbert** [comment]
Thanks for this - will try when I’m out of a conference and report back
