### ISSUE TITLE
How verify if only stack rank field has been modified?

### ISSUE THREAD

**Issue by francesco-sclano** [tfsaggregator/tfsaggregator#289]
Is there any way to identifiy if only stack rank field has been modified? I asked it because I already have a properly working rule that modifyies a custom field named ChangedByUser only on certain conditions. I'd like to add to these conditions following new condition: if only stack rank is modified, the ChangedByUser custom field must not be updated.

About stack rank, I remember you that for example it can be modified alone on workitem X when a user inserts/moves a workitem Y in a position above X. I know that stack rank is a random value and not a sequential number, but in some cases this does not guarantee that stack rank of X is not modified when a user inserts/moves a workitem Y in a position above X.

**Comment by giuliov** [comment]
It is a bit expensive because you have to look at previous revisions (`self.PreviousRevision.Fields` etc).
In all fairness, TFS/VSTS tell us which fields have changed, but we never exposed this detail to help in your specific scenario.
