### ISSUE TITLE
Is there a way to access the value of any revision of a field?

### ISSUE THREAD

**Issue by francesco-sclano** [tfsaggregator/tfsaggregator#290]
Besides self.LastRevision explained at https://tfsaggregator.github.io/using/field-history/, I'd like to know if is there a way to access the value of any revision of a field. This can be useful to perform many operations (rollback, baselines comparison ecc.).

**Comment by giuliov** [comment]
Should be `self.PreviousRevision.Fields["`_name_`"].Value`

**Comment by francesco-sclano** [comment]
This is ok for previous revision but what if I want to obtain the value of a field in a revision older than previous? As instance, if the current value of revision is 50 and I want to obtain the value of System.Description field at revision 5. From revision 5 to revision 50 the System.Description field value can be changed many times (max 45 times). In general I would like to know if there is a way to access the value of a field in any revision.
