### ISSUE TITLE
MakeNewWorkItem doesn't support self as an WorkItem project reference

### ISSUE THREAD

**Issue by yan95g** [tfsaggregator/tfsaggregator#291]
**Steps to reproduce:**
1) create any rule that has following line to create workitem: for example 
var childTaskDev = store.MakeNewWorkItem(self, "Task");
2) Compile rule

**Expected results:**
new work item is created during rule execution

**Actual results:**
following exception is thrown: 
[Verbose]     48.866 Building Script Engine for C#
[Error]       50.706 Error CS1502 in script 'AutogenerateTasksOnActive' at line 12, column 25: The best overloaded method match for 'Aggregator.Core.Interfaces.
IWorkItemRepositoryExposed.MakeNewWorkItem(string, string)' has some invalid arguments
[Error]       50.706 Error CS1503 in script 'AutogenerateTasksOnActive' at line 12, column 47: Argument 1: cannot convert from 'Aggregator.Core.Interfaces.IWork
ItemExposed' to 'string'

**Workaround**: just get Project string info from WI for example: var childTaskDev = store.MakeNewWorkItem((string)self["System.TeamProject"], "Task");  

**Additional information:** example was taken from documentation page - https://tfsaggregator.github.io/using/objects-reference/store-object/
var newWorkItem = store.MakeNewWorkItem(self, "Bug");

**Comment by jessehouwing** [comment]
Should be fixed in latest develop branch. Patched with backwards compat.
