### ISSUE TITLE
Log exact build number

### ISSUE THREAD

**Issue by jessehouwing** [tfsaggregator/tfsaggregator#292]
To help support others remotely it's pretty useful to know the exact build numbers of the aggregator running in their environment.

We should log an initializer event the first time the subscriber runs. In the event log the exact build numbers and possible other useful data for debug purposes.

**Comment by giuliov** [comment]
Is there already: the full version number is calculated by GitVersion and logged as the first message, see `ILogEvents.HelloWorld`. Maybe you look for something additional?
