### ISSUE TITLE
Installer doesnt detect TFS2018

### ISSUE THREAD

**Issue by danielstefanescu** [tfsaggregator/tfsaggregator#294]
TFSAggregator-2.4.0-RC.2.2-release.msi doesn't detect TFS 2018 Update 2 - 16.131.27701.1

**Comment by jessehouwing** [comment]
I think I already pushed the update to the develop branch. Needs to be
cherry picked to release.

**Comment by jessehouwing** [comment]
Updated develop with the rigth version number.

**Comment by jessehouwing** [comment]
Added a release (beta) with these changes. There are a few other fixes in that build that I want to test more before making it a RC or releasing 2.4.0 final.
