### ISSUE TITLE
Planning: TFS Aggregator 3.0

### ISSUE THREAD

**Issue by jessehouwing** [tfsaggregator/tfsaggregator#300]
Looking at the current state of the TFS aggregator we've gotten quite far with limited capacity. To continue to support this project past 2019 we'll need to do another serious investment (port away from the TFS SDK to the REST client for VSTS and TFS versions coming after 2018.

We also receive more requests for "more powerful" interactions. This is what we may be planning going forward.

Before we start. **What would you like to see in TFS Aggregator 3.0**?

Things we're already thinking of include:

* [ ] Fluent links, support multiple link types
* [ ] Trigger only when a specified field changes (take from notification)
* [ ] Port WorkItemClient to VSTS REST API
  * [ ] Fetch & cache work item process schema
  * [ ] Detect process changes to purge caches (service hook?)
  * [ ] Generate Patch from 2 work item instances
  * [ ] Generate Put for new work item instances
  * [ ] Generate Delete for deleted/trashed work item instances
* [ ] Native rule support (drop-in dll)
* [ ] Code generation for "typed wits" based on the process template rest API
* [ ] Fix webhooks azure deployment
* [ ] Create work item tree support
* [ ] Advanced rules
  * [ ] Access to other REST API clients
  * [ ] Trigger on different service hooks (e.g. create work items based on pushes)
* [ ] Alternate policy locations
  * [ ] Store policies as Nuget package in Package Management
  * [ ] Store policies in Git repositories
* [ ] OAuth support instead of PAT
* [ ] New hosting mechanism for webhook version
  * [ ] Azure Functions?
  * [ ] Docker WebApp?
  * [ ] Azure marketplace? 
* [ ] Expose non-wit link types (hyperlink, source control etc)
* [ ] Use Roslyn for code generation 
* [ ] Log exact build numbers when initializing and in error eventlogs.

**Comment by jessehouwing** [comment]
PS: What better issue number than #300 for the planning and tracking of Release 3.0.0 :D

**Comment by Scott-Emberson** [comment]
It would be great to see better logging using a logging tool like Log4Net or NLog, to help debug issues, especially when using the web service version for an on-prem TFS.

**Comment by jessehouwing** [comment]
@Scott-Emberson how would you want these surfaced? I suppose that having the ability to dump log in Azure Log Analytics would be useful. What messages are you currently missing? We log quite a bit.

**Comment by Scott-Emberson** [comment]
@jessehouwing So at the moment, we have to use https://tfsaggregator.github.io/admin/logging/#capturing-log-on-tfs, it would be great if in the config we simply have a configurable log file location C:\Logs so everything is dumped to a single log file rather than using the DebugView tool.

**Comment by jessehouwing** [comment]
If I remember correctly we already expose that through the standard trace listeners ever since 2.1

```
<system.diagnostics>
  <sources>
    <source name="TfsAggregator.ServerPlugin" switchValue="All">
      <listeners>
        <remove name="Default" />
        <add name="filelog" />
      </listeners>
    </source>
    <source name="TfsAggregator.User" switchValue="All">
      <listeners>
        <remove name="Default" />
        <add name="filelog" />
      </listeners>
    </source>
  </sources>
  <sharedListeners>
    <add name="filelog"
         type="Microsoft.VisualBasic.Logging.FileLogTraceListener, 
                   Microsoft.VisualBasic, Version=10.0.0.0, 
                   Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
         BaseFileName="TfsAggregator.log"
         DiskSpaceExhaustedBehavior="ThrowException"
         Location="Custom"
         CustomLocation = "C:\Temp"
         MaxFileSize="81920000"
         LogFileCreationSchedule="Daily"/>
  </sharedListeners>
  <trace autoflush="true"/>
</system.diagnostics>
```

**Comment by giuliov** [comment]
@Scott-Emberson Jesse is right: we also send the messages to standard .Net tracing mechanism.

**Comment by jessehouwing** [comment]
We may need to document that better :).

**Comment by jessehouwing** [comment]
From the forks, interesting to look at:

 * [ ] Native rules: https://github.com/tfsaggregator/tfsaggregator/compare/master...nockawa:rulesInAssembly

**Comment by holterandreasb** [comment]
I'd like to be able to add comments to the discussion area of a work item in specific cases. E.g. to be able to inform the user who created the work item (System.CreatedBy) that a bug needs additional information in a custom field if it is not linked to a parent work item.

**Comment by jessehouwing** [comment]
Just setting the System.History field should do the trick. Be careful, the next iteration the history field will be empty.
