### ISSUE TITLE
Prevent the creation of a task if it exist (a old task with the same title) in my system 

### ISSUE THREAD

**Issue by helhaddad** [tfsaggregator/tfsaggregator#301]
hello, 
I'm asking for your help again. 
I use an excel file to import the tasks. There is a way to prevent the creation of a task if it exists (a old task with the same title) in my system 
of course using TFS aggregator

//<rule name="DeductionsAutoSendEmail" appliesTo="Requirement" changes="Change">
//<![CDATA[
	//if(self["Appnext.Common.AdvertiserID"] != null)
	//{
		//var TaskItems = store.GetWorkItems("SELECT System.ID, System.Title from workitems where 
                  Title = '" + self["System.Title"]  and  [Work Item Type] = 'Task'");
		
              //if(TaskItems != null && TaskItems.Count() > 0)
	       //{
                    //dont create the Task
		//}else{
                   //Create the task
               // }
       // ]]>
//</rule>

**Comment by helhaddad** [comment]
Thank you Jesus for your response, but i can not understand it sorry, What I will do to block the creation of the new work item?

**Comment by jessehouwing** [comment]
Just do nothing if the where returns your items. If it doesn't, create them.
