### ISSUE TITLE
Microsoft.TeamFoundation.WorkItemTracking.Client;

### ISSUE THREAD

**Issue by shridhara136** [tfsaggregator/tfsaggregator#302]
is not supporting
i am unable to access

**Comment by jessehouwing** [comment]
Correct.

Intentionally. What are you trying to accomplish?

**Comment by shridhara136** [comment]
using Microsoft.TeamFoundation.WorkItemTracking.Client;
this is not supporting in BaseFieldValueValidator.cs class. i am getting reference error

**Comment by jessehouwing** [comment]
We need a bit more information to help you.

Are you using the installer?

 - which version of the aggregator (please be specific)
 - which version of TFS? Preferably the full version number as found in the
TFS administration console.
 - did you recently perform an upgrade of either TFS or aggregator?

Are you building the source yourself?

 - which branch?
 - what's your selected configuration/platform
 - what version of visual studio are you using ?
 - what version of TFS do you have installed locally?
 - did you copy any assemblies to the references folders?
 - did you restore all nuget packages?
 - did you change/update any of the nuget references ?

In your policy file

 - are you running with debug mode enabled
 - did you recently change your configuration?

**Comment by shridhara136** [comment]
thanks for your help. it's resolved
