### ISSUE TITLE
team foundation server context is obsolete use ivssrequestcontext

### ISSUE THREAD

**Issue by shridhara136** [tfsaggregator/tfsaggregator#303]

**Comment by jessehouwing** [comment]
We need a bit more information to help you.  

Please describe what you're trying to accomplish. Preferably more than just 'compile the solution'. 

Are you using the installer?  

 - which version of the aggregator (please be specific) 
 - which version of TFS? Preferably the full version number as found in the TFS administration console. 
 - did you recently perform an upgrade of either TFS or aggregator?  

Are you building the source yourself?  
 - what are you targeting? Vsts or tfs? 
 - which branch?  
- what's your selected configuration/platform 
 - what version of visual studio are you using ? 
 - what version of TFS do you have installed locally? 
 - did you copy any assemblies to the references folders? 
 - did you restore all nuget packages? 
 - did you change/update any of the nuget references ?

  In your policy file 

  - are you running with debug mode enabled 
 - did you recently change your configuration?

**Comment by jessehouwing** [comment]
Any issues that don't include this information will result in the same request and we'll have to close them.

So, it's probably better to create a single issue that explains the end goal you have in mind and in which you can track the issues you are encountering. That way elwe can help and track progress.

Remember, this is a volunteer run project, so we have very limited time available to help, though we try to help out whenever we can.

Therefore anything you can do to help us help you is greatly appreciated.
