### ISSUE TITLE
Syntax question: Referencing a Test Cases related Tests

### ISSUE THREAD

**Issue by mbeckman-FederatedInsurance** [tfsaggregator/tfsaggregator#306]
Hi - I'm wondering if you can help me with the syntax to set a field from a WIT related to Test Case. I read through the online docs, which gave me a start on determining if the Test Case has related Requirements. I think I have a problem with how I am using the HasRelation method, and how I'm syntactically looking for the Requirement. I included the rule, and the messages I receive during test. 

Thanks for any help you can provide!

<rule name="InheritRelatedFields" appliesTo="Test Case" hasFields="IS Request Number">
        <![CDATA[
        if (self.HasRelation())
        {
		var relation = self.FollowingLinks("Microsoft.VSTS.Common.TestedBy-Forward").WhereTypeIs("Requirement");
		var assignedTo = self["System.AssignedTo"];
		
		if (relation["Federated.IS.RequestNumber"] != string.Empty) {
			logger.Log("{4}: {1} {0}:Owned by {3}:IS Request Number {2}", relation.Id, relation.TypeName, relation["Federated.IS.RequestNumber"], relation["System.AssignedTo"],relation["System.ChangedDate"]);
			if (self["Federated.IS.RequestNumber"] == string.Empty) {
				self["Federated.IS.RequestNumber"] = (self.relation["Federated.IS.RequestNumber"] ?? 0d);
				logger.Log("{4}:Aggregator changed {1} {0}:Owned by {3}:IS Request Number of {2}", self.Id, self.TypeName, self["Federated.IS.RequestNumber"], self["System.AssignedTo"], self["System.ChangedDate"]);
			}
		}
        }
        ]]>
    </rule>

C:\Program Files\TFS Aggregator\bin>TFSAggregator2.ConsoleApp.exe run --policyFi
le="D:\Administration\TFSAggregator2.ServerPlugin.policies" --teamProjectCollect
ionUrl="http://tfs-dev:8080/tfs/Federated Collection" --teamProjectName="Federat
ed Projects" --workItemId=5494 --logLevel=diagnostic
TFSAggregator2.ConsoleApp 1.0.0

Build: 2.4.0, Configuration: Release-2018 [TFS 2018]
Copyright (c) TFS Aggregator Team 2015-18

Executing run (Applies a policy file to specified work item(s)):

[Information] 00.304 TFSAggregator2.Core started, version: 1.0.0, build: 2.4.0,
configuration: Release-2018 [TFS 2018]
[Warning]     01.519 Rule 'MyFirstRule' is never used
[Warning]     01.519 Rule 'InheritRelatedFields' is never used
[Information] 01.627 Configuration loaded successfully from 'D:\Administration\T
FSAggregator2.ServerPlugin.policies'
[Warning]     01.628 WhatIf flag: no change will be saved.
[Verbose]     01.745 Connecting to http://tfs-dev:8080/tfs/Federated Collection
impersonating WindowsIntegratedAuthenticationToken, running as w404chg1
[Diagnostic]  10.983 Built a new Work Item Repository for http://tfs-dev:8080/tf
s/Federated Collection using a WindowsIntegratedAuthenticationToken
[Verbose]     10.984 Building Script Engine for C#
**[Error]       14.460 Error CS1501 in script 'InheritRelatedFields' at line 3, co
lumn 13: No overload for method 'HasRelation' takes 0 arguments**
[Error]       14.460 Error CS0021 in script 'InheritRelatedFields' at line 8, co
lumn 7: Cannot apply indexing with [] to an expression of type 'Aggregator.Core.
Navigation.FluentQuery'
[Error]       14.460 Error CS1061 in script 'InheritRelatedFields' at line 9, co
lumn 75: 'Aggregator.Core.Navigation.FluentQuery' does not contain a definition
for 'Id' and no extension method 'Id' accepting a first argument of type 'Aggreg
ator.Core.Navigation.FluentQuery' could be found (are you missing a using direct
ive or an assembly reference?)
[Error]       14.460 Error CS1061 in script 'InheritRelatedFields' at line 9, co
lumn 88: 'Aggregator.Core.Navigation.FluentQuery' does not contain a definition
for 'TypeName' and no extension method 'TypeName' accepting a first argument of
type 'Aggregator.Core.Navigation.FluentQuery' could be found (are you missing a
using directive or an assembly reference?)
[Error]       14.460 Error CS0021 in script 'InheritRelatedFields' at line 9, co
lumn 98: Cannot apply indexing with [] to an expression of type 'Aggregator.Core
.Navigation.FluentQuery'
[Error]       14.460 Error CS0021 in script 'InheritRelatedFields' at line 9, co
lumn 138: Cannot apply indexing with [] to an expression of type 'Aggregator.Cor
e.Navigation.FluentQuery'
[Error]       14.460 Error CS0021 in script 'InheritRelatedFields' at line 9, co
lumn 168: Cannot apply indexing with [] to an expression of type 'Aggregator.Cor
e.Navigation.FluentQuery'
[Warning]     14.461 Warning CS0252 in script 'InheritRelatedFields' at line 10,
 column 8: Possible unintended reference comparison; to get a value comparison,
cast the left hand side to type 'string'
[Error]       14.461 Error CS1061 in script 'InheritRelatedFields' at line 11, c
olumn 48: 'Aggregator.Core.Interfaces.IWorkItemExposed' does not contain a defin
ition for 'relation' and no extension method 'relation' accepting a first argume
nt of type 'Aggregator.Core.Interfaces.IWorkItemExposed' could be found (are you
 missing a using directive or an assembly reference?)
[Information] 15.101 Starting processing on workitem #5494

**Comment by giuliov** [comment]
That method returns `true` when the work item has a link to another work item and the link matches the reference name passed as argument. So the call `HasRelation("System.LinkTypes.Hierarchy-Reverse")` gives `true` if the work item has a parent work item (e.g. a Task children of a User Story).
The possible reference names are listed [here](https://docs.microsoft.com/en-us/vsts/work/customize/reference/link-type-element-reference).

PS There is no trace of an `HasRelation` call in the code you shared :-)

PPS The error position is calculated relative to the rule code, i.e. `Error CS1501 in script 'InheritRelatedFields' at line 3, column 13` happens at the third line of the _InheritRelatedFields_ rule.
