### ISSUE TITLE
Task to Story Rollup Totals Incorrect

### ISSUE THREAD

**Issue by dreamerballoon** [tfsaggregator/tfsaggregator#308]
I'm having an issue with the task to story rollup functionality for Original Estimate, Completed Work, and Remaining Work. If the task hours for all three fields reflect what was planned, such as follows, everything is fine:

![image](https://user-images.githubusercontent.com/42349883/44092740-088151ae-9f97-11e8-9109-1ee919e7e5a0.png)

However, if the completed work and remaining work vary at all from what is expected/planned, then the rollup no longer sums correctly. 

In this first scenario, a developer has completes 2 hours of work and estimates it will only take 1 hour of remaining work to complete the task, coming in 1 hour under the original estimate, yet the rollup reflects something different:

![image](https://user-images.githubusercontent.com/42349883/44092986-aaf8e1b8-9f97-11e8-88a3-b7b812bfa269.png)

In this second scenario, a developer has completed 4 hours of work against the original estimate of 4 hours. However, they estimate it will now take 2 additional hours to complete the task. This is also not totaling up correctly:

![image](https://user-images.githubusercontent.com/42349883/44093065-ff4eebe0-9f97-11e8-9699-fc4a07a23eb9.png)

I used the simple rollup example rule:

![image](https://user-images.githubusercontent.com/42349883/44093200-70c56f4c-9f98-11e8-87b5-63bc58153122.png)

Am I missing something or doing something incorrectly in my rule?

Thanks,
Rob

**Comment by jessehouwing** [comment]
If the users enters bad data, the sum of that data is bad.

**Comment by dreamerballoon** [comment]
@jessehouwing Thanks for the quick reply. However, I afraid I see things differently. Stick with me while I explain... The original estimate is "just an estimate". It is completely reasonable that a task may take more or less time than what was estimated. What you are calling "bad" data is actually more accurate than what was estimated. And, I would think that teams want to track actual work vs. estimated work. Otherwise, how do they improve their estimating process? Based on your answer, to get the TFS Aggregator to rollup properly in these scenarios, users need to modify the original estimate, or fudge the numbers for remaining and completed work, right? For our teams, I'm afraid this is not a viable solution, as they want to 1.) reflect accurately, and 2.) get better at estimating. Neither of which will happen if they have to manipulate the numbers to get the rollup to work.

**Comment by jessehouwing** [comment]
Then introduce an additional field or check the history of the original
estimate field. The rule just adds up the numbers you can make it as fancy
as you'd like, but you'll have to codify the desired behavior.

@Andrii recently added a more extensive example
https://github.com/tfsaggregator/tfsaggregator-docs-hugo/blob/master/content/using/examples/log-time-synch.md
