### ISSUE TITLE
How to unblock successors?

### ISSUE THREAD

**Issue by jdshkolnik** [tfsaggregator/tfsaggregator#309]
Hi,

I'd like to write a rule when a work item is completed/removed/deleted, all of its successors will be unblocked if each of those doesn't have one or more active predecessors remaining.

It didn't look like anything came of @jessehouwing 's suggestion in [a past discussion here](https://github.com/tfsaggregator/tfsaggregator/issues/18#issuecomment-81273655).

**Comment by jessehouwing** [comment]
We'd love a pull request. For the v3 rewrite I think I already included the code for 'all link types', but not yet the nice scripting language features @giulio was talking about.

**Comment by jdshkolnik** [comment]
What's the rough timeline for v3?

**Comment by jessehouwing** [comment]
@jdshkolnik we're approaching public beta-bug-bash

**Comment by evertonmc** [comment]
@jessehouwing do we have a reference for this feature? is it in v3? is there a v3? thanks in advance

**Comment by jessehouwing** [comment]
This can easily be implemented as a function now. There is a following
links function to traverse the graph.

Aggregator 3 is based on Azure Functions and a beta is currently available.

**Comment by evertonmc** [comment]
> @jessehouwing do we have a reference for this feature? is it in v3? is there a v3? thanks in advance

forget it, now I've found v3 (a.k.a. CLI)

Question: Is there a way to implement this by using something like 
```
<rule name="AutoUnblockSuccessor" appliesTo="Task">
    <!-- Update Work Item to New if all predecessors become Removed, Resolved or Closed -->
    <![CDATA[
    if (new[] {"Removed", "Resolved", "Closed"}.Contains((string)self["System.State"]))
    {
        if(self.HasRelation("System.LinkTypes.Dependency") )
        {
		self.Successors.ForEach(successor => {
		if (new[] {"Blocked"}.Contains((string)child["System.State"]) && successor.Predecessors.All(child => new[] {"Removed", "Resolved", "Closed"}.Contains((string)child["System.State"]))))
            {
				successor.TransitionToState("New", "Auto restored by #"+self.Id)
			}
        }
    }
    ]]>
</rule>
```

**Comment by evertonmc** [comment]
> This can easily be implemented as a function now.

I'm on premises :disappointed: (server)

**Comment by jessehouwing** [comment]
That looks like a valid approach.

We want to bring Aggregator 3 to the Windows Server Functions Runtime. Thad
foul allow you to run it on-premise as well, though, if your TFS server can
reach Azure, hooking it to Azure Functions would also be an option.

**Comment by evertonmc** [comment]
@jessehouwing I've designed a function to get the Predecessors/successors
Can you tell me why are am I getting this error?
[Error]       00.792 Error CS1061 in script 'AutoActive' at line 18, column 42: 'Aggregator.Core.Interfaces.IWorkItemExposed' does not contain a definition for 'WorkItemLinksImpl' and no extension method 'WorkItemLinksImpl' accepting a first argument of type 'Aggregator.Core.Interfaces.IWorkItemExposed' could be found (are you missing a using directive or an assembly reference?)

```
	<function><![CDATA[
	System.Collections.Generic.IEnumerable<IWorkItemExposed > Predecessors(IWorkItemExposed  wi) {
		var _predecessors =
			from IWorkItemLink workItemLink in wi.WorkItemLinksImpl
			where workItemLink.LinkTypeEndImmutableName == "System.LinkTypes.Dependency-Reverse"
			select wi.Store.GetWorkItem(workItemLink.TargetId);

		foreach (var item in _predecessors)
		{
			yield return item;
		}
	}
	]]></function>
```

**Comment by jessehouwing** [comment]
The impl classes are not exposed. These also use interfaces. I think it's
best to use Following Links here.

**Comment by evertonmc** [comment]
> if your TFS server can reach Azure, hooking it to Azure Functions would also be an option.

My TFS can reach Azure but In order to use functions, my Azure DevOps Server would have to be reachable **from** the internet, which is not the case

**Comment by evertonmc** [comment]
I solved this rite now by extending my rule
```

<rule name="AutoUnblockSuccessor" appliesTo="Task">
    <!-- Update Successor Item to New if all predecessors become Removed, Resolved or Closed -->
<![CDATA[
if (new[] {"Removed", "Resolved", "Closed"}.Contains((string)self["System.State"]))
{
  if(self.HasRelation("System.LinkTypes.Dependency-Forward"))
  {
  var _successors = self.WorkItemLinks.Where(selfLink => selfLink.LinkTypeEndImmutableName.Equals("System.LinkTypes.Dependency-Forward")).Select(selfLink => store.GetWorkItem(selfLink.TargetId));
    
    foreach (var successor in _successors)
    {
      if (new[] {"Blocked"}.Contains((string)successor["System.State"]))
      {
        var _predecessors = successor.WorkItemLinks.Where(successorLink => successorLink.LinkTypeEndImmutableName.Equals("System.LinkTypes.Dependency-Reverse")).Select(successorLink => store.GetWorkItem(successorLink.TargetId));
        if (_predecessors.All<IWorkItemExposed>(predecessor => new[] {"Removed", "Resolved","Closed"}.Contains((string)predecessor["System.State"])))
        {
          successor.TransitionToState("New", "Auto unblocked by #"+self.Id);
          if (successor.Parent.Children.Any<IWorkItemExposed>(child => new[] {"Resolved","Closed","Active"}.Contains((string)child["System.State"])))
          {
            successor.Parent.TransitionToState("Active", "Auto unblocked by #"+self.Id);
          }
          else
          {
            successor.Parent.TransitionToState("New", "Auto unblocked by #"+self.Id);
          }
        }
      }
    }
  }
}
]]>
</rule>

```
