### ISSUE TITLE
Proposal of tfs aggregator modification in order to obtain an history of commits of source code linked with workitems

### ISSUE THREAD

**Issue by francesco-sclano** [tfsaggregator/tfsaggregator#311]
Is it possible to do with tfs aggregator what I previously asked here? 

https://stackoverflow.com/questions/51883551/how-access-git-commits-from-microsoft-teamfoundation-workitemtracking-client/51889249?noredirect=1#comment90795990_51889249

I'd like to modify the source code of tfsaggregator in order to eventually write a rule that is called every time a new commit is linked with a workitem (through an external link) and assign all related informations of commit (author, date etc.) to new custom fields like commit1date, commit1author, commit2date, commit2author and so on ... the idea is to have a stack of last 20 (20 for example) commit informations for every workitem. Before I start development, do you have any suggestion about it ? Is it generally possible to modify aggregator in order to expose methods like GetCommitAsync of Microsoft.TeamFoundation.SourceControl.WebApi (how answered in stackoverflow) ? Thanks

**Comment by jessehouwing** [comment]
Wouldn't a custom work item control be a much easier solution to visualize the commit data on a work item form?
