### ISSUE TITLE
Feature Request: appliesTo="ProjectName"

### ISSUE THREAD

**Issue by Prybe** [tfsaggregator/tfsaggregator#313]
Is it possible to make the following functionality more readable...?

My goal is to set a rule that only applies to a specific project.
For example: only one project wants to accumulate the effort of PBI´s to the parent feature.

Currently I would set an if statement inside of the rule that checks the field "area".

But does it makes sense to add this statement to the rule definition.
Like appliesTo="Task" -> appliesToProject="MyProject"

**Comment by jessehouwing** [comment]
This is already available through adding the projectScope to a policy.

**Comment by jessehouwing** [comment]
You can have multiple policy blocks in the same policy file.

**Comment by Prybe** [comment]
thx a lot... overlooked somehow :)
for all that have the same stupid question.. or are as blind as me
https://github.com/tfsaggregator/tfsaggregator/blob/53a5b8accbb65e2c0061d5368bec12eea939fa1e/samples/TFSAggregator2.ServerPlugin.policies

**Comment by giuliov** [comment]
Also here https://tfsaggregator.github.io/using/policy-syntax/#policy-sections
