### ISSUE TITLE
TFS Aggregator Installation for Azure DevOps

### ISSUE THREAD

**Issue by simranchandel** [tfsaggregator/tfsaggregator#323]
I am unable to figure out a way to install this plugin for Azure Devops. Please help.

**Comment by giuliov** [comment]
If you look for an Azure DevOps *Service* solution you have to take a look at https://github.com/tfsaggregator/aggregator-cli. TFS Aggregator is a *Server* plugin that works with TFS (2013.2 to 2018.3.2) and Azure DevOps *Server* 2019.
The instruction for TFS Aggregator are at https://tfsaggregator.github.io/intro/.
The documentation for Aggregator CLI is limited and can be found from https://github.com/tfsaggregator/aggregator-cli/blob/master/README.md

**Comment by simranchandel** [comment]
Thank you for your response. I have already gone through the document but could not understand how to install it. Please help

**Comment by giuliov** [comment]
You download and run the latest MSI from https://github.com/tfsaggregator/tfsaggregator/releases and run it on each Application Tier node: that's all for the plugin.

**Comment by simranchandel** [comment]
Thank you for your response. Can tfs aggregator be used for the summation
of remaining work in all the child work items of a particular user story?

**Comment by jessehouwing** [comment]
Yes this is one of the samples.

**Comment by HGulec** [comment]
Hi,
We can not run tfs aggregator. Our log ;
![image](https://user-images.githubusercontent.com/52749528/63261894-3e206b00-c28d-11e9-9cad-4e9888e71a85.png)
