### ISSUE TITLE
how to install tfs aggregator in TFS 2017 on premises 

### ISSUE THREAD

**Issue by harieligeti** [tfsaggregator/tfsaggregator#324]

**Comment by jessehouwing** [comment]
Have you checked the docs site?

Tfsaggregator.github.io

**Comment by giuliov** [comment]
This should help https://tfsaggregator.github.io/admin/install/
Note: install on each AT.

**Comment by harieligeti** [comment]
actually am not he admin of the TFS.. am just handler, so in need to install this tfsintegrator in main server, that means where it has installed??

**Comment by harieligeti** [comment]
and i need twoway binding for the fields is this pluggin will help??

**Comment by harieligeti** [comment]
> This should help https://tfsaggregator.github.io/admin/install/
> Note: install on each AT.

AT means

**Comment by jessehouwing** [comment]
Application tier. The part of TFS that hosts the webservices and the job agent.

If you are not an admin, you can't do the install.

I don't know what you mean with a two way binding.

**Comment by harieligeti** [comment]
> Application tier. The part of TFS that hosts the webservices and the job agent.
> 
> If you are not an admin, you can't do the install.
> 
> I don't know what you mean with a two way binding.

it means if 3 fields(text fields) are present in a workitem. if i enter anything in the 2 fields, automatically it should display on the 3rd block as a paragraph type.. as shown in below image path:
[image](https://i.postimg.cc/9FY7yQnz/77235-capture.png)

**Comment by harieligeti** [comment]
> Application tier. The part of TFS that hosts the webservices and the job agent.
> 
> If you are not an admin, you can't do the install.
> 
> I don't know what you mean with a two way binding.

this is the example of twi way binding.. refer this link [https://www.w3schools.com/angular/tryit.asp?filename=try_ng_databinding_two-way](https://www.w3schools.com/angular/tryit.asp?filename=try_ng_databinding_two-way).
if i change or write in a text box it dispays in the next element

**Comment by giuliov** [comment]
Aggregator is not of help in your scenario: it is a server-side solution; 
rules are triggered _after_ you save a work item. A rule can automate a lot of things (like automatically creating or linking other workitems, or editing values in a hierarchy of work items). but looks like you are looking for a client side solution.
You have to write and deploy your custom Extension using Typescript/Javascript.

**Comment by harieligeti** [comment]
> Aggregator is not of help in your scenario: it is a server-side solution;
> rules are triggered _after_ you save a work item. A rule can automate a lot of things (like automatically creating or linking other workitems, or editing values in a hierarchy of work items). but looks like you are looking for a client side solution.
> You have to write and deploy your custom Extension using Typescript/Javascript.

okay.. for that i need to create custom extension myself right? so please let me know the process of making a custom extension

**Comment by giuliov** [comment]
See here https://docs.microsoft.com/en-us/azure/devops/extend/index?view=azure-devops

**Comment by harieligeti** [comment]
Thank you..@giuliov

**Comment by giuliov** [comment]
I think this is all for now. In case open another issue @harieligeti
