### ISSUE TITLE
TFS Aggregator not running rules

### ISSUE THREAD

**Issue by sykokinetyk** [tfsaggregator/tfsaggregator#328]
I am using TFS Aggregator 2.5.1-RC on Azure DevOps Server 2019 RC2.  My rule runs successfully when using the console app with testing, but when I put it into the plugins directory, nothing happens.  Is there a trigger or a hook that I'm missing?

**Comment by giuliov** [comment]
No, unless you have more than one Application Tier.
I suggest to look at the [guide](https://tfsaggregator.github.io/admin/) to review your install and troubleshooting tips.

**Comment by sykokinetyk** [comment]
Hi there.  I followed the guide, and everything seems to match up correctly.  One thing to note, is we are currently load balancing two ADO 2019 servers, and the Aggregator is not installed on one of them, could this cause the issue I am seeing?

**Comment by giuliov** [comment]
Yes, you **must** install it on each application tier. TFS/AzDOS may trigger the event on any AT server, so Aggregator should be present with identical policy file.
