### ISSUE TITLE
Release 2019.1 RC2 support

### ISSUE THREAD

**Issue by evertonmc** [tfsaggregator/tfsaggregator#331]
please :)

**Comment by jessehouwing** [comment]
I suspect the change is simple and only requires the build number to be added to the wix project.

I've just become father for the second time, it may take me longer to test that hypothesis.

Pull request?

**Comment by evertonmc** [comment]
Sure #332 PR to develop only or features/2019.1 as well?

**Comment by evertonmc** [comment]
> I've just become father for the second time, it may take me longer to test that hypothesis.

CONGRATULATIONS MAN! Best thing EVER!

**Comment by jessehouwing** [comment]
![image](https://user-images.githubusercontent.com/4173387/61957992-c4b09800-afc0-11e9-96a9-df2bff81a912.png)

**Comment by jessehouwing** [comment]
There are issues with the build that I can't resolve now. It's generating unexpected build numbers...

@giuliov you a clue? GitVersion is whacko a the moment.

Version 3 ir deprecated, v4 crashes and v5-preview generates 2.6.0alpha instead of 2.5.1-beta.8

**Comment by jessehouwing** [comment]
https://dev.azure.com/tfsaggregator/TfsAggregator2/_build/results?buildId=452&view=logs&j=ae5f67bc-b508-52d0-18c7-3e0886a35c88

**Comment by jessehouwing** [comment]
I cheated.

https://github.com/tfsaggregator/tfsaggregator/releases/tag/v2.5.2-beta1
