### ISSUE TITLE
CompeltedWork field not updating properly (bug?)

### ISSUE THREAD

**Issue by jmilgie** [tfsaggregator/tfsaggregator#333]
`TFS Aggregator version 2.5.2, Azure Devops version 2019.0.1`

Below is my rule from my policies file:

```
<rule name="RollupCompletedWorkFromTasks" appliesTo="Product Backlog Item,Bug">
<![CDATA[
  if (self.HasChildren())
  {
    if (((string)self["System.State"] == "Done")){
      logger.Log("self state={0} and ID={1}", (string)self["System.State"], self["System.Id"]);
      logger.Log("CompletedWork FieldValue (start): {0}", self.GetField<double>("Microsoft.VSTS.Scheduling.CompletedWork", 0d));
      logger.Log("Item state has changed, performing rollup for CompletedWork");
      logger.Log("CompletedWork FieldValue (in progress): {0}", self.Children.Sum(task => task.GetField<double>("Microsoft.VSTS.Scheduling.CompletedWork", 0d)));
      self["Microsoft.VSTS.Scheduling.CompletedWork"] = (double)self.Children.Sum(task => task.GetField<double>("Microsoft.VSTS.Scheduling.CompletedWork", 0d));
      logger.Log("CompletedWork FieldValue (end): {0}", self.GetField<double>("Microsoft.VSTS.Scheduling.CompletedWork", 0d));
    }
  }
    ]]>
</rule>
```

Showing the rule is enabled in the policies file:
```
		<ruleRef name="RollupCompletedWorkFromTasks" />
```

Here is the logging from debugview:
```
[9792] TFSAggregator: [Information] Applying Rule 'RollupCompletedWorkFromTasks' on #17915 
[9792] TFSAggregator.User: [Verbose]     RollupCompletedWorkFromTasks: self state=Done and ID=17915 
[9792] TFSAggregator.User: [Verbose]     RollupCompletedWorkFromTasks: CompletedWork FieldValue (start): 1 
[9792] TFSAggregator.User: [Verbose]     RollupCompletedWorkFromTasks: Item state has changed, performing rollup for CompletedWork 
[9792] TFSAggregator.User: [Verbose]     RollupCompletedWorkFromTasks: CompletedWork FieldValue (in progress): 2.32 
[9792] TFSAggregator.User: [Verbose]     RollupCompletedWorkFromTasks: CompletedWork FieldValue (end): 2.32
```

It appears it's doing all the evaluations correctly... but it's just not actually updating the field. (self object isn't committing to the API/Database?)

In the logged example above CompletedWork field had an initial value of `1`. After the rule applies, the value of the field remains `1`. I can also null it out, and the same will be true (null will remain, no update to the value).

Any help on where to look or what this could be, would be very helpful!

**Comment by giuliov** [comment]
Looks good reading the code. Some execution logs might help you (see https://tfsaggregator.github.io/admin/troubleshooting/): maybe the user executing the rule has no write permission on project's work items.

**Comment by jessehouwing** [comment]
Maybe an exception in another rule? Or another rule discarding the changes?

We only save at the very end.

**Comment by jmilgie** [comment]
RE: user permission, there are other rules which are working fine. (autocreation of child tasks for example). I didn't consider that another rule could be getting in the way. I'll try stripping out other rules and see what happens and circle back. Thanks for the good idea!

**Comment by jmilgie** [comment]
Yep, not a bug. Some other rule was causing this not to work. Stripping everything else out resulted in it working properly. Thanks @jessehouwing !

**Comment by jessehouwing** [comment]
Thanks for letting us know.
