### ISSUE TITLE
Unable to update field with full user name

### ISSUE THREAD

**Issue by ghost** [tfsaggregator/tfsaggregator#334]
We are using TFSAggregator to sync fields between Work-items and have found an issue when trying to sync a string field that holds user names in "TFSUsers" format:

       Firstname Lastname <Domain\UserId>

We have found that we need to remove the " Domain\UserId" from the user name in our script to get an update of this field to work successfully. However, if a user has multiple user names in "TFSUsers" with different Domains, then it always fails with "Work-item not valid to save". Presumably due to it not being able to determine which user to select.  If I change the script to NOT remove the, "<Domain\UserId>",  then all 4 fields will set but will present the "Work-item not valid to save!" when trying to save the work-item. 

If I manually try to add a user to these field in a TFS Work-item from Visual Studio or the Web it works fine specifying the full name, "Firstname Lastname <Domain\UserId>" and picking the correct user since it has the domain specified.

Do to this, the TFSAggregator script is failing every time there is a user with multiple user names listed in "TFSUsers" with different Domains.  We have talked with Microsoft and they state that Users in TFS cannot be removed, once they are in, they are permanent.  But by specifying the Full name should work as this is what is displayed from a field using "TFSUser".

Below is the code I use to test and update this field (actually we have 4 different fields that have this same issue).  As you can see it gets the current parent work-item value (where I am getting the current values to sync) and the target work-item value (the values to be synced). These are both full user names, "Firstname Lastname <Domain\UserId>". I test to verify that these are different and if they are, I remove the " <Domain\UserId>" from the parentWIValue and then set this into the targetWIValue (child) work-item. Once the script is completed, TFS Aggregator validates and returns "Work-item not valid to save" if the user has multiple usernames with different Domains.  If I leave the " <Domain\UserId" in the parentWIValue, then we also get the "Work-item not valid to save" for any users selected, whether or not, they have multiple user names.

Any help in resolving this issue would be greatly appreciated.

James Forst
Mitchell International

Example Code:
=========================
parentWIValue = (string)parentWI["Company.Portfolio_Owner"];
targetWIValue = (string)targetWI["Company.Portfolio_Owner"];
logger.Log(LogLevel.Verbose, "Current target workitem field Company.Portfolio_Owner value: {0}!", 
                              targetWI["Company.Portfolio_Owner"]);
if (parentWIValue == targetWIValue) {
      logger.Log(LogLevel.Verbose, "Target workitem field Company.Portfolio_Owner value already up-to-date"); 
} else {
  if (parentWIValue.Length > 0) 
  { 
      if (parentWIValue.IndexOf('<') > 0) 
      {
          parentWIValue = parentWIValue.Substring(0,parentWIValue.IndexOf('<')-2);
      }
      logger.Log(LogLevel.Verbose, "Setting Company.Portfolio_Owner to Portfolio Epic: {0}!", 
                                    parentWIValue);
      targetWI["Company.Portfolio_Owner"] = parentWIValue;
      logger.Log(LogLevel.Verbose, "New target workitem field Company.Portfolio_Owner value: {0}!", 
                                    targetWI["Company.Portfolio_Owner"]);
  } else {
      logger.Log(LogLevel.Verbose, "Setting Company.Portfolio_Owner to Portfolio Epic: {0}!", 
                                    defaultWIValue);
      targetWI["Company.Portfolio_Owner"] = defaultWIValue;
      logger.Log(LogLevel.Verbose, "New target workitem field Company.Portfolio_Owner value: {0}!", 
                                    targetWI["Company.Portfolio_Owner"]);
  }
}

**Comment by jessehouwing** [comment]
We've had this issue with looking up emailaddresses. TFS is very peculiar in the way identities are looked up and exposed as field values.

Underlying, TFS relies on:

```
var workItemStore = teamProjectCollection.GetService<WorkItemStore>();

workItemStore.TryFindIdentity(lookup, out var identity))
```

It may be possible to add a field decorator that performs the lookup ant then feeds the upn or nt-user format of the identity. That one should always work. 

You could also update the display name of the old identities to make them not the same as the new ones, that should also work. 

I don't have a setup at hand that has these issuer, so it's very hard to test and repro. Do you have the ability to locally build the solution?

**Comment by jessehouwing** [comment]
What I propose would require adding a class very similar to this one

https://github.com/tfsaggregator/tfsaggregator/blob/master/Aggregator.Core/Aggregator.Core/Extensions/DoubleFixFieldDecorator.cs

And use the displayName to perform the lookup using the work item store object.

**Comment by jessehouwing** [comment]
You can also try to just pass in the `domain\user` value when present in the display name. I've seen that work as well in the past.

If you go through the issue history, you'll see that there are many past issues around identity lookups and there isn't much we can do about it. The object model is just weird about it.

**Comment by ghost** [comment]
Hi Jesse,

Thanks for the info.

We have tried passing the user name as “First Last”, “First Last <Domain\User>” and “Domain\User” and so far the “First Last” is the only one that has worked. Except for the ones with Double identities with different Domains.

I will try some of the items you suggested, including changing the Display Names of the old identities which may be the simplest.

I will let you know what I find.

Thanks again,

James

**Comment by ghost** [comment]
Unable to find resolution for this issue and no help.
