### ISSUE TITLE
I want to use "DateTime" in rule script

### ISSUE THREAD

**Issue by ozdemirersin** [tfsaggregator/tfsaggregator#336]
Hello , i want to use "DateTime" in rule script, how can i do?

![image](https://user-images.githubusercontent.com/54444404/66023016-73f57800-e4f8-11e9-8b71-e5e027efc7b6.png)

**Comment by giuliov** [comment]
I remember some past discussions, try search in older issues. If you can't find I'll answer tomorrow.

Giulio Vian
Microsoft MVP, ALM DevOps Ranger
PSM I, MCTS, MCPD, MCSD1
mobile +353 89 2362452 | +39 348 2811203

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ozdemirersin** [comment]
Oh sorry, i found. "System.DateTime" is working.
