### ISSUE TITLE
Can I access Azure Devops user groups in tfsaggregator?

### ISSUE THREAD

**Issue by ozdemirersin** [tfsaggregator/tfsaggregator#337]
I want to check that the person who created the item is in the group, is it possible?

**Comment by SAnCherepan** [comment]
@ozdemirersin, there is a workaround you can use.

1. Add a flag field in your WITD.
2. In initial transition (`TRANSITION from=""`) add a `<COPY for="[project]\<group_name>" from="value" value="whatever_you_want">` and check that field within your Aggregator rule.

Use `[project]` or `[global]` depending on whether your group is defined on project or collection level.

**Comment by jessehouwing** [comment]
No, we don't expose the TFS objects to query identities & permissions.
