### ISSUE TITLE
'Complete linked work items after merging' option doesn't trigger rules

### ISSUE THREAD

**Issue by Xemius** [tfsaggregator/tfsaggregator#338]
I wrote a rule that transition the parent to "done", if all child tasks are in a "done" state.
So, when i use option "Complete linked work items after merging" in pull-request, this rule will not be executed.
How can i solve this?

**Comment by giuliov** [comment]
Can you share more of your context? My first reaction is that TFS/AzDOS is not raising the event and it would help to know which version you are using.

**Comment by Xemius** [comment]
@giuliov 
I run it on:
Windows Server 2012 R2 (if it help :))
Azure DevOps Server 2019 (17.143.28621.4)
TFS aggregator 2.5.2 beta3
