### ISSUE TITLE
No response after saving the policies file

### ISSUE THREAD

**Issue by Stefan2222** [tfsaggregator/tfsaggregator#340]
After saving TFSAggregator2.ServerPlugin.policies client access is not possible for 5 to 10 minutes. Sometimes it is necessary to run IISRESET to restore client access. The TFSAggregator2.ServerPlugin.policies was successfully checked in the Console.App before and all rules are working fine. The effect occurs even after minor changes like adding a field in a logger output. It looks like the time of no response increases every time the TFSAggregator2.ServerPlugin.policies gets updated.

DevOps Server 17.143.28912.1 (AzureDevOps2019.0.1)
Aggregator v2.5.1-beta6

**Comment by giuliov** [comment]
Thanks Stefan.
This is outside our control: any file change in TFS/AzureDevOps `Plugins` directory, trigger a restart of the AppDomain hosting any plugin.
We will try to gather more information to understand the time increase you describe.

**Comment by Stefan2222** [comment]
In case you need more information like event logs etc. I´ll be happy to assist you.

**Comment by ltoto2** [comment]
Same with TFS 2017.2 and Aggregator v2.5.0-RC
No response for few minutes

Thanks

**Comment by giuliov** [comment]
To all: can you share the OS and .Net version?

**Comment by Stefan2222** [comment]
Windows Server 2012R2
.NET Framework 4.6.01055

**Comment by agomesnunes** [comment]
We have TFS 2017 update 1 and Windows 10 enterprise installed on two servers and we use Aggregator to automate some rules.
 
In recent weeks we are facing difficulties in automation.
 
For example, work items are in the rules waiting for automation to update them, but for some reason they are not updated, we need to "recycle" IIS and after that, we need to update some work items that are stopped, done that to Automation starts running and clearing the queue, minutes later the same problem occurs.
 
Already we searched in several forums and found nothing, could help us with any tips to solve such a problem.

.NET Framework 4.5.5...

**Comment by agomesnunes** [comment]
Sorry, the operating system of the previous comment is "Windows Server 2016 standard"

**Comment by jessehouwing** [comment]
Update to .net 4.6 or 4.7 should auto enable TLS 1.2 support.

Or follow these posts.

https://johnlouros.com/blog/enabling-strong-cryptography-for-all-dot-net-applications
