### ISSUE TITLE
Release 2019.1.1 support

### ISSUE THREAD

**Issue by anielsen** [tfsaggregator/tfsaggregator#342]
According to the docs version 2019.1 is the last supported. Can I use the current version (v2.5) with devops 2019.1.1?

Thank you for creating tfsaggregator :-)

**Comment by jessehouwing** [comment]
Already done.

**Comment by jessehouwing** [comment]
![Screenshot_20200214-192640](https://user-images.githubusercontent.com/4173387/74560106-2426c300-4f66-11ea-919d-5c2be40504df.png)

**Comment by anielsen** [comment]
Thank you! I see that I need to be better at navigating github :-)
