### ISSUE TITLE
Authentication mechanism between Aggregator Web Service and VSTS/ADO.

### ISSUE THREAD

**Issue by sakamati** [tfsaggregator/tfsaggregator#344]
Hello,

Based on the below flow diagram, understand that currently Personal Access Token (PAT) is the only option to authenticate Aggregator Web Service against VSTS/ADO.
As you may know the PAT comes up with its own limitations such the limited expiry period (max 1year) and associated to a individual member on VSTS/ADO. Need to manage the renewal part of the PAT once a year before it expires.

Do we have other ways to authenticate Aggregator web service with VSTS/ADO? Something like Service Principal?

![image](https://user-images.githubusercontent.com/1908536/81788376-0eeb1180-9520-11ea-8542-1350fcb80131.png)

**Comment by jessehouwing** [comment]
No we currently don't offer this. There are ways to generate a PAT with a much longer expiry date through the REST API. 

In the past you could use your "alternate credentials user+pass" for Git, but Microsoft is deprecating this.

With GitHub actions likely coming to Azure DevOps, It may be possible to leverage that to host/Replace the TFS aggregator and use its auth token.

We could probably also implement a service to auto-extend/re-new the PAT.

Right now none of that is in place. PS The Aggregator WebService has been deprecated and has been replaced by [aggregator-cli](https://github.com/tfsaggregator/aggregator-cli).

**Comment by sakamati** [comment]
Thanks for your response.
