### ISSUE TITLE
Server plugin stops working silently

### ISSUE THREAD

**Issue by ItielBeeri** [tfsaggregator/tfsaggregator#345]
We have a working installation of TFSAggregator as a server plugin, with some useful and well-tested policies.
For many months, it just worked perfectly.
In the last month, it stops working without any detectable error. Whenever we make any change in the `.policies` file (meaningless changes, like adding a space), it restarts and works well for a couple of minutes or hours, then it simply stops.
There is no relevant record in the Windows event viewer. Logging is enabled, and DebugView is always open: as long as events are handled correctly, their logs are captured and appear, then when it stops - there are no more logs, neither any error log.
I can't figure out what event causes it to stop. But it always resumes with no problem if a change is made to the `.policies` file.
What could be the cause of this weird and annoying behavior?

**Comment by giuliov** [comment]
The "it stops" makes me think that AzDO/TFS marks the plugin as dead for some reason, but you should see a message in the EventLog (IIRC it appears in TFS own log, deep in _Application and Services Logs_ not in _Windows Logs_).
In this scenario, you should touch some file in the Plugins directory to force AzDO/TFS to start a new AppDomain and reload any plugins. It can be a simple text file that you edit for this purpose.

HTH

**Comment by giuliov** [comment]
Ah the "if a change is made to the .policies file" leads exactly in that direction.

**Comment by avrahamcool** [comment]
I've stumble into that exact problem.
maybe someone have a better understanding of that issue by now?
"touching" files in the plugin directory works.. but after a *what seems to be random* duration the plugin stop again.

i've noticed in the logs some errors regarding DataWarehouse. (i'll check what's that about...)
i'm not sure if those were always there or not..

**Comment by jessehouwing** [comment]
That sounds like the TFS Job agent failing. Changing/touching any file in
that folder will auto restart the services.

As a workaround you could probably create a scheduled task that restarts
the Job Agent service.
