### ISSUE TITLE
Azure DevOps 2020 Support

### ISSUE THREAD

**Issue by jessehouwing** [tfsaggregator/tfsaggregator#347]
Looks like this will be the very last version we will support with the server plugin.

You [can find the link to the installer here](https://github.com/tfsaggregator/tfsaggregator/releases).

![image](https://user-images.githubusercontent.com/4173387/86165293-661a6500-bb13-11ea-99ad-046c12c9a00a.png)

**Comment by mcnallys** [comment]
Looks like the beta is linked to the wrong dlls.

![image](https://user-images.githubusercontent.com/26471074/86625087-1c55d280-bf8a-11ea-8609-5fb431b9f383.png)

![image](https://user-images.githubusercontent.com/26471074/86625126-2d064880-bf8a-11ea-995f-966482734035.png)

**Comment by jessehouwing** [comment]
Interesting.... Let me check the build server setup. I build locally
against the installed server...

**Comment by giuliov** [comment]
The Reference DLL are in TFVC IIRC, @jessehouwing

**Comment by jessehouwing** [comment]
I know, I thought I had put in the correct ones...

**Comment by jessehouwing** [comment]
I just pushed an updated installer, same release, since there were 0 code changes, only updating our reference assemblies on the build image.

**Comment by mcnallys** [comment]
Looking good now, thanks!

**Comment by jessehouwing** [comment]
Let me know if you encounter any issues.

**Comment by arvindsedha** [comment]
Hi,
I have a problem, I do not see any logs of Aggregator in the error logs and it either doesn't work. We have DevOps 2020 RC1 On-Premises with Aggregator version 2.6.0-beta.1 installed.
It seems that DevOps 2020 doesn't load the plugin as I see the following error (don't know if it's related to it). Any help will be appreciated!!
TF53010: The following error has occurred in an Azure DevOps component or extension:

C:\Program Files\TFS Aggregator\bin>TFSAggregator2.ConsoleApp.exe run --policyFile="C:\Program Files\Azure DevOps Server 2020\Application Tier\Web Services\bin\Plugins\TFSAggregator2.ServerPlugin.policies" --teamProjectCollectionUrl=http://csitfs2017:8080/tfs/DefaultCollection --teamProjectName=DevTeam --workItemId=63830 --logLevel=diagnostic
TFSAggregator2.ConsoleApp 1.0.0

Build: 2.6.0, Configuration: Release-2020 [TFS 2020]
Copyright (c) TFS Aggregator Team 2015-19
Error: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

**UPDATE** 

Found the way to get it working by copying the Microsoft dlls from 

C:\Program Files\Azure DevOps Server 2020\Application Tier\Web Services\bin

to

C:\Program Files\TFS Aggregator\bin

**Comment by jessehouwing** [comment]
Which ones were missing?

**Comment by giuliov** [comment]
@arvindsedha 
Have you looked at https://tfsaggregator.github.io/docs/v2/admin/troubleshooting/ ?
This is a new install or was working before?
Have you upgraded AzDO Server _after_ installing Aggregator (see https://tfsaggregator.github.io/docs/v2/admin/install/#upgrade-tfs-to-a-new-version)?
Can you share the installed DLL version?
```powershell
$pathToAssemblyFile = "C:\Program Files\Azure DevOps Server 2020\Application Tier\Web Services\bin\Plugins\TFSAggregator2.ServerPlugin.dll"
[System.Reflection.Assembly]::LoadFile($pathToAssemblyFile).GetCustomAttributesData() | ?{ $_.AttributeType -eq [System.Reflection.AssemblyConfigurationAttribute] } | select ConstructorArguments
```
What version you see in the Control Panel installed Apps list?

**Comment by arvindsedha** [comment]
@giuliov  @jessehouwing 

We upgraded the DevOps Server from 2019 -> 2020 and after upgrade I uninstalled the old version away and re-installed 2.6.0.Beta1

Below are my logs, seems plugin is not getting loaded at all

PS C:\Users\asentajacsi> $pathToAssemblyFile = "C:\Program Files\Azure DevOps Server 2020\Application Tier\Web Services\bin\Plugins\TFSAggregator2.ServerPlugin.dll"
PS C:\Users\asentajacsi> [System.Reflection.Assembly]::LoadFile($pathToAssemblyFile).GetCustomAttributesData() | ?{ $_.AttributeType -eq [System.Reflection.AssemblyConfigurationAttribute] } | select ConstructorArguments

ConstructorArguments
--------------------
{"Release-2020 [TFS 2020]"}


C:\Program Files\TFS Aggregator\bin>TFSAggregator2.ConsoleApp.exe run --logLevel=diagnostic --policyFile=..\samples\TFSAggregator2.ServerPlugin.policies --teamProjectCollectionUrl=http://csitfs2017:8080/tfs/DefaultCollection --teamProjectName=DevTEam --workItemId=68236
TFSAggregator2.ConsoleApp 1.0.0

Build: 2.6.0, Configuration: Release-2020 [TFS 2020]
Copyright (c) TFS Aggregator Team 2015-19
Error: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

**Comment by jessehouwing** [comment]
I may look into this after next week. I currently have 0 bandwidth with an extremely busy week coming up and my son's 1st birthday today.

As the release notes say: this version has had very little testing to date.

**Comment by arvindsedha** [comment]
Hi,

@jessehouwing  now it seems it tries to load the plugin but fails with following error

The description for Event ID 47513 from source TFSAggregator cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Exception encountered processing notification: Error HRESULT E_FAIL has been returned from a call to a COM component. 
Stack Trace:   at Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.DataStoreNative64.UpdateMetadata(IntPtr handle, Object rowset, String dbstamp, UInt32& changes)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.Datastore.UpdateMetadata(Object rowset, String dbstamp)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.EndBackendCall(BackendCallData data)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.RefreshCacheInternal(BackendCallData& data)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.InitializeInternal()
   at Microsoft.TeamFoundation.Client.TfsTeamProjectCollection.InitializeTeamFoundationObject(String fullName, Object instance)
   at Microsoft.TeamFoundation.Client.TfsConnection.CreateServiceInstance(Assembly assembly, String fullName)
   at Microsoft.TeamFoundation.Client.TfsConnection.GetService(Type serviceType)
   at Microsoft.TeamFoundation.Client.TfsConnection.GetService[T]()
   at Aggregator.Core.Facade.WorkItemRepository..ctor(IRuntimeContext context) in D:\a\1\s\Aggregator.Core\Aggregator.Core\Facade\WorkItemRepository.cs:line 45
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.<>c.<ProcessEvent>b__2_0(IRuntimeContext runtimeContext) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 68
   at Aggregator.Core.Context.RuntimeContext.CreateWorkItemRepository() in D:\a\1\s\Aggregator.Core\Aggregator.Core\Context\RuntimeContext.cs:line 244
   at Aggregator.Core.Context.RuntimeContext.get_WorkItemRepository() in D:\a\1\s\Aggregator.Core\Aggregator.Core\Context\RuntimeContext.cs:line 258
   at Aggregator.Core.EventProcessor..ctor(IRuntimeContext runtime) in D:\a\1\s\Aggregator.Core\Aggregator.Core\EventProcessor.cs:line 40
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 85

the message resource is present but the message is not found in the string/message table


Best Regards
Arvind

**Comment by jessehouwing** [comment]
Looks like it can't connect to the server for some reason. And failing hard.

**Comment by jessehouwing** [comment]
I just ran a test locally and TFS Aggregator works with my simple policy. Update Metadata happens when the local client cache needs to be refreshed and it stores data in the AppData file system cache of the TFS/AzureDevOfs client. Make sure that the user TFS runs under has sufficient permissions to update that location. Try using SysInternals ProcMon to see if you can catch the reason for the failure.

And check whether the cache may have been corrupted and needs clearing:

Check the Program Data and/or Appdata folder for the user:

```
C:\Users\Administrator\AppData\Local\Microsoft\Azure DevOps\8.0\Cache
C:\ProgramData\Microsoft\Azure DevOps\8.0\Cache
```

https://stackoverflow.com/a/24292703/736079
