### ISSUE TITLE
Move task from one parent to another and fix rollup hours on previous parent

### ISSUE THREAD

**Issue by jasondavidcamp** [tfsaggregator/tfsaggregator#348]
We tend to change the parent of a task from one PBI to another which makes our "Rollup Completed Work" rule only work for the new parent. Are there any helpful tips on solving this issue? 

      if (self.HasParent() && self.Parent.TypeName != "Task")
      {
          var parent = self.Parent;
          parent["Microsoft.VSTS.Scheduling.CompletedWork"] = parent.Children.Sum(task => task.GetField<double>("Microsoft.VSTS.Scheduling.CompletedWork", 0d));
          logger.Log(LogLevel.Information, "Rollup completed work hours from child {0} #{1} to parent {2} #{3}", self.TypeName, self.Id, parent.TypeName, parent.Id);
      }

**Comment by jessehouwing** [comment]
Go back 1 revision, check the old parent, update where needed.

**Comment by jasondavidcamp** [comment]
I like that idea. Thanks for the guidance.

**Comment by jasondavidcamp** [comment]
It doesn't look like I can use the Parent property on the self.PreviousRevision

**Comment by jessehouwing** [comment]
It exposes a WorkItemLinks field, use it to grab the parent.

**Comment by jasondavidcamp** [comment]
When I use WorkItemLinks on the PreviousRevision, it seems to always come back empty.
var linkcount = self.PreviousRevision.WorkItemLinks.Count();

Maybe I'm having the same issue as willstones did [here](https://github.com/tfsaggregator/tfsaggregator-core/issues/10)

**Comment by jasondavidcamp** [comment]
since links on PreviousRevsion don't work, I ended up creating 2 rules

    
    <rule name="RecalculateCompletedWorkForBereavedParent" appliesTo="Bug,Change Request,Epic,Feature,Requirement">
        <![CDATA[
        var currentCompletedWork = self.GetField<double>("Microsoft.VSTS.Scheduling.CompletedWork", 0d);
        var recomputedCompletedWork = self.Children.Sum(task => task.GetField<double>("Microsoft.VSTS.Scheduling.CompletedWork", 0d));
        if (System.Math.Round(currentCompletedWork,2) != System.Math.Round(recomputedCompletedWork,2))
        {
            self["Microsoft.VSTS.Scheduling.CompletedWork"] = recomputedCompletedWork;
            logger.Log(LogLevel.Warning, "{0} Fixed completed work hours on {1} #{2} from {3} hours to {4} hours", System.DateTime.Now, self.TypeName, self.Id, currentCompletedWork, recomputedCompletedWork);
        }
        ]]>
    </rule>

**Comment by jasondavidcamp** [comment]
Updated:
    <rule name="RollupCompletedWork" hasFields="Microsoft.VSTS.Scheduling.CompletedWork">
      <![CDATA[
      if (self.HasParent())
      {
          var parentTypes = new []{"Bug", "Change Request", "Epic", "Feature", "Requirement"};
          if (self.HasParent() && parentTypes.Contains(self.Parent.TypeName)) 
          {
              var parent = self.Parent;
              parent["Microsoft.VSTS.Scheduling.CompletedWork"] = parent.Children.Sum(task => task.GetField<double>("Microsoft.VSTS.Scheduling.CompletedWork", 0d));
              logger.Log(LogLevel.Information, "{0} Rollup completed work hours from child {1} #{2} to parent {3} #{4}", System.DateTime.Now, self.TypeName, self.Id, parent.TypeName, parent.Id);
          }
      }
      ]]>
    </rule>

    
    <rule name="RecalculateCompletedWorkForBereavedParent" appliesTo="Bug,Change Request,Epic,Feature,Requirement">
        <![CDATA[
        var currentCompletedWork = self.GetField<double>("Microsoft.VSTS.Scheduling.CompletedWork", 0d);
        var recomputedCompletedWork = self.Children.Sum(task => task.GetField<double>("Microsoft.VSTS.Scheduling.CompletedWork", 0d));
        if (System.Math.Round(currentCompletedWork,2) != System.Math.Round(recomputedCompletedWork,2))
        {
            self["Microsoft.VSTS.Scheduling.CompletedWork"] = recomputedCompletedWork;
            logger.Log(LogLevel.Warning, "{0} Fixed completed work hours on {1} #{2} from {3} hours to {4} hours", System.DateTime.Now, self.TypeName, self.Id, currentCompletedWork, recomputedCompletedWork);
        }
        ]]>
    </rule>
