### ISSUE TITLE
Condition that enforces separation of duties 

### ISSUE THREAD

**Issue by vmulumoodi** [tfsaggregator/tfsaggregator#350]
A workflow condition that enforces separation of duties (for SAS-70 compliance), i.e. it makes sure that the same user cannot trigger two incompatible transitions or two consecutive transitions on the same issue.

**Comment by jessehouwing** [comment]
Can't be done. Changes are already committed prior to the aggregator running. There is no way to intercept and cancel the unwanted transition.

You'll need to solve that using standard work item customization rules.
