### ISSUE TITLE
Error when calling the tool

### ISSUE THREAD

**Issue by HekoHub** [tfsaggregator/tfsaggregator#351]
When calling the tool the following error appears:
Exception encountered processing notification: Method not found: 'Microsoft.TeamFoundation.Integration.Server.CommonStructureProjectInfo 
Microsoft.TeamFoundation.Integration.Server.ICommonStructureService.GetProject(Microsoft.TeamFoundation.Framework.Server.IVssRequestContext, 
System.String)'. Stack Trace: at Aggregator.Core.Facade.RequestContextWrapper.GetProjectName(Uri teamProjectUri) at 
Aggregator.Core.Configuration.ProjectScope.Matches(IRequestContext requestContext, INotification notification) at 
Aggregator.Core.EventProcessor.<>c__DisplayClass7_0.<FilterPolicies>b__1(PolicyScope scope) at System.Linq.Enumerable.All[TSource]
(IEnumerable`1 source, Func`2 predicate) at System.Linq.Enumerable.WhereListIterator`1.MoveNext() at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
 at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source) at Aggregator.Core.EventProcessor.ProcessEvent(IRequestContext requestContext,
 INotification notification) at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, 
 NotificationType notificationType, Object notificationEventArgs, 
Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties)
Can anyone give us a hint?

**Comment by jessehouwing** [comment]
What TFS version do you have installed and in case you did an upgrade, did you uninstall the aggregator prior to the update?

What version of TFS/ADS? 
What version of TFS Aggregator?

**Comment by HekoHub** [comment]
No, the aggregator was installed on the existing version.T
FS/ADS=2019.0 
TFS Aggregator=v2.5
Thanks

**Comment by jessehouwing** [comment]
Try the latest 2.6, if that works, let me know.

https://github.com/tfsaggregator/tfsaggregator/releases/tag/2.6.0-beta.1.1

>

**Comment by HekoHub** [comment]
Thanks, uninstall the aggregator and installed again has solved the problem!!!
