### ISSUE TITLE
Error while using TFSAggregator2.ConsoleApp with DevOps Server 2020

### ISSUE THREAD

**Issue by Stefan2222** [tfsaggregator/tfsaggregator#352]
I used the setup of Aggregator v2.6.0-beta.1.4 to install for 18.170.30525.1 (Azure DevOps Server 2020).
Using the console app like this TFSAggregator2.ConsoleApp.exe run -h is causing an error:

Error: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

Any usage of the console app is causing this error message.

Using the same setup for TFS 2018 3.2 the console app works fine.

[TFSAggregator2ConsoleApp.docx](https://github.com/tfsaggregator/tfsaggregator/files/5524809/TFSAggregator2ConsoleApp.docx)

**Comment by Stefan2222** [comment]
Any hint on how to slove this issue is appreciated.

**Comment by jessehouwing** [comment]
Quick fix:

 * Copy `$(ServerAssemblies)\Microsoft.TeamFoundation.Framework.Server.dll` and `$(ServerAssemblies)\Microsoft.TeamFoundation.Server.Types.dll` over from the server installation and paste them into the console app folder.

Longer fix:

 * Wait for my build to complete and install the next release: https://github.com/tfsaggregator/tfsaggregator/releases/tag/v2.6.0-beta.1.5. This includes the immediately needed assemblies. I'm hoping that's enough. 

If this won't work, keep copying files from this list till it won't crash:

https://github.com/tfsaggregator/tfsaggregator/blob/develop/References/2020/config.targets#L36-L65

You can find those in the Azure DevOps Serves installation folders.

**Comment by Stefan2222** [comment]
The quick fix works. Thanks a lot!
I´ll check the new release tomorrow.
