### ISSUE TITLE
Not automatically processing rules

### ISSUE THREAD

**Issue by sykokinetyk** [tfsaggregator/tfsaggregator#353]
Hi there,

I have two instances of the Aggregator running.  One on ADO Server 2019.1.1, and one on 2020 RC2.  I have tested my rules/policies successfully using the console application multiple times, but when live updating work items, I do not see anything.

Rule/policy:

<rule name="ApplyPriority" appliesTo="User Story">
    
    <![CDATA[
      foreach (var child in self.Children) {
         var priority = self.GetField<int>("Microsoft.VSTS.Common.Priority", 0);
         logger.Log("Priority = {0}", priority);
         logger.Log("Child Priority is currently {0}", child["Microsoft.VSTS.Common.Priority"]);
         child["Priority"] = priority.ToString();
    }
    ]]>
</rule>
<rule name="ApplyPriorityNewTasks" appliesTo="Task">
    
    <![CDATA[
      if (self.HasParent()) {
         self["Priority"] = self.Parent["Priority"].ToString();
        }
	]]>
</rule>
    <policy name="TestAggregate">
      <collectionScope collections="Demo" />
      <projectScope projects="AggregatorTest" />
      <ruleRef name="ApplyPriority" />
      <ruleRef name="ApplyPriorityNewTasks" />	
    </policy>

I only see any semblance of error in event viewer, which is the following, and only on one of the ADO nodes:

I have attempted re-installing to no avail.  Anything I'm missing that I should try?

**Comment by jessehouwing** [comment]
There were issue with the RC that were fixed in RTW. Please upgrade to RTW
and uninstall/reinstall the aggregator and try again.
