### ISSUE TITLE
Not processing rules

### ISSUE THREAD

**Issue by sevcimic** [tfsaggregator/tfsaggregator#358]
Hello,

we have two nodes of TFS 2017 installed. I recently tried to add TfsAggregator to create some basic rules, but the rules are not processing. I have installed the latest version of TfsAggregator2 on both instances and now I have only one basic rule which only should log one line to DebugView. But in DebugView is only this information and nothing more:
[7096] TFSAggregator: [Information] Configuration loaded successfully from 'C:\Program Files\Microsoft Team Foundation Server 15.0\Application Tier\Web Services\bin\Plugins\TFSAggregator2.ServerPlugin.policies' 
![tfsAggregator_information](https://user-images.githubusercontent.com/60646881/114530771-8dc65e00-9c4b-11eb-91e6-fe77294b5a6e.png)

I am able to catch some not authorized exceptions when I set up the policies file with errors on purpose. But it seems, that if it is set up correctly, it just does nothing. I tried the rule with the console app and it worked correctly.

Can you please help me and tell me, what am I doing wrong?

Here is my policy file (changed to .txt for upload)
[TFSAggregator2.ServerPlugin.policies.txt](https://github.com/tfsaggregator/tfsaggregator/files/6302685/TFSAggregator2.ServerPlugin.policies.txt)

**Comment by giuliov** [comment]
Some ideas:

- Do you monitor debugview on both nodes?
- Have you tried removing/comment the  `<server baseUrl="http://localhost/" />` ?
- Is the collective DNS hostname is reacheable from the nodes themselves (try with curl/prowehsll)?

Note also that the rule will run _only_ for the `Vyroba` collection

**Comment by sevcimic** [comment]
First of all, thank you :)

- Yes, I monitor both nodes. The second node shows nothing for TfsAggregator
- Yes, I have, without success. Then it fails with the exception "You are not authorized to access http://tfs/...". Is this the problem?
- What do you mean by collective DNS hostname? From inside of company network, we are accessing web UI through http://tfs/ and if we are on VPN, we have to use something like http://tfs.servers.company.internal/. Which one should be accessible from nodes themselves? 

I am aware of the collection condition and I want it there.

**Comment by sevcimic** [comment]
And just to add some information. Sysadmin, which is in charge of servers and network settings, told me, that the currently active TFS nod is accessible only through the http://localhost, not through the public URL of TFS from the server itself. By this I mean, that I am not able to open the page http://tfs/ in the browser from the server to which I am connected by RDP. Only http://localhost is working.

I don't understand, that the DebugView is not showing more than Configuration loaded, even when the logging level is set to Diagnostic.

**Comment by giuliov** [comment]
`TF30063: You are not authorized to access` means that the running account has no permission on AzDO/TFS.
You have these mutually exclusive options:

1. Give the account running Azure DevOps service (check on the Administration Console) write permissions to the Collection WorkItems (and some read)
2. set `<authentication autoImpersonate="true" />` (the above account should still have some access as #238)
3. use a PAT to authenticate `<authentication personalToken="****" />` , remember that it expires and must be refreshed
4. `<authentication username="****" password="*****" />` the password is in clear text

**Comment by sevcimic** [comment]
Okay, little progress I think. I tried all options and here are results:

1. `TFS30063 You are not authorized` But the account running TFS is a member of Team Foundation Adminitrators for a long time.
2. `TFS30063 You are not authorized` My account is also member of Team Foundation Administrator group
3. `[7096] TFSAggregator: [Critical]    Exception encountered processing notification: Basic authentication requires a secure connection to the server. `
4. `[7096] TFSAggregator: [Critical]    Exception encountered processing notification: Basic authentication requires a secure connection to the server. `

And if the DebugView logs only those two lines from above, it looks like there is some error in policy file.

So if I understand correctly, I need to talk with sysadmin and try to solve the `You are not authorized` error for members of Team Foundation Administrator group. And other groups. This seems to me that there might be some routing problem with dns name. We will see, what the sysadmin tell me.

Thank you.

**Comment by jessehouwing** [comment]
The service account or admin may not have the required permissions, this is standard, check the checklist on how to grant the permissions:

https://tfsaggregator.github.io/docs/v2/admin/troubleshooting/#server-plugin-checklist

**Comment by sevcimic** [comment]
Well, it's strange I think. Sys admin is telling me, that we are using two nodes with Active/Passive settings. And when is one node as passive, it can't be reached from itself by the public url name of the TFS. Sounds logical, but I am monitoring both servers with DebugView. After a change of Task, which fires TfsAggregator, it shows in one of the nodes an exception with `You are not authorized` and on the other server it shows nothing. So the server, which is showing the error, must be active, right? But why that server cannot reach itself by the public url? The permissions are set correctly, the service account is in Project collection Administrator. Do you have any other idea, what should I check?

**Comment by jessehouwing** [comment]
The interception job Will kick off from any tfsjobagent that's running. So
even if the node isn't reachable from the public url, it will happily
service jobs.

Try shutting down the tfsjobagent service on the passive node to force all
jobs to run on the active node.

**Comment by sevcimic** [comment]
Good news, it's working. Sysadmin changed some settings and it's working flawlessly. Thank you, everyone, I'm closing the issue.
