### ISSUE TITLE
Multiple Executions Causes Kanban Board Issues

### ISSUE THREAD

**Issue by shaneedwards** [tfsaggregator/tfsaggregator#36]
First, thanks for a great plugin--doing a lot of great things with it.

I just setup a fairly complex set of operations to calculate development cycle times during transitions on user stories.  ~~About 75% of the time, when I transition a story via the kanban wall, the Aggregator runs once and everything continues to work perfectly.  About 25% of the time when I transition a story on the kanban wall the aggregator runs twice.~~  It happens every time I change any data through TFS Aggregator using C# scripting.  Now, this doesn't cause a data problem or anything like that, but what it does cause is a strange reaction on the Kanban.  Every time after I see aggregation run twice in my DebugView the next transition attempt will fail (silently) exactly once.  Then on further attempt it works correctly.  ~~This isn't tied to any single transition or anything I can find a pattern to, it appears to happen randomly.~~ It is definitely reproducible.  Please see my next comment with a video of the failure.

It isn't really a breaking issue, but it is aggravating my team because it fails so frequently that they have to pay careful attention on the kanban board.  ~~This issue does not appear to happen if I transition via the form view.~~  Once I found how to reproduce the issue it DOES happen in the form view as well as Kanban board.  

Any help is greatly appreciated--I'm not able to make heads or tails of why it would run twice sometimes or why that would affect kanban transitions only.

![image](https://cloud.githubusercontent.com/assets/7059852/8139667/012c1e7e-111b-11e5-816e-91fad6d6ad41.png)

![image](https://cloud.githubusercontent.com/assets/7059852/8139698/559a30ae-111b-11e5-97a4-7345a395b051.png)

**Comment by giuliov** [comment]
First of all thanks: you are a brave beta tester!
Honestly I have not tested the Board scenario, but I suggest considering reentrancy: after you touch the work item and the plugin saves it, TFS will trigger another change notification that reenters the plugin for the same work item.

**Comment by shaneedwards** [comment]
Thanks for the response, hope you had a good weekend.

I wanted to follow up with more information after additional testing and see if you could offer any further advice.  I was able to find a pattern--this occurs any time I operate on the user story via TFSAggregator.  I do see the reentrancy that you mentioned which, based on some comments in other forums is intentional.  I have handled that problem by setting a 'last modified' field and checking in an IF so that when I make a change it will not process more than once.  The problem I am seeing is that even when I do nothing it appears that TFS gets into some state where the next transition will always fail.  It turns out, this isn't just a Kanban issue, but happens if I manually transition as well.

I will post my slightly modified code and a video of the interaction as well.  In the code snapshot below I have highlighted the two debug outputs that you'll see in the trace window.  


![2015-06-15_09-24-08](https://cloud.githubusercontent.com/assets/7059852/8162042/80de38a6-1340-11e5-8a0f-c22849b8c19a.png)

In this video you'll see me transition to a state that does not run the C# aggregation code (falls through to the else), then transition to the state that runs the code and you'll see in the debug that the first run works fine and the second (reentry) falls through to the else.  Then, the third transition just silently fails.  No debug output, no errors on the screen, just flat rejected.  

https://www.youtube.com/watch?v=MEm5f8Lc9pM

Any insight you can give on what might be cause the issue would be of great help!

**Comment by jessehouwing** [comment]
This may be related to the fact that the web ui doesn't expect the
underlying work item to be changed.

TFS 2015 will make the front-end aware of backend changes through signalR
I've heard, which would solve this issue. I don't think there is anything
you can do to prevent this, other than reloading the screen after a change
if you intend to update the same WorkItem multiple times.

**Comment by shaneedwards** [comment]
Ahhh, that makes sense.  Explains why I wasn't finding an error in the back end or in JavaScript.  It isn't an error, just the UI getting out of sync.  Not to belabor the point, but is there a way to fire off a reload event on the front-end from TFSAggregator?

**Comment by jessehouwing** [comment]
Unfortunately not. That will only happen with the signalR support.

**Comment by shaneedwards** [comment]
Thank you for the assistance.  I'll be waiting patiently for 2015!
