### ISSUE TITLE
Can't Process Multiple Rules

### ISSUE THREAD

**Issue by shaneedwards** [tfsaggregator/tfsaggregator#37]
I assume this is just something I'm not understanding, but I just added a second rule to my policy file and whenever I have more than one rule in the file I get errors.  The first rule takes two fields (probability and impact) and finds bug severity in a matrix and writes the string to a field--fairly straightforward and WORKS when it is the only rule in the file.

If I comment out the bug severity rule and run the second rule, which just sums three separate effort fields into the StoryPoints field, then it works as well.

However, when I turn both rules on (see the XML below) I get the following error:

![image](https://cloud.githubusercontent.com/assets/7059852/8384548/6bae1198-1c07-11e5-9a92-616963edb2d2.png)

The body of that error says: 
```A field definition MyCompany.Agile.Lean.BugProbability in the work item type definition file does not exist```

I know it exists because, first I can see it in my Bug.xml, and second this error doesn't occur with either of the single rules in place and both separately work as expected.  It is almost like the second rule is somehow executing the first rule because the User Story item type does not have the aforementioned BugProbability field.

Am I missing something syntactically here?  Thanks for your help.

```XML
<?xml version="1.0" encoding="utf-8"?>
<AggregatorConfiguration>
    
  <runtime>
      <logging level="Diagnostic"/>
  </runtime>
     
  <rule name="CalcBugSeverity" appliesTo="Bug"><![CDATA[ 
      System.String Probability = (System.String)self["MyCompany.Agile.Lean.BugProbability"];      
      System.String Impact = (System.String)self["MyCompany.Agile.Lean.BugImpact"]; 
                            
      if( Probability != null && Impact != null )
      {          
          int ProbInt = int.Parse( Probability[0].ToString() ) - 1;
          int ImpactInt = int.Parse( Impact[0].ToString() ) - 1;
                                    
          string[,] Matrix = new string[5, 5]
          {
            {"Low", "Low", "Low", "Medium", "Medium"},
            {"Low", "Low", "Medium", "Medium", "High"},
            {"Low", "Medium", "Medium", "High", "High"},
            {"Medium", "Medium", "High", "High", "Critical"},
            {"Medium", "High", "High", "Critical", "Critical"}
          };
                  
          System.Diagnostics.Debug.WriteLine("TFSAggregator: Set bug severity to " + Matrix[ProbInt,ImpactInt]);
          self["MyCompany.Agile.Lean.BugSeverity"] = Matrix[ProbInt,ImpactInt];
      }
      else
      {
          System.Diagnostics.Debug.WriteLine("TFSAggregator: Nothing to do here...");
      }
    ]]></rule>

   
  <rule name="CalcTotalEffort" appliesTo="UserStory"><![CDATA[                  
      System.Diagnostics.Debug.WriteLine("TFSAggregator: Update Story Points Field (Total Effort)");
      self["Microsoft.VSTS.Scheduling.StoryPoints"] = (double)self["MyCompany.Agile.Lean.DevEffort"] + (double)self["MyCompany.Agile.Lean.QAEffort"] + (double)self["MyCompany.Agile.Lean.BAEffort"];
    ]]></rule>
  
    
  <policy name="DefaultPolicy">
    <projectScope projects="Agile Test Project" />
    <ruleRef name="CalcBugSeverity" />
    <ruleRef name="CalcTotalEffort" />
  </policy>

</AggregatorConfiguration>

**Comment by giuliov** [comment]
You should find the code generated from the rules in the `%TEMP%` directory for the TFS service user.

**Comment by jessehouwing** [comment]
It looks ok... are you able to share the process template? Or a minimal
reproduceable set? I scanned through the code and don't see how this would
occur.

A failing test case with just the the xml for the Bug and Userstory would
be ideal to prevent this from happening in the future.

**Comment by shaneedwards** [comment]
Let me see what I can piece together (likely Monday before I have anything to show).  I can, however, confirm that **appliesTo** is not scoping the rules to specific work item types.  **hasFields** also appears to be ignored.  Every rule is being run against any WIT that is altered in the system.  I am working in a custom project template that was originally copied from the Microsoft Agile template.  It does appear that the Policy and Rule scoping is working as expected though.  I ended up moving forward by wrapping all of my rules in Try/Catch blocks so I could continue automating for the time being.

Will update next week with a test-case if I can put one together.

Have a great weekend.

**Comment by giuliov** [comment]
Found a critical bug in the reflection code, not sure I have the time to publish a patch, but I will soon push a PR.
