### ISSUE TITLE
Auto generate tasks creation failing when customized tag is added for work items using TFS aggregator plugin

### ISSUE THREAD

**Issue by vankaaruna** [tfsaggregator/tfsaggregator#371]
We customized user story template to generate the tasks automatically when the specific tag by installing plugin TFSAggregator-2.6.0-beta.1.12-release on Azure Devops server 2019.0.1. It was working fine before upgrade and it's failing after  Azure Devops server from 2019.0.1 to 2019.1.1 patch 10 (On Prem).
Uninstalled the TFSAggregator-2.6.0-beta.1.12-release plugin and reinstalled. Tried installing latest version of plugin TFSAggregator-2.6.1-beta.3-release. Still problem persists.

**Comment by jessehouwing** [comment]
Without logs, the rule, the customized process template we can't support you.

**Comment by vankaaruna** [comment]
Hi Jesse,
Thanks for your response. Would you be ok if  we set up initial meeting to discuss more about the issue? Please let us know your availability.


Thanks,
Aruna Vanka,  Information Technology Specialist - I,
Application Innovation Services(AIS) Operational Services
8260 Longleaf Drive, Elk Grove, CA 95758
916.691.9931 Desk
***@***.******@***.***>

**Comment by giuliov** [comment]
You can find suggestions for logging and troubleshooting in our docs at https://tfsaggregator.github.io/docs/v2/admin/troubleshooting/ and https://tfsaggregator.github.io/docs/v2/admin/logging/
