### ISSUE TITLE
my transitionToState function spams

### ISSUE THREAD

**Issue by pancarr** [tfsaggregator/tfsaggregator#373]
hi,

i use azure devops 2020 and aggregator2.
i have added a new rule in policies file to change a state to another state when conditions are fulfilled. even when conditions met, it spams forever.

this is the rule i wrote. 

![Capture](https://user-images.githubusercontent.com/95170603/143766765-41fddbdb-1c54-4e40-a4a2-e6e35b4884d8.PNG)
![Capture1](https://user-images.githubusercontent.com/95170603/143766783-3695cc7b-3048-46cb-9a8f-8ccaaf1f8408.PNG)

transition in xml

![Capture2](https://user-images.githubusercontent.com/95170603/143766794-c0843442-f7b4-4ac3-8b3c-1897d0780cef.PNG)

spam happens in tfs
![Capture4](https://user-images.githubusercontent.com/95170603/143766800-1c149a2f-8431-40e1-a012-45458ed8371e.PNG)

i also want to say other rules work fine. pls help.

**Comment by jessehouwing** [comment]
I can't see anything immediately wrong with that rule... But it's hard to understand what's going on without understanding the language.

Transition to state will immediately trigger a save, not wait to evaluate whether any other fields changed. It's one if the quirks of the workitem engine.

But I don't see why it would trigger again after the state change given the surrounding if statement.

I'd recommend turning in debug logging and sending that over to us. It'll give a better idea on why the rule triggered and why it forced a save.

**Comment by jessehouwing** [comment]
If there's one thing I'd improve to the rule is to swap the assignment line and the state transition rule.

**Comment by pancarr** [comment]
i swaped their places but it still does the same. 
![image](https://user-images.githubusercontent.com/95170603/143770978-819d0f1e-e9ba-4871-9812-405f1cdcd6a6.png)
 

when conditions are met i want "bölüm başkanı onayı" stage change to "fizibilite onayı".  you can see on picture it has its transition to "fizibilite onayı". but it doesnt change so rule sees  it is still on "bölüm başkanı onayı" stage and put another comment that says stage changed to "fizibilite onayı". if i don't delete  it, it goes on forever. i added else part to check, does it do same to my assigned to field but it doesnt. it changes for one time and that is all.  so i assume problem is transition. but previous rules written before me works fine.

there is one thing that i suspect. transitions are under a file called "Geliştirme Talebi.xml".

![image](https://user-images.githubusercontent.com/95170603/143771293-f86d7c3d-37d9-48ef-b526-a059354a7ffe.png)
 as you can see it is under Feature Category. i just added "Bölüm Başkanı Onayı" recently just to "Geliştirme Talebi". should i also add to the defaultworkitemtype? 


before coming here i also suspected maybe required fields caused to not pass other stage but i  made a rule "Bölüm Başkanı Onayı" to the my default start stage "Yeni". it also stucks in loop. i have checked if i did any spelling mistake but i cant see. on tfs pipeline works fine and publish my changes. it triggers release and it also works without problem. if there is anything i could to help you understand better or anything want me to try please let me know.

**Comment by jessehouwing** [comment]
Turn on debug logging.

https://tfsaggregator.github.io/docs/v2/admin/logging/

Or run the console app to get more details of what's going on. Without the
logs, any help from us is going to be guess based.

It's also possible another rule is interfering.

The logs will help you better understand what is happening and what rules
are triggering.

**Comment by pancarr** [comment]
hi, i am here to give update. as you suggested i checked logs though it took time to reach machine that holds aggregator. as you guessed another rule was interfering. thx for the help. appreciate it.

**Comment by jessehouwing** [comment]
Thanks for letting us know!
