### ISSUE TITLE
Migration guide

### ISSUE THREAD

**Issue by millusdk** [tfsaggregator/tfsaggregator#376]
Hello Tfsaggregator,

We are currently investigating upgrading our usage of TFS Aggregator from the plugin (v2) version to using the CLI/Docker version.
In order to perform the migration, it seems that we need to update our current policy file to the new format. Is there any migration guide for this?

Best regards,
Emil

**Comment by jessehouwing** [comment]
No. There isn't any. We tried to keep the main work item API mostly
compatible. But the way policies are defined is completely new.

**Comment by millusdk** [comment]
HI Jesse.

Thank you for your quick reply. Sounds good that the API should mostly be the same.
In our current setup, we have filters on the rules such that some of them are only run on specific projects, is this supported in the functions/docker model?

Best regards,
Emil

**Comment by jessehouwing** [comment]
Yes. You can map rules to specific projects: https://tfsaggregator.github.io/docs/v3/commands/map-commands/

**Comment by millusdk** [comment]
Great, so a rule is not applied until it is mapped, is that correctly understood?

**Comment by jessehouwing** [comment]
That's my understanding, but now you're asking the maintainer of aggregator2 how the rules in aggregator-cli work. @giuliov is the core maintainer of the new version.

For specific questions, please start a discussion here: https://github.com/tfsaggregator/aggregator-cli/discussions

Or for problems and bugs, open an issue here: https://github.com/tfsaggregator/aggregator-cli/issues
