### ISSUE TITLE
TFSaggregator is not working after upgrading TFS2018 to azuredevops 2020. kindly help , i have uninstall and install TFS aggregator 

### ISSUE THREAD

**Issue by indreshmourya1106** [tfsaggregator/tfsaggregator#377]

**Comment by jessehouwing** [comment]
Have you moved the policy file to the new folder Azure DevOps server was installed into?

**Comment by indreshmourya1106** [comment]
> Have you moved the policy file to the new folder Azure DevOps server was installed into?

"yes"

**Comment by giuliov** [comment]
Is the Aggregator version you installed the latest? An old version would not recognize 2020.
It was a single server or a dual server upgrade? If dual, you must reinstall Aggregator on both servers.
Have you checked the Windows Event Log for errors?

**Comment by indreshmourya1106** [comment]
We have single server  and install TFS aggregator  version - tfsaggregator-2.6.1-beta.3.
After installing TFS aggregator , no "bin" folder is created under " C:\Program Files\TFS Aggregator" , and no files related to TFS aggregator found under  "C:\Program Files\Azure DevOps Server 2020\Application Tier\Web Services\bin\Plugins"

**Comment by giuliov** [comment]
Try remove (uninstall) and reinstalling.
If you lunch installer from an elevated command line prompt, you can get a detailed log, e.g.
```cmd
msiexec /i "TFSAggregator-2.6.1-beta.3-release.msi" /l*v "TFSAggregator-install.log"
```

**Comment by indreshmourya1106** [comment]
"Bin" folder is not created .
does it support azure devops server 2020 1.1 version?

**Comment by jessehouwing** [comment]
When you run the installer, which packages are enabled to install? Is the server plug-in for your version and the commandline tool selected to be installed?

Can you share the installer logs?

**Comment by indreshmourya1106** [comment]
Does TFS aggregator work on azure devops 20201.1 version?

**Comment by indreshmourya1106** [comment]
HI team,

TFS aggregator is not supported in azure devops server 2020 version.
Kindly suggest.


Best regards,
Indresh Mourya
Lead DevOps Engineer
TietoEVRY, Credit Solutions & Services

**Comment by jessehouwing** [comment]
I've confirmed proper operation in 2020 multiple times. We just added experimental support for 2022. But the project is in deprecated mode and the support we can provide on the server plugin is minimal.

If you want an investigation from my end, you can hire me or a colleague through xpirit. But given that this an open source project that is 3 year over it's deprecation announcement I'm not really able to provide you with more support than a the link to the troubleshooting guide.

**Comment by jessehouwing** [comment]
These versions are supported:

https://github.com/tfsaggregator/tfsaggregator/blob/develop/Setup.Aggregator/Product.wxs#L304

**Comment by jessehouwing** [comment]
Follow the debug & diagnostics in the help section of the docs pages. I
can't geve you other advice than that until you have logs to share of a
better understanding of what's broken.
