### ISSUE TITLE
TFS 2015 support | Implemented, needs testing

### ISSUE THREAD

**Issue by giuliov** [tfsaggregator/tfsaggregator#39]
Testing everything works on 2015

**Comment by DEllingsworth** [comment]
Is this version working at all in TFS 2015 currently?  So far it is not even giving me debug messages.

**Comment by jessehouwing** [comment]
It surely needs to be recompiled against the new object model and given
that this model is no longer stored in the GAC, we may need to alter the
code a bit for assembly-resolving to work.

A simple upgrade-solution+recompile failed. Pull-request welcome ;).

**Comment by AaronKowall** [comment]
Any further digging into this?  May be a showstopper for a TFS 2015 upgrade at a client.

**Comment by jessehouwing** [comment]
I'll see what I can do this weekend. No guarantees, as our daughter could
be born any day now.

**Comment by jessehouwing** [comment]
Work remaining:

Remaining issues:
- [] Paths to server object model are currently hardcoded, needs to use the TfsReferences.targets file again now that teh NuGet packages work.
- [] ProcessTemplateVersion object needs to be wrapped for testability
- [] Code compiles, tests pass, but no server deployed verification so far.

**Comment by jessehouwing** [comment]
@AaronKowall, I updated a 2015 development branch with the latest bits and made it work with the 2015 object model. I suspect we'll want to work on creating either a single solution that works with both 2013 and 2015 or will split into 2 different master branches going forward.

If you want to test this version on your side, you'd make me a very happy man, I do not really have the time on my hands at the moment to setup a test environment and perform a full regression test.

**Comment by jessehouwing** [comment]
@giuliov can you fix the build by creating a 2015 reference zip and putting these in blob storage?

**Comment by DEllingsworth** [comment]
Thanks! I attempted my own upgrade last week but had some struggles with the new object model.  I'll test your changes tomorrow!

**Comment by AaronKowall** [comment]
@jessehouwing Thanks, I'll try to give it a test today.  Else tomorrow.

**Comment by DEllingsworth** [comment]
The GetCollectionUriFromContext routine seems to be broken for 2015. The TeamFoundationLocationService seems to be depreciated.

**Comment by jessehouwing** [comment]
> The GetCollectionUriFromContext routine seems to be broken for 2015. The 
> TeamFoundationLocationService seems to be depreciated.

This has been fixed.

**Comment by jessehouwing** [comment]
Merged with Develop. This branch now supports both TFS 2013 and TFS 2015 using different Build Configurations.

Impact of API differences is currently minimal.
