### ISSUE TITLE
Azure DevOps 2022.1 RTW

### ISSUE THREAD

**Issue by millusdk** [tfsaggregator/tfsaggregator#397]
Hello maintainers,

Microsoft has released the final version of Azure DevOps Server 2022.1, is there any chance of an updated version that can work with that version, or will the existing 2.7.0-beta.1 work with that version?

Best regards,
Emil

**Comment by jessehouwing** [comment]
I'll take a pull request as TFS aggregator (plugin) is considered deprecated and I try not to spend my time on it.

It will likely keep working if you upgrade Azure DevOps over it.

If you uninstall the TFS aggregator it will likely not detect Azure DevOps Server when you try to reinstall it.

This PR could be used as a guide, I expect only the product.wxs needs updating to add the right build numbers:

https://github.com/tfsaggregator/tfsaggregator/pull/393

**Comment by millusdk** [comment]
Thank you for your quick reply. We tried installing 2022.1 on top of the existing 2022.0.1, but the plugin did not work after this. However, I cloned the repository, copied the required dll-files across (I needed to add a manual reference to the Core.WebApi.dll despite placing it in the same folder as the other references) and built a new version of the plugin.
After copying the new dll's to the Plugins folder, the policies were executed again.

Would a "official" release in these circumstances require anything other than simply updating the products.wxs-file as you write?
If that is all that is needed, then I believe I would be able to provide such a PR.

**Comment by jessehouwing** [comment]
Most of the times, updating the `product.wxs` would do it. The additional work is to test the installer against that version of Azure DevOps Server and ensuring the plugin loads and runs as expected.

**Comment by millusdk** [comment]
That sounds like something I should be able to do :) The installer just places the dll-files in the correct folder right?

**Comment by jessehouwing** [comment]
> That sounds like something I should be able to do :) The installer just places the dll-files in the correct folder right?

Yups. And reads the correct folder from the registry.

And the description of the installation component may need an update of the version.

**Comment by millusdk** [comment]
I have created a PR with the changes to Product.wxs

**Comment by jessehouwing** [comment]
Just created the release. Can you verify the official bits?

**Comment by jessehouwing** [comment]
https://github.com/tfsaggregator/tfsaggregator/releases/tag/v2.7.0-beta.2

**Comment by millusdk** [comment]
Yes, I will test it later, can't mess with the Azure DevOps Server at this moment since the team is using it :)
