### ISSUE TITLE
Console_app: what-if warning even if not using the flag & Error: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by patrick-13x** [tfsaggregator/tfsaggregator#399]
Hi, 

I'm trying to evaluate rules from the console app and I get a what-if warning even if I'm not using the flag. 
I'm also getting this error: Error: Object reference not set to an instance of an object.
The policy file is configured as per documentation. 

Can you help? 

Thanks in advance

**Comment by jessehouwing** [comment]
The Aggregator CLI project is deprecated. Has been for over 2 years now. Please ensure you've used the correct repo to report any issues. This repo is for the TFS Aggregator Plugin that installs a DLL on the Azure DevOps Server itself.

There [are separate repos for the newer (and better supported) aggregator-cli project](https://github.com/tfsaggregator/aggregator-cli).

Debugging and troubleshooting steps for [both v2 (plugin)](https://tfsaggregator.github.io/docs/v2/admin/troubleshooting/) and [v3 (cli)](https://tfsaggregator.github.io/docs/v3/troubleshoot/) are available on the docs site.

If you're on V2, much more than opening the solution in Visual Studio on a machine that locally has your version of Azure DevOps Server installed (doesn't have to be configured nor running) and hitting F5 is the guidance I really want to give, unless you really have no other options.

The least you can do to help is provide the version you've installed, exact commands you're running and enabling verbose logging (`--logLevel=giagnostic`) and sharing the minimal ruleset file that causes the issue. That way we might be able to reproduce.

I can offer paid support if needed.

**Comment by patrick-13x** [comment]
Hi @jessehouwing , 

thanks for your reply. 
Actually I'm using the console app that comes with the plugin version to test the rule policy against the server. Version is latest beta2 on AzDevOps Server 2022.1 w/ latest patch applied.
I'm trying with a simple command that looks like the sample invocation showed in the documentation `TFSAggregator2.ConsoleApp.exe -f <policy file path> -c <colection URL> -p <project name> -n <work items IDs> -l Diagnostic`.
The ruleset is pretty much the sample one with some minimal edit (project name, autoimpersonate). Here's what I get: 

```
[Information] 00.065 TFSAggregator2.Core started, version: 1.0.0+c9132b2151d2ece98e71f56368c09878958bbb3d, build: 2.7.0, configuration: Release-2022.1 [TFS 2022.1]
[Information] 00.251 Configuration loaded successfully from 'C:\Program Files\TFS Aggregator\samples\TFSAggregator2.ServerPlugin.policies'
[Warning]     00.252 WhatIf flag: no change will be saved.
Error: Object reference not set to an instance of an object.
```

I also had a weird exeperience with the docker version which I reported here: [aggregator-cli/issues/#291](https://github.com/tfsaggregator/aggregator-cli/issues/291)


Thank you in advance for your help

Patrick

**Comment by jessehouwing** [comment]
There might be bugs en that version, it was provided by another person who
wanted it working on their server.

I don't have an actual on-prem environment to test this against, nor a
customer that relies on it.

**Comment by patrick-13x** [comment]
Hi @jessehouwing,

which one do you think it's the most recent stable and tested version to be used in a company environment? I noticed they're almost all betas.

**Comment by jessehouwing** [comment]
I haven't done a proper release in 3 years since we put up the deprecation
notice.

What server version are you using, you may be able to go back a few
releases. Nothin has changed in the code other than binding the code to the
right assembly versions and making the installer understand the server
versions.

But you can't run an older version of the aggregator plugin against a newer
version of the server. So if you're on 2022.1, then this version is the
only one that will work.

**Comment by jessehouwing** [comment]
Locally in the debugger and on a machine that has Azure DevOps Server 2022.1 installed, I'm not seeing your error. It might be that the installer should package another assembly that's missing on your computer. Are you running the tool on the Azure DevOps Application Tier itself or from your development workstation? Have you tried installing (next, next, finish the installer) Azure DevOps Server 2022.1 locally to see if that fixes things?

**Comment by patrick-13x** [comment]
Hi,
 
thanks for your reply, actually I tried both (directly from tier and from dev machine) but the results are the same. I installed the plugin using the latest version released with conventional procedure (next, next). 
Worth to notice that the error appeared all of a sudden when trying to move to production (using actual plugin) but console testing was working fine right after installation.
