### ISSUE TITLE
Update Appveyor build script to pull references for TFS2013 and TFS2015

### ISSUE THREAD

**Issue by jessehouwing** [tfsaggregator/tfsaggregator#51]
@giuliov can you update the build script to build both TFS 2013 and TFS 2105 packages?

The build now also needs to restore two reference packages, the TFS2013 client and server object model and the TFS 2015 server object model.

 - [x] Configurations to build: Debug-2013, Debug-2015, Release-2013, Release-2015
 - [x] Platform to build: Any CPU
 - [x] upload references for TFS 2015
 - [x] unpack 2013 references to "references\2013" instead of "references"
 - [x] unpack 2015 references to "references\2015"

**Comment by giuliov** [comment]
Sure.

**Comment by jessehouwing** [comment]
Script updated to build all 4 configurations and package the outcomes.

The binaries for 2015 still need to be uploaded to blob storage and added to the script for download.

**Comment by giuliov** [comment]
I worked on this let me finish it

 

Saluti,

Giulio

**Comment by jessehouwing** [comment]
Thanks :). Created a task list in the initial comment.

**Comment by giuliov** [comment]
@jessehouwing I have a problem with 2013 version: you used new C#6 stuff which won't retro-compile. Option 1: compile both versions with 2015/6.0
Option 2: roll back your changes

For now I implement the first one, leaving a comment in the Appveyor script if we want to support VS2013

**Comment by giuliov** [comment]
Build is green, need to understand how to manage multiple artifacts. I suspect that we have to add instructions to install 2015 client API or include them in the package.

**Comment by jessehouwing** [comment]
I made the conscious choice to work only in 2015 due to the improved code
Analysis and quality tools.

The c#6 features are a nice addition that made a few things easier.

I say we only support building from vs2015. Easier to maintain and easier
to ensure that all versions work.

I'll check which client assemblies are needed and whether they're present
in the server assembly folder.

**Comment by jessehouwing** [comment]
Looks like all dependent assemblies are already part of the 2015 apptier installation:

````
C:\Program Files\Microsoft Team Foundation Server 14.0\Application Tier\Web Services\bin
````

No need to redistribute files from the Nuget package in that case.
