### ISSUE TITLE
Sum to parent fails for multiple fields

### ISSUE THREAD

**Issue by Swoffa** [tfsaggregator/tfsaggregator#54]
We have the following rule in our policy file:
```
    <rule name="RollupTask" appliesTo="Task">
        <![CDATA[
        if (self.HasParent())
        {
            self.Parent["Microsoft.VSTS.Scheduling.CompletedWork"] = self.Parent.Children.Sum(task => (double)task.GetField<double>("Microsoft.VSTS.Scheduling.CompletedWork", (double)0));
            self.Parent["Microsoft.VSTS.Scheduling.RemainingWork"] = self.Parent.Children.Sum(task => (double)task.GetField<double>("Microsoft.VSTS.Scheduling.RemainingWork", (double)0));
            self.Parent["Microsoft.VSTS.Scheduling.OriginalEstimate"] = self.Parent.Children.Sum(task => (double)task.GetField<double>("Microsoft.VSTS.Scheduling.OriginalEstimate", (double)0));
        }
        ]]>
    </rule>
```

It works fine if any single field (CompletedWork, RemainingWork or OriginalEstimate) is changed, ie the user story is updated with sums from the tasks, but if two or three fields are changed at the same time, only the first is summed up correctly (the others remain unchanged). In the event log on the TFS server everything seems fine as far as we can see.   

The purpose here is to sum up the values from task to user stories. We also have similar rules for user story to feature, task to bug and task to issue.  

Are we doing something wrong? Is there a simpler way to achieve what we want? Is this a bug?

**Comment by giuliov** [comment]
Have you tried to raise the logging level as described in docs/Troubleshooting.md ? It is very detailed and may help a lot in visualizing what is happening.

**Comment by jessehouwing** [comment]
It may have to how with how Children are loaded, if it loads the same workitem multiple times, it may cause only one set of changes to be written. But I'd have to run a couple of tests to be sure.

**Comment by jessehouwing** [comment]
Looking at the sources, this may fix the issue:

WorkItemRepository.cs:

        public IWorkItem GetWorkItem(int workItemId)
        {
            if (this.workItemStore == null)
            {
                this.ConnectToWorkItemStore();
            }

            // CHECK: do we need to do some locking to support async access?
            var previouslyLoaded = loadedWorkItems.FirstOrDefault(wi => wi.Id == workItemId);
            if (previouslyLoaded != null)
            {
                return previouslyLoaded;
            }
            else
            {
                IWorkItem justLoaded = new WorkItemWrapper(this.workItemStore.GetWorkItem(workItemId), this, this.logger);
                this.loadedWorkItems.Add(justLoaded);
                return justLoaded;
            }
        }

**Comment by Swoffa** [comment]
Thanks @jessehouwing and @giuliov for quick feedback!!  
Your suggestions lead us into using a variable for the parent, which solved our problem.
Rule now looks like this:
```
    <rule name="RollupTask" appliesTo="Task">
        <![CDATA[
        if (self.HasParent())
        {
            var parent = self.Parent;
            parent["Microsoft.VSTS.Scheduling.CompletedWork"] = parent.Children.Sum(task => (double)task.GetField<double>("Microsoft.VSTS.Scheduling.CompletedWork", (double)0));
            parent["Microsoft.VSTS.Scheduling.RemainingWork"] = parent.Children.Sum(task => (double)task.GetField<double>("Microsoft.VSTS.Scheduling.RemainingWork", (double)0));
            parent["Microsoft.VSTS.Scheduling.OriginalEstimate"] = parent.Children.Sum(task => (double)task.GetField<double>("Microsoft.VSTS.Scheduling.OriginalEstimate", (double)0));
        }
        ]]>
    </rule>
```
This works for now, but it is even nicer if your fix is permanently implemented.

**Comment by jessehouwing** [comment]
That seems to confirm my suspicion. My alternative workaround was to do exactly what you just did.

**Comment by jessehouwing** [comment]
Would you be able to confirm by trying https://ci.appveyor.com/project/giuliov/tfsaggregator/build/2.0.60-develop once it finished compiling.

**Comment by Swoffa** [comment]
We tried it and it works like a charm. Thanks!
