### ISSUE TITLE
Implement ITeamfoundationRequestFilter to allow us to create a NotificationPoint and roll back changes

### ISSUE THREAD

**Issue by jessehouwing** [tfsaggregator/tfsaggregator#59]
See: https://msdn.microsoft.com/en-us/library/microsoft.teamfoundation.framework.server.iteamfoundationrequestfilter_methods.aspx

By catching, parsing and updating the REST, WebAccess and SOAP message for Work Item Save we may be able to provide a NotificationPoint option.

**Comment by jessehouwing** [comment]
See also: https://social.msdn.microsoft.com/Forums/vstudio/en-US/c1a2bfc8-d039-48fc-b70e-0d47b1da70c5/is-there-a-workitempresaveevent?forum=tfsworkitemtracking

**Comment by giuliov** [comment]
Sample code here https://conradoclarkdeveloper.com/tag/iteamfoundationrequestfilter/
