### ISSUE TITLE
If one of child WITs dont have field than is need to be changing - no one will be saved

### ISSUE THREAD

**Issue by ASolovyev** [tfsaggregator/tfsaggregator#64]
For example:

    <rule name="CopyProduct"
          appliesTo="User Story; Product backlog Item; Technical Story; Bug">
       <![CDATA[
        if (self.HasChildren())
        {
          foreach (var child in self.Children)
            {
                child["Custom.Product"] = self["Custom.Product"];
            }
        }
        ]]>
     </rule>

If one of child WITs have not Custom.Product - aggregator will not save all scope of child WITs

Sorry for bad english :(

**Comment by giuliov** [comment]
Your best option is to use the `hasFields` attribute of the `rule` element, like this
```
<rule name="CopyProduct"
      appliesTo="User Story; Product backlog Item; Technical Story; Bug" hasFields="Custom.Product">
```

**Comment by jessehouwing** [comment]
Or you can use: 

```
var child in self.Children.Where(child => child.Field.Any(field => field.ReferenceName == "Custom.Product")
```

instead of just 

```
var child in self.Children
```

**Comment by ASolovyev** [comment]
Thank you!

i will use this:
    var child in self.Children.Where(child => child.Field.Any(field => field.ReferenceName == "Custom.Product")
