### ISSUE TITLE
Create Tips, Tricks & Pitfalls page in documentation

### ISSUE THREAD

**Issue by jessehouwing** [tfsaggregator/tfsaggregator#66]
Tricks & Tips:

 - [x] Use HasFields to create rules for any work item type, even if the schema changes
 - [x] Efficiently fetching related work items through the Lazy query API.
 - [x] Setup the RateLimiting feature to prevent disasters
 - [x] Use Debug Viewer to see what's going on behind the scenes
 - [x] Log events from your own rules
 - [x] Use the TemplateScope to enable a given set of rules for all projects with a specific template
 - [x] Write your rules using the ReferenceName for fields, that way your rules will work on process templates in different languages (and are more likely to survive TFS upgrades unharmed).
 - [x] If all you do is play with strings, also check out this little known feature in WIT customization. (see: https://msdn.microsoft.com/en-us/library/ff731584.aspx)

Pitfalls

 - [x] Beware of the History field. (see #65)
 - [x] Beware of cascading changes over a large number of work items (use max depth on lazy query api)
 - [x] Any field can return null, make sure to keep this in mind when casting values (see #63)
 - [x] Don't forget to setup the Eventlog 
 - [x] Don't forget to give the service account permissions to change your work items (on behalf of others if you have enabled impersonation)

**Comment by giuliov** [comment]
I am thinking to change the documentation. Today we keep the MD files in the same repository with the code.

I would move them to the Wiki, so:
 - other people can add/edit without forking
 - no build triggered for editing a typo

To keep in the tradition of off-line documentation, I can add a build step to grab a snapshot of the wiki and ad it to the zip package.

**Comment by jessehouwing** [comment]
I think it's possible to move the main docs to a separate branch in the
repo... Let me check that.

**Comment by giuliov** [comment]
Github-pages option is heavier, if you want to setup an entire project site.

**Comment by giuliov** [comment]
I will start work on the wiki as the next task, if you have nothing against Notice that the wiki is backed by a git repository, so full history and ability to work off-line.

**Comment by giuliov** [comment]
I am tired of writing documentation. Take a cursory look a the wiki... and fill some gaps.
BTW The wiki is open for contribution to anyone. I would love to see contribution like @shaneedwards'.

**Comment by jessehouwing** [comment]
Nice! I'd love people to start contributing rulesets. Especially ones that
work on the standard templates.

Thanks for taking this up! You're a machine :)
