### ISSUE TITLE
V2 rules engine

### ISSUE THREAD

**Issue by nancpasc** [tfsaggregator/tfsaggregator#67]
Hi,

I'm currently trying to make the beta plugin work with TFS 2015.

I've read the policies samples files in order to get an idea on how to work with the new rules engine. However, I've noticed that the most comprehensive sample, "allInOne.policies", does mix C# and VB language syntax, and I'm unable to get it work properly. Is it supposed to work as is ?

Best regards.

**Comment by giuliov** [comment]
That sample uses Powershell, but it has not been review since long: do not trust it too much for now.

**Comment by nancpasc** [comment]
I didn't realized it was PS. Thanks a lot !
