### ISSUE TITLE
Replace  .NET scripting api with Roslyn scripting api? 

### ISSUE THREAD

**Issue by jessehouwing** [tfsaggregator/tfsaggregator#68]
https://github.com/dotnet/roslyn/tree/master/src/Scripting/Core

**Comment by giuliov** [comment]
It would be nice for sure. Things to consider:
 * we should limit ourselves to .NET Framework 4.5.1 (TFS 2013 requirement) even better 4.5 (TFS 2012)
 * Roslyn Nuget package lacks this feature, and suspect it will be hard to manage via source code

**Comment by jessehouwing** [comment]
Makes sense, so this would have to be a separate add+on just for 2015 onwards.
