### ISSUE TITLE
Scripting support

### ISSUE THREAD

**Issue by rbanks54** [tfsaggregator/tfsaggregator#7]
I've been thinking about what we need to do to support scripting in the solution

Here's what I came up with:

- [ ] Put all scripts in a single user folder, not under the TFS folder (to avoid restarting TFS)
- [ ] Put a file watcher on that folder and reload scripts when needed, to avoid having to load scripts for each changed work item
- [ ] Call _all_ scripts in the event processor. i.e. let the script figure out if it wants to act on a work item
- [ ] Pass the basic details of the work item to the script, and let the script decide if it wants to load the full details of the script and any parents/children/related items before doing an calculations/actions.
- [ ] Either let the script also save the work item, or pass the script a function for saving the work item. There is a challenge with this, in that work items are next to impossible to de/serialize because of the TFS object model design
- [ ] For performance work out how to prevent reevaluation of work items when they are saved and not trigger another processing loop (this is probably a separate issue though)

In terms of scripting langauges, I'd prefer JavaScript as it's the most widely known/used thing these days.
I tried using Edge.js and got some simple interaction working but I've been having problems with more complex objects and callbacks to C# code.  That said, if we just send the work item to the JS script, and the script then uses the REST API (which would require TFS 2015) so there's likley no need to be any more complex than that.

Lua/Python, I'm less keen on simply because I don't know them.
ScriptCS might be an option. I don't know how easy it would be to directly call the server side API with it, but I doubt it would be hard.
And of course, there's powershell. Duh!

As a note, there's nothing stopping us supporting multiple scripting languages so that people have a choice. We'd just use a convention based on the file extension to decide which script engine to use at the time.

Effectively this would massively simplify TFSAggregator as it would become nothing more than a task runner, listening for work item changed events and calling scripts. The complexity would then be in the scripts themselves. We'd need to provide sample scripts that cover all the usage scenarios we currently support, but that shouldn't be a big deal.

Thoughts?

**Comment by jessehouwing** [comment]
I'd still prefer to have the scripts in a Source Control repo. On file system is horrible for large instances where file system access on a AT server requires lots of paperwork. I'm not entirely sold on "let the script decide". It would be expensive to run all scripts every time and each script would have to do teh same basic checks to see if it's applicable. 

For situations where scripts are different between projects and/or collections configuration will become a nightmare, unless there is a simple mapping as we worked on before.

It would be a great solution for fully centrally managed instances where only a dedicated team creates and manages the process template.

**Comment by rbanks54** [comment]
Scripts in source control - fair enough. We just need to add a notification for when the folder changes so we can grab the updated versions.  Should be easy enough using both TFVC and git.

It's not that expensive to run them all each time if we pass basic WI information so that scripts don't need any more information before deciding if they need to do expensive operations. The performance optimisation is in keeping the scripts loaded in memory (depending on the scripting engine) to avoid startup costs and running them asynchronously, if possible.

**Comment by giuliov** [comment]
I opt to leave the code flexible to easily support more than one scripting language, could be the configuration file that specify which use.
Cons: more testing and documentation effort.
I will stick to C#, at least in this phase, because it is easy to debug and integrate.

As for where to store the script, the idea of reading them from file system and a separate mechanism to pull new copies from version control is my choice. See #19

**Comment by giuliov** [comment]
In commit f60ab I added ability to select which scripting language. To me VB can be the simplest to read of all (https://github.com/tfsaggregator/tfsaggregator/blob/develop/UnitTests.Core/ConfigurationsForTests/SumFieldsOnSingleWorkItemVB.policies).
