### ISSUE TITLE
Aggregate remaining work to parent issue - decreasing! 

### ISSUE THREAD

**Issue by Prybe** [tfsaggregator/tfsaggregator#70]
Hi, 

 I followed the sample for a simple rollup. 

 _self.Parent["Custom.RemainingWork"] = (double)self.Parent["Custom.RemainingWork"] + (double)self["Microsoft.VSTS.Scheduling.RemainingWork"]; 

 It works fine. 

 But the Problem is that the parent value will be increased with every change. 
 If the child has a value of 5, the parent value will be increased by 5. 
 When I change the child value from 5 to 2, the parent value will be increased be 2. 
 But it should be decreased with 3. 

 So I want to aggregate the difference from the new value to the old value and not the raw new value only. 
 I need to decrease the parent value also. 

 Could you help me please? 
 What can I do to achieve this goal? 

 thanks in advance 
 Martin

**Comment by giuliov** [comment]
If you want to manage deltas, a simple way is adding an hidden field, say `Custom.PreviousRemainingWork`. The rule will become something like

```
double delta = (double)(self["Custom.PreviousRemainingWork"]??0d) - (double)self["Microsoft.VSTS.Scheduling.RemainingWork"];
self.Parent["Custom.RemainingWork"] = (double)self.Parent["Custom.RemainingWork"] + delta;
self["Custom.PreviousRemainingWork"] = (double)self["Microsoft.VSTS.Scheduling.RemainingWork"];
```

There could be other ways, but more complicated.
