### ISSUE TITLE
Compatibility with TFS 2015 update 1

### ISSUE THREAD

**Issue by jessehouwing** [tfsaggregator/tfsaggregator#71]
Microsoft has made a few breaking changes, requiring us to solve these issues if we need to support it:

http://blogs.msdn.com/b/visualstudioalm/archive/2015/10/13/breaking-change-in-tfs-2015-update-1-for-server-side-plugins.aspx

Breaking interfaces:

 * TeamFoundationRequestContext  -> IVssRequestContext 
 * TeamFoundationServiceHost -> IVssServiceHost 
 * ITeamFoundationService -> IVssFrameworkService 
 * DeploymentServiceHost -> IVssDeploymentServiceHost  

Todo:

 * [x] Add new solution configurations
 * [x] Create zip file for dependent assemblies
 * [x] Update build definition
 * [x] Update solution to use these new interfaces

**Comment by giuliov** [comment]
This will delay RTM'ing. Yet another environment to add to test matrix :-(.

**Comment by jessehouwing** [comment]
Fixed the build in the dev branch to build 2013, 2015 correctly now.

We'll need to store a new set of reference assemblies for the build definition in order to build 2015.1.

@giuliov, can you pick that up? The TfsReferences.targets is already up to date.

**Comment by giuliov** [comment]
Working on it

**Comment by jessehouwing** [comment]
Make sure to pull latest bits I just committed to develop.
