### ISSUE TITLE
Support Powershell Get-Siblings and Get-Parent methods

### ISSUE THREAD

**Issue by BrentAutry** [tfsaggregator/tfsaggregator#72]
Using tfs 2015

[Critical]    00.296 Exception encountered processing notification: Object refer
ence not set to an instance of an object.
Stack Trace:   at Aggregator.Core.Facade.WorkItemRepository.GetWorkItem(Int32 wo
rkItemId) in C:\projects\tfsaggregator\Aggregator.Core\Facade\WorkItemRepository
.cs:line 45
   at Aggregator.Core.EventProcessor.ProcessEvent(IRequestContext requestContext
, INotification notification) in C:\projects\tfsaggregator\Aggregator.Core\Event
Processor.cs:line 58
   at Aggregator.ConsoleApp.RunCommand.Run(String[] remainingArguments) in C:\pr
ojects\tfsaggregator\Aggregator.ConsoleApp\RunCommand.cs:line 105

Policy:

<?xml version="1.0" encoding="utf-8"?>
<AggregatorConfiguration>

```
<runtime>
    <logging level="Diagnostic"/>
    <script language="Powershell" />
</runtime>

<!-- When all Tasks are done being worked on, set the parent (Bug or PBI) to Done (unless it is Removed) -->
<rule name="AutoClose"
      appliesTo="Task">
<![CDATA[
if ($self.HasParent())
{
  if (-not $parent.State -eq 'Removed') {
          if (-not (Get-Siblings $self | where { 'Done','Removed' -notcontains $_.State })) {
                $parent.State = 'Done'
          }
  }
}
]]>
```

  </rule>

```
<!-- When any Tasks are In Progress set the parent (Bug or PBI) to In Progress -->
<rule name="AutoStart"
      appliesTo="Task">
  <![CDATA[
  if ($self.HasParent())
  {
          if (-not $parent.State -eq 'Removed') {
              if (Get-Siblings $self | where { 'In Progress','Ready For Test' -contains $_.State }) {
                  $parent.State = 'In Progress'
              }
          }
  }
  ]]>
</rule>

<policy name="DefaultPolicy">
    <collectionScope
        collections="*"
        />
    <ruleRef name="AutoStart" />
    <ruleRef name="AutoClose" />
</policy>
```

</AggregatorConfiguration>

**Comment by giuliov** [comment]
I am sorry to say that the `Get-Siblings` cmdlet is not implemented; you can use `$self.Children`. Keep in mind that we have less test coverage for Powershell, so expect a more bumpy road, and any contribution is appreciated.

**Comment by jessehouwing** [comment]
What would be needed to support get-childitem and get-siblings? I tried
finding such information, but couldn't find any...

**Comment by giuliov** [comment]
IIRC gci requires implementing a [PS Provider](https://technet.microsoft.com/en-us/library/ee126198(v=vs.85).aspx) which is not trivial and out-of scope. 

I think some helper cmdlet is within our reach, but not more... and would postpone to a future version and focusing on RTM in the next weeks.

**Comment by jessehouwing** [comment]
Agreed.

**Comment by jessehouwing** [comment]
Looks like this will need to be a `ContainerCmdletProvider` to be the least and possibly `ItemCmdletProvider`.

This would be indeed out of scope for v2 RTM.

**Comment by giuliov** [comment]
I will review docs and sample when I finish with merging your work.

**Comment by giuliov** [comment]
Removing `allInOne.policies` as it creating useless confusion

**Comment by JuliusMaximus** [comment]
It doesn't seem to matter which policy file I use I still get the error message. Below is the error and the policy file being used. Maybe I am just doing something wrong?

Order of events with console app:
Configuration loaded successfully
Built a new work item repository for (url)
Building Script Engine for C#
Starting processing on workitem #
Policy scope Collections(*) matches (collection name)
Then this error is thrown:
[Critical]    00.460 Exception encountered processing notification: Object reference not set to an instance of an object.
Stack Trace:   at Aggregator.Core.Facade.WorkItemRepository.GetWorkItem(Int32 workItemId) in C:\projects\tfsaggregator\Aggregator.Core\Facade\WorkItemRepository.cs:line 45
   at Aggregator.Core.EventProcessor.ProcessEvent(IRequestContext requestContext, INotification notification) in C:\projects\tfsaggregator\Aggregator.Core\EventProcessor.cs:line 58
   at Aggregator.ConsoleApp.RunCommand.Run(String[] remainingArguments) in C:\projects\tfsaggregator\Aggregator.ConsoleApp\RunCommand.cs:line 117


Policy file:
<?xml version="1.0" encoding="utf-8"?>
<AggregatorConfiguration>
    <runtime debug="true">
        <logging level="Diagnostic" />
        <script language="C#" />
        <authentication autoImpersonate="true" />
    </runtime>

    <rule name="MyFirstRule" appliesTo="Task" hasFields="Title">
        <![CDATA[
        logger.Log("Test");
        ]]>
    </rule>

    <policy name="MyFirstPolicy">
        <collectionScope collections="*" />
        <ruleRef name="MyFirstRule" />
    </policy>

</AggregatorConfiguration>

**Comment by giuliov** [comment]
Seems that it failed connecting to TFS. The command line should look like
```
TFSAggregator2.ConsoleApp run --policyFile=path_to_policies_file --teamProjectCollectionUrl=http://localhost:8080/tfs/DefaultCollection --teamProjectName=TfsAggregatorTest1 --workItemId=2
```
