### ISSUE TITLE
Create integration test framework

### ISSUE THREAD

**Issue by jessehouwing** [tfsaggregator/tfsaggregator#76]
Right now most unit tests rely heavily on the Mock implementation. A few bugs turned out to be issues where the mock did something slightly different than the real thing.

I'd love there to be an integration test project which does:
- [ ] destroy all work items in the project(s)
- [ ] allow us to create a number of work items
- [ ] apply a number of changes
- [ ] run a specific rule or ruleset
- [ ] validate the expected outcome of the rule
- [ ] cleans up the mess the test just created

I'd like this to
- use the infrastructure of the Console application, so that we don't have to deploy the TFS Aggregator to the server (that way we could even test against VSO).
- not rely on existing work items, but always creates the work items needed for the test
- use pre-created team projects with a specific process template installed
- use pre-defined users, teams, groups, iterations and areas (could use the ScrumRobot from Richard Hundhausen to set those up).

It doesn't have to:
- Create the team projects each time (takes too long and is a brittle process)
- transform the process template on the fly (though that would be nice and could steal from WitMorph)
- be independent on the TFS version to run the tests against.

**Comment by giuliov** [comment]
I did something in the past, need to look in my archives.

**Comment by jessehouwing** [comment]
I may have a volunteer: https://twitter.com/kverhaar/status/654475276274003968

**Comment by giuliov** [comment]
Good. I remember that I played at the SQL level to zap the Collection database (see https://github.com/giuliov/WitSync/tree/master/WitSyncEngine.Tests).

**Comment by jessehouwing** [comment]
Let's not take that route ;)
