### ISSUE TITLE
Publish Aggregator

### ISSUE THREAD

**Issue by giuliov** [tfsaggregator/tfsaggregator#80]
With RC/RTM we should update / inform:
- [x] [Codeplex](https://tfsaggregator.codeplex.com/)
- [x] [Visual Studio Gallery](https://visualstudiogallery.msdn.microsoft.com/site/upload)
- [x] ALM Rangers channels
- [x] ALM MVP channels
- [x] Twitter

Last minute tasks
- [x] Review wiki
- [x] Create Release
- [x] Set final version numbers in AssemblyInfo.cs and Wix project on master

**Comment by jessehouwing** [comment]
Can we add: 

 * [ ] can we add the `.pdb` files in the debug msi?

**Comment by giuliov** [comment]
Created an issue for this
