### ISSUE TITLE
TFS 2015 SP1

### ISSUE THREAD

**Issue by nancpasc** [tfsaggregator/tfsaggregator#81]
Hi guys,

It seems that TFS2015 Update 1 will break compatibility with some server-side plugins.

http://blogs.msdn.com/b/visualstudioalm/archive/2015/10/13/breaking-change-in-tfs-2015-update-1-for-server-side-plugins.aspx

Will this impact the TFS aggregator plugin and do you plan to make your release compatible with TFS2015Update 1 ?

Thanks a lot.

**Comment by jessehouwing** [comment]
We already did the work required. If additional changer are needed for the final of update 1 we'll try to incorporate those as soon as it is available.

**Comment by CRMBricks** [comment]
TFS Aggregator worked fine until we installed the TFS Update1 last week.
I set the logoutput in the policies to "diagnostics" but I cant see any output in the eventlogger.
Do you have any suggestions, how to find the error?

**Comment by jessehouwing** [comment]
@CRMBricks you'll need to uninstall and re-install the Aggregator.

There have been breaking API changes and our installer drops a different version of the aggregator when you re-install it.

**Comment by CRMBricks** [comment]
Thanks it works :)
