### ISSUE TITLE
TFS 2012 is not supported

### ISSUE THREAD

**Issue by DavidTuke** [tfsaggregator/tfsaggregator#83]
Hi All;

Good work - very useful add-on to TFS

I am on TFS 2012; any chance of this working with TFS 2012?;  Anyone tried it?

I am currently using TFS Aggregator V1; but some aspects not working (multiplication in particular

**Comment by giuliov** [comment]
Shortly, it may work but we do not have resources to test that version.

Some additional detail if you want to try:
* the API has not changed from 2010 to 2015 RTM, so 2013 source code is ok
* fork the project
* add additional Solution and Project configurations, say `Debug-2012` and `Release-2012`
* set the proper .Net version on the projects for this new configurations
* check that the new configuration defines **TFS2013** _or_ add a `TFS2012` to the `#if`
* Add 2012 folder under Reference and copy there the 2012 binaries
* If you are really brave, add the 2012 flavor to the setup project (still undocumented, sorry).
Build and cross fingers

In any case, you should use Visual Studio 2015, as the source requires a recent compiler.

The other option, is to look into v1 codebase; the latest fixes on v1.0.1 tag).

**Comment by jessehouwing** [comment]
In theory the 2013 version will build against 2012, but you may need to grab the right references as Microsoft moved  bunch interfaces around, which is why we officially support TFS 2013 update 2 and higher...
