### ISSUE TITLE
Sample NewObjects

### ISSUE THREAD

**Issue by michaeljprentice** [tfsaggregator/tfsaggregator#89]
Thank you for sharing TfsAggregator!

I was testing out the NewObjects.policies examples and ran into an issue.  Specifically with the NewTask rule.

This is with TFS 2015 Update 1 RC2, TfsAggregator v2.0-RC1

```csharp
    <!-- WorkItems -->
    <rule name="NewTask"
          appliesTo="Bug">
        <![CDATA[
        var parent = self;
        //var child = store.MakeNewWorkItem(self.ProjectName, "Task");
        var child = store.MakeNewWorkItem("TfsAggregatorTest1", "Task");
        child["Title"] = "Task auto-generated for " + parent["Title"];
        parent.AddWorkItemLink(child, WorkItemImplementationBase.ChildRelationship);
        ]]>
    </rule>
```
self.ProjectName doesn't appear to be valid, nor does just self as explained in the wiki.  I wasn't able to get it to work even while manually defining the Project as shown above.

**Just as self**

```
[Error]       00.772 Error CS1502 in script 'NewTask' at line 4, column 21: The best overloaded method match for 'Aggregator.Core.Interfaces.IWorkItemRepositoryExposed.MakeNewWorkItem(string, string)' has some invalid arguments
[Error]       00.772 Error CS1503 in script 'NewTask' at line 4, column 43: Argument 1: cannot convert from 'Aggregator.
Core.Interfaces.IWorkItemExposed' to 'string
```

**with self.ProjectName**
```
[Error]       00.881 Error CS1061 in script 'NewTask' at line 4, column 48: 'Aggregator.Core.Interfaces.IWorkItemExposed
' does not contain a definition for 'ProjectName' and no extension method 'ProjectName' accepting a first argument of type 'Aggregator.Core.Interfaces.IWorkItemExposed' could be found (are you missing a using directive or an assembly reference?)
```

**Explicit Project Name**
```
[Critical]    01.570 Exception encountered processing notification: TF237128: Target workitem Id should be set before ad
ding link to collection.
Stack Trace:   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemLink.InternalAdd(WorkItem workItem)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemLinkCollection.Add(WorkItemLink link)
   at Aggregator.Core.Facade.WorkItemWrapper.AddWorkItemLink(IWorkItemExposed destination, String linkTypeName, IEnumerable`1 availableLinkTypes)
   at Aggregator.Core.Facade.WorkItemWrapper.AddWorkItemLink(IWorkItemExposed destination, String linkTypeName)
   at RESERVED.Script_NewTask.RunScript(IWorkItemExposed self, IWorkItemRepositoryExposed store, IRuleLogger logger)
   at Aggregator.Core.Script.DotNetScriptEngine`1.RunScript(Assembly assembly, String scriptName, IWorkItem self, IWorkItemRepository store)
   at Aggregator.Core.Script.DotNetScriptEngine`1.Run(String scriptName, IWorkItem workItem, IWorkItemRepository store)
   at Aggregator.Core.EventProcessor.ApplyRule(Rule rule, IWorkItem workItem)
   at Aggregator.Core.EventProcessor.ApplyRules(IWorkItem workItem, IEnumerable`1 rules)
   at Aggregator.Core.EventProcessor.ProcessEvent(IRequestContext requestContext, INotification notification)
   at Aggregator.ConsoleApp.RunCommand.Run(String[] remainingArguments)
```

**Comment by giuliov** [comment]
The `MakeNewWorkItem` overload, taking just `self` has not reached the master branch.

As for the second case, there is no `ProjectName` property; probably we considered adding but never started implementing.

The last case, using a literal string for the project name, must work, but probably the sample code has never been tested against TFS. The error happens in the `AddWorkItemLink` call: this happens as the new work item was never saved, as I discovered writing another tool (I noted this link <https://social.msdn.microsoft.com/Forums/vstudio/en-US/0cbc378b-09ad-4899-865d-b418aecb8375/work-item-links-error-message-unexplained> as explanation of double save).

Shortly: **this sample is bugged**. To fix I can think of three options:
1. Add a check to automatically save new work items and keep the sample
2. Expose a Save method on `self` and change the sample

@jessehouwing I prefer (2) as (1) can be tricky

**Comment by giuliov** [comment]
I just pushed a possible solution to GetGlobalList PR

**Comment by jessehouwing** [comment]
I demoed this last week at the MVP summit and ran into similar issues. To
solve I refactored  the code a bit to allow passing in the existing work
item. The alternative is to make sure you include a cast to string when
assigning the System.TeamProject property.

     (string)Self["System.TeamProject"]

The other thing that is messing with this sample is that after creating a
new work item the sparsification kicks in, causing another 2 workitem
revisions being created most instantly, causing the first save to be
discarded.

I worked around this by checking whether the workitem already had children
and retrying until succeeded.

In the sample I also changed the link creation direction to make sure only
the new workitem was changed with regards to the link.

That together worked just fine.

**Comment by jessehouwing** [comment]
Sample policy used for demo purposes last week, so I know it worked at least a week ago ;):

```
    <!-- WorkItems -->
    <rule name="NewTask"
          appliesTo="Bug">
        <![CDATA[
        var parent = self;
        if (!self.HasChildren())
        {
            var child = store.MakeNewWorkItem((string)parent["System.TeamProject"], "Task");
            child["Title"] = "Task auto-generated for " + parent["Title"];
            child.AddWorkItemLink(parent, WorkItemImplementationBase.ParentRelationship);
        }
        ]]>
    </rule>
```

**Comment by jessehouwing** [comment]
This should also work in the most recent build:

```
    <!-- WorkItems -->
    <rule name="NewTask"
          appliesTo="Bug">
        <![CDATA[
        var parent = self;
        if (!self.HasChildren())
        {
            var child = store.MakeNewWorkItem(self, "Task");
            child["Title"] = "Task auto-generated for " + parent["Title"];
            child.AddWorkItemLink(parent, WorkItemImplementationBase.ParentRelationship);
        }
        ]]>
    </rule>
```

**Comment by giuliov** [comment]
Finished implementing integration tests (PR #92) to catch these scenarios.
