### ISSUE TITLE
TFS 2013 RTM and Update 1 are not supported

### ISSUE THREAD

**Issue by josh-endries** [tfsaggregator/tfsaggregator#93]
I just installed this via the debug 2.0.114 MSI (I tried release also) on our TFS2013 server and saw no errors but can't get it to work... This is my current file:

C:\Program Files\Microsoft Team Foundation Server 12.0\Application Tier\Web Services\bin\Plugins\TFSAggregator2.ServerPlugin.policies

```
<?xml version="1.0" encoding="utf-8"?>
<AggregatorConfiguration>
    <runtime debug="false">
        <rateLimiting interval="00:00:05.0" changes="5" />
        <logging level="Verbose" />
        <script language="C#" />
        <authentication autoImpersonate="false" />
    </runtime>
    <rule name="Log" appliesTo="Task"><![CDATA[
        logger.Log(LogLevel.Warning, "Warning");
        logger.Log("Default");
        System.Diagnostics.Trace.WriteLine("Trace WL");
        System.Diagnostics.Trace.TraceError("Trace Error");
        var date = System.DateTime.Now.ToString();
        System.IO.File.WriteAllText(@"c:\tmp\test.txt", date);
    ]]> 
    </rule>
    <policy name="DefaultPolicy">
        <collectionScope collections="*" />
        <ruleRef name="Log" />
    </policy>
</AggregatorConfiguration>
```

Unfortunately I don't see anything in DebugView even with all the event sources enabled and the file doesn't get created (c:\tmp is writable by everyone). I've tried just logger, just trace, changing work items and other stuff too.

After installation on the server, I didn't reboot or restart any services, in case that's necessary. I've tried moving the file and DLLs out and in, editing the policies file in place vs. copying/moving, and various other policies that should have modified something. Everything seems to work fine in the aggregator console app, but nothing happens when I actually change a work item via the TFS web UI.

I'm not sure if it isn't running at all, or something else is going wrong, since there is no logging at all. I'm guessing that it isn't even loading or executing.

If I change the file, copy over the existing one, log into TFS and change a work item task this is what I see in DebugView (everything in the Capture menu is enabled):

[12180] w3wp.exe Information: 0 : 
[12180] Updated Trace Settings 
[12180] w3wp.exe Information: 0 : 
[12180] Initialized the Trace Configurations 
[12180] Registering ChatRoom Routes 

The Troubleshooting page mentions using the right version for the right server, but on the releases page I only see one version. It also references names for source and destination fields but I have no idea what those are.

I was able to create a DLL and class that implements ISubscriber and works, but TFS Aggregator is a lot easier to use, and I'm not sure if ISubscriber will let me do the same stuff anyway. I'm not sure what else to check or try at this point.

**Comment by giuliov** [comment]
Which 2013 version?
I discovered the other day that Update 5 is ok, but 2013 RTM does not work, but I hadn't time to investigate.

**Comment by jessehouwing** [comment]
TFS 2013 update 2 had breaking changes with regards to where (in which
assemblies) what classes were. We build against the newer locations. We'd
need to have a 4th project configuration to support 2013 rtm.

If you're willing to install server side plugins, you should by willing to
upgrade to update 5.

**Comment by fzzzt** [comment]
Thanks for the response. Looks like version 12.0.21106.0, which I think is one step up from RTM if my google-fu is working. I'll ask the system guys about updating.

**Comment by fzzzt** [comment]
I'm not sure I'd classify this as a bug. We will be updating TFS this weekend so hopefully next week this will be resolved; I'll update after retrying it. Thanks for the tip!

**Comment by jessehouwing** [comment]
The change to support rtm and update one is one of references only, should
by easy to fix, but I'm not sure we want to support yet another version.

**Comment by giuliov** [comment]
It's at least a documentation bug: we have not specified the 2013 versions' oddities.

**Comment by jessehouwing** [comment]
That seems the case. We may need to verify that in the installer as well
with a launch rule.

**Comment by fzzzt** [comment]
It looks like the plan is to upgrade to 2015. I don't see any open issues for that here on github; should it work just fine or are there known problems? Thanks again.

**Comment by jessehouwing** [comment]
I went through the docs and updated a number of pages to clearly spell out we need TFS 2013 update 2 or later. The breaking change which requires this, is the move of the WorkItemChangedEvent to a new assembly as outlined here: http://blogs.ripple-rock.com/rorystreet/2014/05/08/WhereIsWorkItemChangedEventInTFS2013Update2.aspx

Should anyone want to contribute a TFS 2013 RTM and update 1 compatible version, that's where you can find the information. The trick will require some creative work with the configuration switches and to tweak the tfsrreferences.targets file.

Closing this issue as Won't fix, though a pull request would be honored.

**Comment by giuliov** [comment]
I did a bit of work on this and is more than the assembly reference: ProcessTemplateVersion class is internal in 2013 RTM, so we need similar code

```
#if TFS2013RTM
   Assembly asm = Assembly.Load("Microsoft.TeamFoundation.Framework.Server");
   Type asmType = asm.GetType("Microsoft.TeamFoundation.Framework.Server.TeamFoundationSerializationUtility");
   MethodInfo mi = asmType.GetMethod("Deserialize", BindingFlags.Public | BindingFlags.Static, null, new Type[] { typeof(string) }, null);
   MethodInfo gmi = mi.MakeGenericMethod(new[] { typeof(ProcessTemplateVersion) });
   var result = (ProcessTemplateVersion)gmi.Invoke(null, new object[]{ rawVersion });
#else
   var result = TeamFoundationSerializationUtility.Deserialize<ProcessTemplateVersion>(rawVersion);
#endif
```

It is a good chance to align all folder/properties etc that refers to TFS versions.

**Comment by jessehouwing** [comment]
Or throw a not implemented exception in such cases... So far Microsoft
isn't setting the template version for on premise, so it doesn't work
anyway.
