### ISSUE TITLE
Access URI of workitem

### ISSUE THREAD

**Issue by Checker1** [tfsaggregator/tfsaggregator#96]
Hello

Would it be possible to get access to the URI of the workitem, like we have access to the History? See the following link for info: https://msdn.microsoft.com/en-us/library/microsoft.teamfoundation.workitemtracking.client.workitem.uri(v=vs.120).aspx

**Comment by jessehouwing** [comment]
This would be a simple addition to the Work Item class and interfaces.

Fixed in Develop

**Comment by Checker1** [comment]
Thanks alot Jessehouwing :)

**Comment by Checker1** [comment]
Jesse, any idea when this will get merged to master and released? I would love to use it :)

**Comment by jessehouwing** [comment]
I suppose there is no harm in pushing that now. I'm not making a special release for just this feature, but you can grab the build in a couple of minutes.

**Comment by jessehouwing** [comment]
Should be available through: https://ci.appveyor.com/project/giuliov/tfsaggregator/build/2.0.139-master
