### ISSUE TITLE
How to assign WI to a user?

### ISSUE THREAD

**Issue by ASolovyev** [tfsaggregator/tfsaggregator#97]
Hi everybody!

i am trying to assign a WI to another user.

here is a code

    self["System.AssignedTo"]  = "SomeStrangerFromAD";

or

    self["MyOwn.TempUsr"] = "SomeStrangerFromAD";
    self["System.AssignedTo"] = (string)self["MyOwn.TempUsr"];

And both of them throwing an exception 
Exception encountered processing notification: Unable to cast object of type 'Microsoft.TeamFoundation.WorkItemTracking.Client.Field' to type 'System.String'. 

How can i assign a WI to a specific user?

**Comment by jessehouwing** [comment]
Just checked, there is a bug in the Incorrect field error handler, which I will push an update for. To assign a user, make sure you assign the display name of the user. That should work.

**Comment by jessehouwing** [comment]
Fixed in https://github.com/tfsaggregator/tfsaggregator/releases/tag/v2.01-RTM
