### ISSUE TITLE
More samples on state transitions and linklevel (traversing throught WI hierachy)

### ISSUE THREAD

**Issue by Bhuard1** [tfsaggregator/tfsaggregator#98]
Hi,

It would is useful to have a sample on changing states thru a parent hiearchies (linkLevel in V1).

For example in V1 when updaing the parent UserStory or Feature to Active
Sample AggregatorItem.xml: 

```xml
<!--When any Tasks are Active set the parent user story to Active. The condition is that the Target workitem state must currently be at state New-->
<AggregatorItem name="ActivateUserStory" operationType="String" linkType="Parent" linkLevel="1" workItemType="Task">
		<Mappings>
			<Mapping targetValue="Active" inclusive="Or">
				<SourceValue>Active</SourceValue>
			</Mapping>
		</Mappings>
		<Conditions>
			<Condition leftField="State" operator="Equal" rightValue="New"/>
		</Conditions>
		<TargetItem name="State"/>
		<SourceItem name="State"/>
	</AggregatorItem>
	<!--When any Tasks are Active set the parent user story or feature to Active -->
	<AggregatorItem name="ActivateFeature_Level2"
		 operationType="String" linkType="Parent" linkLevel="2" workItemType="Task">
		<Mappings>
			<Mapping targetValue="Active" inclusive="Or">
				<SourceValue>Active</SourceValue>
			</Mapping>
		</Mappings>
		<Conditions>
			<Condition leftField="State" operator="Equal" rightValue="New"/>
		</Conditions>
		<TargetItem name="State"/>
		<SourceItem name="State"/>
	</AggregatorItem>
```

Thanks for considering

**Comment by jessehouwing** [comment]
something like:

```
<rule name="AutoActivate" appliesTo="Task,Bug,User Story,Feature">
    if (self["System.State"] == "Active" && self.HasParent && self.Parent["System.State"] != "New")
    {
        self.Parent.TransitionToState("Active");
    }
</rule>
```

This rule should auto-cascade, once the task is saved, it will update the Story which will trigger this rule again and update the feature, which will trigger the rule and update the Epic if there is one.

**Comment by Bhuard1** [comment]
Hi,
Thanks for the quick response.

Once you know it much more simple syntax

In the current conditions I was trying out, I had to add the .ToSting() for my condiftions to work (at least in the console helper)
ex: if (self.Parent["State"].ToString() == "New")

**Comment by jessehouwing** [comment]
Yeah, you may need to do some casting, as values are returned as objects. It's safer to cast than to call ToString, unless you add a null check to be sure the field actually has a value. I updated the sample above.

**Comment by Bhuard1** [comment]
Thanks for the tips. I do very little programming. This was very helpfull.

Note: The TransitionToState method expects two parameters a comment (I found the method in the source code), 
I could also have done self.Parent["State"] = "Active" but I prefer to use build your methods.

For those interested this is what I came up with (I commetted out my logger)

```XML
  <rule name="AutoActivateParents" appliesTo="Task,Bug,User Story,Feature">
    <![CDATA[
    if (((string)self["System.State"] == "Active") && self.HasParent() && ((string)self.Parent["System.State"]) == "New")
    {
         self.Parent.TransitionToState("Active","TFSAgregator"); 
         //logger.Log("In Condition child: {1} #{0}! and parent ID: {2} parent State:{3}  ", self.Id, self["State"], self.Parent.Id,self.Parent["State"]);
    }
    ]]>
  </rule>
```
